
import { TableColumnsType, Tag, Popconfirm } from 'antd';
import { FeeAdjustmentFeeItemProps,FeeAdjustmentItemProps } from "@/types/finance_manage/fee_adjustment";
import i18n from '@/i18n';
import LocaleHelper from '@/utils/locale';
import { NavLink } from 'react-router-dom';



export const getColumns = (handleEdit: (record: FeeAdjustmentItemProps) => void, handleDelete: (record: FeeAdjustmentItemProps) => void): TableColumnsType<FeeAdjustmentItemProps> => [

    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentBusinessId()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BusinessId',
        sorter: true,
        align: 'left',
        fixed: 'left',
        render: (text) => <a>{text}</a>,
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentConsignor()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Consignor',
        sorter: true,
        align: 'left',
        fixed: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentBookingAgent()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BookingAgent',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentShippingCompany()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'ShippingCompany',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentSailingDate()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'SailingDate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentVesselVoyage()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'VesselVoyage',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentMblNumber()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'MblNumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentMblType()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'MblType',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentBusinessStatus()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BusinessStatus',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentSalesPerson()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'SalesPerson',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentBlStatus()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BlStatus',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentSysAuditStatus()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'SysAuditStatus',
        sorter: true,
        align: 'center',
        render: (text) => {
            if (text === '正常') {
                return <Tag color='green'>{text}</Tag>;
            }
            else {
                return <Tag color='red'>{text}</Tag>;
            }
        },
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentReleaseAuditStatus()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'ReleaseAuditStatus',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentAuditTime()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'AuditTime',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentHoldTime()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'HoldTime',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentHoldReason()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'HoldReason',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentContractValid()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'ContractValid',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentInvoiced()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Invoiced',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentFullyWrittenOff()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'FullyWrittenOff',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentOverdue()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Overdue',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentOverLimit()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'OverLimit',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentRemarks()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Remarks',
        sorter: true,
        align: 'left',
    },
    {
        title: '操作',
        key: 'operation',
        fixed: 'right',
        width: 40,
        render: (_, record) => (
        <>
            <NavLink to={`/orders/detail?businessId=${record.BusinessId}`}>详细</NavLink>
        </>
        ),
    },
]; 

export const getFeeColumns = (handleEdit: (record: FeeAdjustmentFeeItemProps) => void, handleDelete: (record: FeeAdjustmentFeeItemProps) => void): TableColumnsType<FeeAdjustmentFeeItemProps> => [
    {
        title: '业务编号',
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BusinessId',
        sorter: true,
        align: 'left',
        fixed: 'left',
    },
    {
        title: '费用编码',
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'FeeCode',
        sorter: true,
        align: 'left',
        fixed: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentConsignor()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Consignor',
        sorter: true,
        align: 'left',
        fixed: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentBookingAgent()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BookingAgent',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentShippingCompany()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'ShippingCompany',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentSailingDate()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'SailingDate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentVesselVoyage()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'VesselVoyage',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentMblNumber()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'MblNumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentFeeSettlementUnitCode()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'SettlementUnitCode',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentFeeSettlementUnitName()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'SettlementUnitName',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentFeeFeeName()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'FeeName',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentFeeTransactionType()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'TransactionType',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentFeeCurrencyCode()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CurrencyCode',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentFeeAmount()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Amount',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentFeeDomesticForeign()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'DomesticForeign',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentFeeSettledAmount()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'SettledAmount',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentFeeUnsettledAmount()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'UnsettledAmount',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentFeePayableAmount()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'PayableAmount',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentFeeRelatedBlNumber()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'RelatedBlNumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentFeeBillType()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BillType',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getFeeAdjustmentFeeSettlementNumber()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'SettlementNumber',
        sorter: true,
        align: 'left',
    },
    {
        title: '操作',
        key: 'operation',
        fixed: 'right',
        width: 40,
        render: (_, record) => (
        <>
            <NavLink to={`/orders/detail?businessId=${record.BusinessId}`}>详细</NavLink>
        </>
        ),
    },
]; 
