
import request, { ApiRes, requestWithProgress } from '../../request'
import { BaseAirPortItemProps } from "@/types/dynamic_configuration_platform/basic_manage/base_airport";
import Mock from "mockjs";
//
const baseSeaportItems: BaseAirPortItemProps[] = [
    {
        "Id": "0",
        "Code": "BCN",
        "NameCn": "巴塞罗那",
        "NameEn": "BARCELONA",
        "CountryRegion": "SPAIN",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "BUQ",
        "NameCn": "布拉瓦约",
        "NameEn": "BULAWAYO",
        "CountryRegion": "ZIMBABWE",
        "CityCode": "",
        "CityName": "",
        "Area": "非洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "CMR",
        "NameCn": "科尔马",
        "NameEn": "COLMAR",
        "CountryRegion": "FRANCE",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "RMI",
        "NameCn": "里米尼",
        "NameEn": "RIMINI",
        "CountryRegion": "ITALY",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "JST",
        "NameCn": "约翰斯顿",
        "NameEn": "JOHNSTOWN",
        "CountryRegion": "UNITED STATES",
        "CityCode": "",
        "CityName": "",
        "Area": "中美洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "AGA",
        "NameCn": "阿加迪尔",
        "NameEn": "AGADIR",
        "CountryRegion": "MOROCCO",
        "CityCode": "",
        "CityName": "",
        "Area": "非洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "BGF",
        "NameCn": "班吉",
        "NameEn": "BANGUI",
        "CountryRegion": "CENTRAL AFRICAN REPUBLIC",
        "CityCode": "",
        "CityName": "",
        "Area": "非洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "PSR",
        "NameCn": "佩斯卡拉",
        "NameEn": "PESCARA",
        "CountryRegion": "ITALY",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "YSJ",
        "NameCn": "圣约翰",
        "NameEn": "SANIT JOHN",
        "CountryRegion": "CANADA",
        "CityCode": "",
        "CityName": "",
        "Area": "加拿大",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "RUH",
        "NameCn": "利雅得",
        "NameEn": "RIYADH",
        "CountryRegion": "SAUDI ARABIA",
        "CityCode": "",
        "CityName": "",
        "Area": "中东",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "CMG",
        "NameCn": "科龙巴",
        "NameEn": "CORUMBA",
        "CountryRegion": "BRAZIL",
        "CityCode": "",
        "CityName": "",
        "Area": "南美洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "TSE",
        "NameCn": "科龙巴",
        "NameEn": "AQMOLA",
        "CountryRegion": "KAZAKHSTAN",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "OSI",
        "NameCn": "奥西耶克",
        "NameEn": "OSIJEK",
        "CountryRegion": "CROATIA",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "MTY",
        "NameCn": "蒙特雷",
        "NameEn": "MONTERREY",
        "CountryRegion": "MEXICO",
        "CityCode": "",
        "CityName": "",
        "Area": "中美洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "YNG",
        "NameCn": "扬斯敦",
        "NameEn": "YOUNGSTOWN WARREN",
        "CountryRegion": "UNITED STATES",
        "CityCode": "",
        "CityName": "",
        "Area": "中美洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "EFL",
        "NameCn": "凯法利尼亚",
        "NameEn": "KEFALLINIA",
        "CountryRegion": "GREECE",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "MLN",
        "NameCn": "梅利拉",
        "NameEn": "MELILLA",
        "CountryRegion": "SPAIN",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "RHQ",
        "NameCn": "梅利拉",
        "NameEn": "RHODES",
        "CountryRegion": "GREECE",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "DZA",
        "NameCn": "梅利拉",
        "NameEn": "DZAOUDZI",
        "CountryRegion": "MAYOTTE",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "TWU",
        "NameCn": "斗湖",
        "NameEn": "TAWAU",
        "CountryRegion": "MALAYSIA",
        "CityCode": "",
        "CityName": "",
        "Area": "东南亚",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "PED",
        "NameCn": "斗湖",
        "NameEn": "PARDUBICE INT'L",
        "CountryRegion": "CZECH REPUBLIC",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "NCY",
        "NameCn": "阿内西",
        "NameEn": "ANNECY",
        "CountryRegion": "FRANCE",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "GYE",
        "NameCn": "瓜亚基尔",
        "NameEn": "GUAYAQUIL",
        "CountryRegion": "ECUADOR",
        "CityCode": "",
        "CityName": "",
        "Area": "南美洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "HNL",
        "NameCn": "火奴鲁鲁",
        "NameEn": "HONOLULU",
        "CountryRegion": "UNITED STATES",
        "CityCode": "",
        "CityName": "",
        "Area": "中美洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "KBL",
        "NameCn": "喀布尔",
        "NameEn": "KABUL",
        "CountryRegion": "AFGHANISTAN",
        "CityCode": "",
        "CityName": "",
        "Area": "中东",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "SAW",
        "NameCn": "萨比哈－哥克赛恩",
        "NameEn": "SABIHA GOKCEN",
        "CountryRegion": "TURKEY",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "PBG",
        "NameCn": "普拉茨堡",
        "NameEn": "PLATTSBURG",
        "CountryRegion": "UNITED STATES",
        "CityCode": "",
        "CityName": "",
        "Area": "中美洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "ATW",
        "NameCn": "阿普尔顿",
        "NameEn": "APPLETON",
        "CountryRegion": "UNITED STATES",
        "CityCode": "",
        "CityName": "",
        "Area": "中美洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "MSJ",
        "NameCn": "三泽",
        "NameEn": "MISAWA",
        "CountryRegion": "JAPAN",
        "CityCode": "",
        "CityName": "",
        "Area": "东南亚",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "MAR",
        "NameCn": "马拉开波",
        "NameEn": "MARACAIBO",
        "CountryRegion": "VENEZUELA",
        "CityCode": "",
        "CityName": "",
        "Area": "南美洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "BOD",
        "NameCn": "波尔多",
        "NameEn": "BORDEAUX",
        "CountryRegion": "FRANCE",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "PIK",
        "NameCn": "格拉斯哥",
        "NameEn": "GLASGOW",
        "CountryRegion": "UNITED KINGDOM",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "GPO",
        "NameCn": "格拉斯哥",
        "NameEn": "GENERAL PICO",
        "CountryRegion": "ARGENTINA",
        "CityCode": "",
        "CityName": "",
        "Area": "南美洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "VHY",
        "NameCn": "格拉斯哥",
        "NameEn": "VICHY",
        "CountryRegion": "FRANCE",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "INN",
        "NameCn": "因斯布鲁克",
        "NameEn": "INNSBRUCK",
        "CountryRegion": "AUSTRIA",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "SBP",
        "NameCn": "圣路易斯欧匹斯堡",
        "NameEn": "SAN LUIS OBISPO",
        "CountryRegion": "UNITED STATES",
        "CityCode": "",
        "CityName": "",
        "Area": "中美洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "HPN",
        "NameCn": "韦斯特切斯特",
        "NameEn": "WESTCHESTER COUNTY",
        "CountryRegion": "UNITED STATES",
        "CityCode": "",
        "CityName": "",
        "Area": "美西",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "NSK",
        "NameCn": "诺里尔斯克",
        "NameEn": "NORILSK",
        "CountryRegion": "RUSSIAN FEDERATION",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "ROA",
        "NameCn": "罗阿诺克",
        "NameEn": "ROANOKE",
        "CountryRegion": "UNITED STATES",
        "CityCode": "",
        "CityName": "",
        "Area": "美国内陆",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "ZAD",
        "NameCn": "扎达尔",
        "NameEn": "ZADAR",
        "CountryRegion": "CROATIA",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "DUR",
        "NameCn": "德班",
        "NameEn": "DURBAN",
        "CountryRegion": "SOUTH AFRICA",
        "CityCode": "",
        "CityName": "",
        "Area": "非洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "IWA",
        "NameCn": "德班",
        "NameEn": "WILLIAMS GATEWA",
        "CountryRegion": "UNITED STATES",
        "CityCode": "",
        "CityName": "",
        "Area": "中美洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "RAH",
        "NameCn": "拉夫哈",
        "NameEn": "RAFHA",
        "CountryRegion": "SAUDI ARABIA",
        "CityCode": "",
        "CityName": "",
        "Area": "中东",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "GAF",
        "NameCn": "加夫萨",
        "NameEn": "GAFSA",
        "CountryRegion": "TUNISIA",
        "CityCode": "",
        "CityName": "",
        "Area": "非洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "ALS",
        "NameCn": "阿拉莫萨",
        "NameEn": "ALAMOSA",
        "CountryRegion": "UNITED STATES",
        "CityCode": "",
        "CityName": "",
        "Area": "中美洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "YQX",
        "NameCn": "甘德市",
        "NameEn": "GANDER",
        "CountryRegion": "CANADA",
        "CityCode": "",
        "CityName": "",
        "Area": "加拿大",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "HKY",
        "NameCn": "甘德市",
        "NameEn": "HICKORY",
        "CountryRegion": "UNITED STATES",
        "CityCode": "",
        "CityName": "",
        "Area": "中美洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "CIA",
        "NameCn": "罗马",
        "NameEn": "ROME",
        "CountryRegion": "ITALY",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "RST",
        "NameCn": "罗切斯特",
        "NameEn": "ROCHESTER",
        "CountryRegion": "UNITED STATES",
        "CityCode": "",
        "CityName": "",
        "Area": "中美洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "MOT",
        "NameCn": "迈诺特",
        "NameEn": "MINOT",
        "CountryRegion": "UNITED STATES",
        "CityCode": "",
        "CityName": "",
        "Area": "中美洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "SVX",
        "NameCn": "叶卡特琳堡",
        "NameEn": "EKATERINBURG",
        "CountryRegion": "RUSSIAN FEDERATION",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "VAF",
        "NameCn": "叶卡特琳堡",
        "NameEn": "VALENCE/CHABEUIL",
        "CountryRegion": "FRANCE",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "PRA",
        "NameCn": "叶卡特琳堡",
        "NameEn": "PARANA",
        "CountryRegion": "ARGENTINA",
        "CityCode": "",
        "CityName": "",
        "Area": "南美洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "VRN",
        "NameCn": "维罗纳",
        "NameEn": "VERONA",
        "CountryRegion": "ITALY",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "MOD",
        "NameCn": "莫德斯托",
        "NameEn": "MODESTO",
        "CountryRegion": "UNITED STATES",
        "CityCode": "",
        "CityName": "",
        "Area": "中美洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "MKY",
        "NameCn": "麦凯",
        "NameEn": "MACKAY",
        "CountryRegion": "AUSTRALIA",
        "CityCode": "",
        "CityName": "",
        "Area": "澳新",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "BMA",
        "NameCn": "斯德哥尔摩",
        "NameEn": "STOCKHOLM",
        "CountryRegion": "SWEDEN",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "CKG",
        "NameCn": "斯德哥尔摩",
        "NameEn": "CHONGQING",
        "CountryRegion": "CHINA",
        "CityCode": "",
        "CityName": "",
        "Area": "中国",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "KRT",
        "NameCn": "喀土穆",
        "NameEn": "KHARTOUM",
        "CountryRegion": "SUDAN",
        "CityCode": "",
        "CityName": "",
        "Area": "非洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "SKP",
        "NameCn": "斯科普里",
        "NameEn": "SKOPJE",
        "CountryRegion": "MACEDONIA, THE FORMER YUGOSLAV R",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "1",
        "Code": "DLE",
        "NameCn": "多勒",
        "NameEn": "DOLE",
        "CountryRegion": "FRANCE",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "QSA",
        "NameCn": "斯科普里",
        "NameEn": "SABADELL",
        "CountryRegion": "SPAIN",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "BER",
        "NameCn": "柏林",
        "NameEn": "BERLIN",
        "CountryRegion": "GERMANY",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "HEA",
        "NameCn": "柏林",
        "NameEn": "HERAT",
        "CountryRegion": "AFGHANISTAN",
        "CityCode": "",
        "CityName": "",
        "Area": "中东",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "NTE",
        "NameCn": "南特",
        "NameEn": "NANTES",
        "CountryRegion": "FRANCE",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "FIH",
        "NameCn": "金沙萨",
        "NameEn": "KINSHASA",
        "CountryRegion": "CONGO, THE DEMOCRATIC REPUBLIC O",
        "CityCode": "",
        "CityName": "",
        "Area": "非洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "DCM",
        "NameCn": "卡斯特尔",
        "NameEn": "CASTRES",
        "CountryRegion": "FRANCE",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "OST",
        "NameCn": "卡斯特尔",
        "NameEn": "OSTEND/BRUGES",
        "CountryRegion": "BELGIUM",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "URS",
        "NameCn": "卡斯特尔",
        "NameEn": "KURSK",
        "CountryRegion": "RUSSIAN FEDERATION",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "LBG",
        "NameCn": "巴黎",
        "NameEn": "PARIS",
        "CountryRegion": "FRANCE",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "EPL",
        "NameCn": "埃皮纳勒",
        "NameEn": "EPINAL",
        "CountryRegion": "FRANCE",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "KHY",
        "NameCn": "哈巴罗夫斯克",
        "NameEn": "KHABAROVSK",
        "CountryRegion": "RUSSIAN FEDERATION",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "MKC",
        "NameCn": "堪萨斯城",
        "NameEn": "KANSAS CITY",
        "CountryRegion": "UNITED STATES",
        "CityCode": "",
        "CityName": "",
        "Area": "中美洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "ASW",
        "NameCn": "阿斯旺",
        "NameEn": "ASWAN",
        "CountryRegion": "EGYPT",
        "CityCode": "",
        "CityName": "",
        "Area": "非洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "AGB",
        "NameCn": "慕尼黑",
        "NameEn": "MUNICH",
        "CountryRegion": "GERMANY",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "BIQ",
        "NameCn": "比亚丽兹",
        "NameEn": "BIARRITZ",
        "CountryRegion": "FRANCE",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "MGA",
        "NameCn": "马那瓜",
        "NameEn": "MANAGUA",
        "CountryRegion": "NICARAGUA",
        "CityCode": "",
        "CityName": "",
        "Area": "中美洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "YQG",
        "NameCn": "温莎",
        "NameEn": "WINDSOR",
        "CountryRegion": "CANADA",
        "CityCode": "",
        "CityName": "",
        "Area": "加拿大",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "ADL",
        "NameCn": "阿德莱德",
        "NameEn": "ADELAIDE",
        "CountryRegion": "AUSTRALIA",
        "CityCode": "",
        "CityName": "",
        "Area": "澳新",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "SEN",
        "NameCn": "绍森德",
        "NameEn": "SOUTHEND",
        "CountryRegion": "UNITED KINGDOM",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "HAH",
        "NameCn": "莫罗尼",
        "NameEn": "MORONI",
        "CountryRegion": "COMOROS",
        "CityCode": "",
        "CityName": "",
        "Area": "非洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "GWT",
        "NameCn": "韦斯特兰",
        "NameEn": "WESTERLAND",
        "CountryRegion": "GERMANY",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "DCA",
        "NameCn": "华盛顿",
        "NameEn": "WASHINGTON",
        "CountryRegion": "UNITED STATES",
        "CityCode": "",
        "CityName": "",
        "Area": "中美洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "IYK",
        "NameCn": "因约肯",
        "NameEn": "INYOKERN",
        "CountryRegion": "UNITED STATES",
        "CityCode": "",
        "CityName": "",
        "Area": "中美洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "TUL",
        "NameCn": "塔尔萨",
        "NameEn": "TULSA",
        "CountryRegion": "UNITED STATES",
        "CityCode": "",
        "CityName": "",
        "Area": "美西",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "AJA",
        "NameCn": "阿雅克肖",
        "NameEn": "AJACCIO",
        "CountryRegion": "FRANCE",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "KUF",
        "NameCn": "SAMARA",
        "NameEn": "SAMARA",
        "CountryRegion": "RUSSIAN FEDERATION",
        "CityCode": "",
        "CityName": "",
        "Area": "红海",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "ASU",
        "NameCn": "亚松森",
        "NameEn": "ASUNCION",
        "CountryRegion": "PARAGUAY",
        "CityCode": "",
        "CityName": "",
        "Area": "南美洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "FCO",
        "NameCn": "罗马",
        "NameEn": "ROME",
        "CountryRegion": "ITALY",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "TRK",
        "NameCn": "打拉根",
        "NameEn": "TARAKAN",
        "CountryRegion": "FINLAND",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "SID",
        "NameCn": "撒尔",
        "NameEn": "SAL",
        "CountryRegion": "CAPE VERDE",
        "CityCode": "",
        "CityName": "",
        "Area": "非洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "TLV",
        "NameCn": "特拉维夫－雅法",
        "NameEn": "TEL AVIV-YAFO",
        "CountryRegion": "ISRAEL",
        "CityCode": "",
        "CityName": "",
        "Area": "中东",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "ALC",
        "NameCn": "阿利坎特",
        "NameEn": "ALICANTE",
        "CountryRegion": "SPAIN",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "CEG",
        "NameCn": "切斯特",
        "NameEn": "CHESTER",
        "CountryRegion": "UNITED KINGDOM",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "BZR",
        "NameCn": "贝济耶",
        "NameEn": "BEZIERS",
        "CountryRegion": "FRANCE",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "FNC",
        "NameCn": "丰沙尔",
        "NameEn": "FUNCHAL",
        "CountryRegion": "PORTUGAL",
        "CityCode": "",
        "CityName": "",
        "Area": "欧洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "CVJ",
        "NameCn": "库埃纳瓦卡",
        "NameEn": "CUERNAVACA",
        "CountryRegion": "MEXICO",
        "CityCode": "",
        "CityName": "",
        "Area": "中美洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "TYR",
        "NameCn": "泰勒",
        "NameEn": "TYLER",
        "CountryRegion": "UNITED STATES",
        "CityCode": "",
        "CityName": "",
        "Area": "中美洲",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "DAM",
        "NameCn": "大马士革",
        "NameEn": "DAMASCUS",
        "CountryRegion": "SYRIAN ARAB REPUBLIC",
        "CityCode": "",
        "CityName": "",
        "Area": "中东",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    },
    {
        "Id": "0",
        "Code": "FUK",
        "NameCn": "福冈",
        "NameEn": "FUKUOKA",
        "CountryRegion": "JAPAN",
        "CityCode": "",
        "CityName": "",
        "Area": "东南亚",
        "BasePort": "否",
        "ExchangeCode": "",
        "IsoCode": "",
        "PortRequirements": ""
    }
];


// 获取账单管理台账列表
export const getBaseAirportList = async (): Promise<BaseAirPortItemProps[]> => {
    return baseSeaportItems;
}

// 保存账单管理
export const saveBaseAirport = async (data: BaseAirPortItemProps, onUploadProgress?: (progress: number) => void): Promise<BaseAirPortItemProps> => {
    // 模拟上传进度
    if (onUploadProgress) {
        let progress = 0;
        const interval = setInterval(() => {
            progress += 10;
            onUploadProgress(progress);
            if (progress >= 100) {
                clearInterval(interval);
            }
        }, 1000);
    }
    return data;
}


/*
// 获取币制信息
export const getBaseSeaportList = async (): Promise<BaseSeaportItemProps[]> => {
  const response = await request({
    method: "GET",
    url: "/base_seaport"
  })
  const responseData = response?.data as ApiRes<BaseSeaportItemProps[]>;
  return responseData.data || [];
}

export const saveBaseSeaport = (data:BaseSeaportItemProps,onUploadProgress: (progress: number) => void) => {
  return requestWithProgress({
    method: 'POST',
    url: "/base_seaport/save",
    data:data,
    onUploadProgress: (progress) => {
        onUploadProgress(progress);
    }
  })
}
*/
