
import request, {ApiRes,requestWithProgress } from '../../request'
import { BaseTaxTypeItemProps } from "@/types/dynamic_configuration_platform/basic_manage/base_tax_type";
import Mock from "mockjs";
//
const baseTaxTypeItems: BaseTaxTypeItemProps[] = [
    {
        "TaxTypeCode": "SD",
        "TaxTypeName": "印花税",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "季,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "孙凯",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "ROAF",
        "TaxTypeName": "其他行政事业性收费收入",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "周洋",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "RWCAF",
        "TaxTypeName": "水利行政事业性收费收入",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "李丹",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "RFGA",
        "TaxTypeName": "林业草原行政事业性收费收入",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "张伟",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "RAAF",
        "TaxTypeName": "农业行政事业性收费收入",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "王芳",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "RIIIAF",
        "TaxTypeName": "工业和信息产业行政事业性收费收入",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "刘健",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "RTAF_2",
        "TaxTypeName": "交通运输行政事业性收费收入",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "陈晨",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "RNRAF",
        "TaxTypeName": "自然资源行政事业性收费收入",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "赵敏",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "REAF",
        "TaxTypeName": "教育行政事业性收费收入",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "吴婷",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "RCADOAF",
        "TaxTypeName": "人防办行政事业性收费收入",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "杨帆",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "RTAF_1",
        "TaxTypeName": "税务行政事业性收费收入",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "黄琪",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "RFAF",
        "TaxTypeName": "财政行政事业性收费收入",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "郑宇",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "RPDF",
        "TaxTypeName": "排污费收入",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "胡颖",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "ROGF",
        "TaxTypeName": "其他政府性基金收入",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "高翔",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "RSDF",
        "TaxTypeName": "污水处理费收入",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "林静",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "REDF",
        "TaxTypeName": "可再生能源发展基金",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "徐磊",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "NPPSFDF",
        "TaxTypeName": "核电站乏燃料处理处置基金",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "马骏",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "RNMWCCF",
        "TaxTypeName": "国家重大水利工程建设基金收入",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "韩雪",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "PRSFLR",
        "TaxTypeName": "地方水库移民扶持基金",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "冯涛",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "RUISF",
        "TaxTypeName": "城市基础设施配套费收入",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "朱琳",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "TGRAF",
        "TaxTypeName": "三峡水库库区基金",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "韩磊",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "PRSFLMSR",
        "TaxTypeName": "大中型水库移民后期扶持基金",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "齐峰",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "RSOLURS",
        "TaxTypeName": "国有土地使用权出让收入",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "孟雨",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "RALDF",
        "TaxTypeName": "农业土地开发资金收入",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "姜楠",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "RSOLIF",
        "TaxTypeName": "国有土地收益基金收入",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "石磊",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "ARUPU",
        "TaxTypeName": "城市公用事业附加收入",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "贾雪",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "LMSRF",
        "TaxTypeName": "大中型水库库区基金",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "彭程",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "RAIF",
        "TaxTypeName": "建设行政事业性收费收入",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "苏萌",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "WSCCF",
        "TaxTypeName": "水土保持补偿费收入",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "季,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2020-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "何晶",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "VTT",
        "TaxTypeName": "船舶吨税",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2020-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "宋晨",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "TT",
        "TaxTypeName": "烟叶税",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2020-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "韩梅",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "CD",
        "TaxTypeName": "关税",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2020-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "吴刚",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "FVRF",
        "TaxTypeName": "森林植被恢复费",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "董倩",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "SIO",
        "TaxTypeName": "其他专项收入",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "丁玲",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "IIT",
        "TaxTypeName": "个人所得税",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "邱勇",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "RT",
        "TaxTypeName": "资源税",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "蒋琳",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "CCF",
        "TaxTypeName": "文化事业建设费",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "钱坤",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "TOCL",
        "TaxTypeName": "耕地占用税",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "沈冰",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "VPT",
        "TaxTypeName": "车辆购置税",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "唐瑶",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "VVT",
        "TaxTypeName": "车船税",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "年",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "韩旭",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "DT",
        "TaxTypeName": "契税",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "段晨",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "CT",
        "TaxTypeName": "消费税",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "江婷",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "ITLV",
        "TaxTypeName": "土地增值税",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "罗丹",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "ULUT",
        "TaxTypeName": "城镇土地使用税",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "朱婷",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "LEST",
        "TaxTypeName": "地方教育附加",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "金鑫",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "EST",
        "TaxTypeName": "教育费附加",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "施怡",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "UMCT",
        "TaxTypeName": "城市维护建设税",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "姚远",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "OR",
        "TaxTypeName": "其他收入",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "谭静",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "SIWCC",
        "TaxTypeName": "水利建设专项收入",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,年",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "许晨",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "EPT",
        "TaxTypeName": "环境保护税",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "叶辉",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "ESFD",
        "TaxTypeName": "残疾人就业保障金",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "季,年",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "贺琳",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "HPT",
        "TaxTypeName": "房产税",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,半年,年",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "彭博",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "CIT",
        "TaxTypeName": "企业所得税",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,年",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "2010-01-01 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "崔浩",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    },
    {
        "TaxTypeCode": "VAT",
        "TaxTypeName": "增值税",
        "TaxSystemName": "中国税制",
        "CountryRegion": "中国大陆",
        "TaxPeriod": "月,季,次",
        "TaxCurrency": "人民币",
        "PrecisionVal": 2,
        "RoundingRule": "四舍五入",
        "ExchangeType": "基准汇率",
        "EffectiveDate": "1993-12-13 00:00:00",
        "ExpiryDate": "",
        "CreatedBy": "吕涛",
        "CreatedTime": "2025-08-18 14:32:00",
        "Status": "启用"
    }
];


// 获取账单管理台账列表
export const getBaseTaxTypeList = async (): Promise<BaseTaxTypeItemProps[]> => {
    return baseTaxTypeItems;
}

// 保存账单管理
export const saveBaseTaxType = async (data: BaseTaxTypeItemProps, onUploadProgress?: (progress: number) => void): Promise<BaseTaxTypeItemProps> => {
    // 模拟上传进度
    if (onUploadProgress) {
        let progress = 0;
        const interval = setInterval(() => {
            progress += 10;
            onUploadProgress(progress);
            if (progress >= 100) {
                clearInterval(interval);
            }
        }, 1000);
    }
    return data;
}
