
import { TableColumnsType, Tag, Popconfirm } from 'antd';
import { HasOffSettingItemProps,OffSettingDetailItemProps } from "@/types/finance_manage/has_off_setting";
import i18n from '@/i18n';
import LocaleHelper from '@/utils/locale';



export const getColumns = (handleEdit: (record: HasOffSettingItemProps) => void, handleDelete: (record: HasOffSettingItemProps) => void): TableColumnsType<HasOffSettingItemProps> => [

    {
        title: i18n.t(LocaleHelper.getHasOffSettingWriteoffserialnumber()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Writeoffserialnumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingSettlementobject()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Settlementobject',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingBusinessnumber()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Businessnumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingSettlementagent()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Settlementagent',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingCounterparty()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Counterparty',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingOurbank()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Ourbank',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingPaymentnoticenumber()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Paymentnoticenumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingVouchernumber()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Vouchernumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingBankslipnumber()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Bankslipnumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingWriteoffperson()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Writeoffperson',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingWriteoffdate()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Writeoffdate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingReceiptpaymentdate()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Receiptpaymentdate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingPaymenttype()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Paymenttype',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingSlipstatus()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Slipstatus',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingReceiptpaymentmethod()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Receiptpaymentmethod',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingIsprepaid()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Isprepaid',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingCurrency()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Currency',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingAmount()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Amount',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingWrittenoffamount()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Writtenoffamount',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingBalance()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Balance',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingActualreceivedamount()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Actualreceivedamount',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingActualpaidamount()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Actualpaidamount',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingFinancialcharges()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Financialcharges',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingExchangegainloss()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Exchangegainloss',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingShortchange()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Shortchange',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingOriginalcurrencydifference()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Originalcurrencydifference',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingCreator()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Creator',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingReviewer()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Reviewer',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingReviewdate()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Reviewdate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingIscancelled()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Iscancelled',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingInvoiceinformation()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Invoiceinformation',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingRemarks()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Remarks',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingAccountperiod()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Accountperiod',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingVoucherdate()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Voucherdate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingReviewername()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Reviewername',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingBillsettlementtype()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Billsettlementtype',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingPrereceiptpaymentremarks()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Prereceiptpaymentremarks',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getHasOffSettingReceiptpaymentvouchernumber()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Receiptpaymentvouchernumber',
        sorter: true,
        align: 'left',
    },
    {
        title: '操作',
        key: 'operation',
        fixed: 'right',
        width: 60,
        render: (_, record) => (
        <>
            <a onClick={()=>handleEdit(record)}>详细</a>
        </>
        ),
    },
]; 

export const getDetailColumns = (handleEdit: (record: OffSettingDetailItemProps) => void, handleDelete: (record: OffSettingDetailItemProps) => void): TableColumnsType<OffSettingDetailItemProps> => [

    {
        title: i18n.t(LocaleHelper.getOffSettingDetailBusinessNumber()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BusinessNumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailMasterOrderNumber()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'MasterOrderNumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailSubOrderNumber()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'SubOrderNumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailEntrustingUnit()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'EntrustingUnit',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailSettlementObject()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'SettlementObject',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailVoyage()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Voyage',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailContainerType()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'ContainerType',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailBusinessDate()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BusinessDate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailFeeName()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'FeeName',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailPaymentType()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'PaymentType',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailWriteoffCurrency()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'WriteoffCurrency',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailWriteoffAmount()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'WriteoffAmount',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailWriteoffExchangeRate()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'WriteoffExchangeRate',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailOriginalCurrency()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'OriginalCurrency',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailOriginalAmount()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'OriginalAmount',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailOriginalExchangeRate()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'OriginalExchangeRate',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailConvertedAmount()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'ConvertedAmount',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailOriginalTotalAmount()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'OriginalTotalAmount',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailInvoiceNumber()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'InvoiceNumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailSales()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Sales',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailOperator()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Operator',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailCustomerService()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CustomerService',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailOurBank()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'OurBank',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailInvoiceDate()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'InvoiceDate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailWriteoffPerson()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'WriteoffPerson',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailWriteoffDate()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'WriteoffDate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailPaymentDate()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'PaymentDate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailReviewPerson()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'ReviewPerson',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailReviewDate()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'ReviewDate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getOffSettingDetailFeeRemark()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'FeeRemark',
        sorter: true,
        align: 'left',
    },
]; 

