
import { TableColumnsType, Tag, Popconfirm } from 'antd';
import { InvoiceIssuanceReceiptItemProps } from "@/types/invoice_issuance_receipt/invoice_issuance_receipt";
import i18n from '@/i18n';
import LocaleHelper from '@/utils/localeHelper';



export const getColumns = (handleEdit: (record: InvoiceIssuanceReceiptItemProps) => void, handleDelete: (record: InvoiceIssuanceReceiptItemProps) => void): TableColumnsType<InvoiceIssuanceReceiptItemProps> => [

    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptBusinessId()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BusinessId',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptSettlementUnit()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'SettlementUnit',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptMasterOrderNo()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'MasterOrderNo',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptSubOrderNo()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'SubOrderNo',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptInvoiceTitle()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'InvoiceTitle',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptReconciliationNo()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'ReconciliationNo',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptCustomer()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Customer',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptBusinessType()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BusinessType',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptBusinessDate()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BusinessDate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptBargeSailingDate()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BargeSailingDate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptVesselVoyage()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'VesselVoyage',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptPortOfLoading()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'PortOfLoading',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptPortOfDestination()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'PortOfDestination',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptSales()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Sales',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptAccrued()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Accrued',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptOperator()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Operator',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptFinanceDate()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'FinanceDate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptDomesticOrForeign()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'DomesticOrForeign',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptPaymentType()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'PaymentType',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptFeeStatus()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'FeeStatus',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptConfirmationStatus()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'ConfirmationStatus',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptFeeName()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'FeeName',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptCurrency()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Currency',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptCustomBusinessType()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CustomBusinessType',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptQuantity()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Quantity',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptTaxInclusivePrice()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'TaxInclusivePrice',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptTaxExclusivePrice()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'TaxExclusivePrice',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptTaxRate()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'TaxRate',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptTaxAmount()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'TaxAmount',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptContactPerson()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'ContactPerson',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptWriteOffAmount()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'WriteOffAmount',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptUnsettledAmount()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'UnsettledAmount',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptFeeRemark()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'FeeRemark',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptContractStatus()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'ContractStatus',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptCustomPosition1()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CustomPosition1',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptCustomPosition2()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CustomPosition2',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptEtd()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Etd',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptEta()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Eta',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptCarrier()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Carrier',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptPickupDeliveryLocation()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'PickupDeliveryLocation',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptTruckPickupTime()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'TruckPickupTime',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptBusinessStatus()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BusinessStatus',
        sorter: true,
        align: 'left',
    },
    {
        title: '操作',
        key: 'operation',
        fixed: 'right',
        width: 40,
        render: (_, record) => (
        <>
            <a onClick={()=>handleEdit(record)}>详细</a>
        </>
        ),
    },
]; 

export const getSmallColumns = (handleEdit: (record: InvoiceIssuanceReceiptItemProps) => void, handleDelete: (record: InvoiceIssuanceReceiptItemProps) => void): TableColumnsType<InvoiceIssuanceReceiptItemProps> => [

    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptBusinessId()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BusinessId',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptInvoiceTitle()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'InvoiceTitle',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptCustomer()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Customer',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptBusinessType()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BusinessType',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptBusinessDate()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BusinessDate',
        sorter: true,
        align: 'center',
    },
    
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptSales()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Sales',
        sorter: true,
        align: 'left',
    },
    
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptOperator()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Operator',
        sorter: true,
        align: 'left',
    },
    
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptFeeName()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'FeeName',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptCurrency()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Currency',
        sorter: true,
        align: 'left',
    },
    
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptQuantity()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Quantity',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptTaxInclusivePrice()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'TaxInclusivePrice',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptTaxExclusivePrice()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'TaxExclusivePrice',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptTaxRate()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'TaxRate',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptTaxAmount()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'TaxAmount',
        sorter: true,
        align: 'right',
    },
    
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptWriteOffAmount()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'WriteOffAmount',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptUnsettledAmount()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'UnsettledAmount',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getInvoiceIssuanceReceiptFeeRemark()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'FeeRemark',
        sorter: true,
        align: 'left',
    },
]; 
