
import Mock from "mockjs";
import { FeeReconciliationItemProps } from "@/types/fee_reconciliation/fee_reconciliation";
import { ReconciliationRuleEngineItemProps,ReconciliationCompareFieldsItemProps,ReconciliationMatchFieldsItemProps } from "@/types/fee_reconciliation/reconciliation_rule_engine";
import request, { ApiRes, requestWithProgress } from '../request';
// 模拟费用对账台账数据
const feeReconciliationItems: FeeReconciliationItemProps[] = [
  {
    "ShippingCompany": "高丽海运株式会社",
    "PricingNature": "自有约价",
    "ActualPortEntryDate": "2020-07-23 13:11",
    "BusinessModel": "整箱",
    "BusinessNumber": "AFS2007004",
    "WarehouseEntryNumber": "AFS2007004",
    "BookingNumber": "",
    "CutoffDate": "2020-08-03",
    "ProjectNumber": "",
    "Sono": "KMTCSHAF703978,KMTCSHAF703978A",
    "ContainerNumber": ",FFAU1030131",
    "OverseasCustomerService": "",
    "SiteOperation": "",
    "PaymentApplicationNumber": "",
    "Eta": "",
    "Etd": "2020-08-07",
    "Atd": "",
    "Ata": "",
    "ExchangeRate": 1,
    "BillNumber": "SH20080001D",
    "SettlementObject": "上海大洋行有限公司",
    "CargoType": "自揽货",
    "MasterWaybillNumber": "KMTCSHAF703978",
    "HouseWaybillNumber": "AFS2007004",
    "Consignor": "上海大洋行有限公司",
    "BusinessType": "海运出口",
    "BusinessDate": "2020-08-07",
    "IsFba": "否",
    "AmazonWarehouseCode": "",
    "DestinationDeliveryMethod": "",
    "CourierNumber": "",
    "IsRemoteWarehouse": "否",
    "ShipNameAndVoyage": "KMTC QINGDAO V.2008S",
    "PortOfLoading": "SHANGHAI",
    "PortOfDestination": "LOS ANGELES,CA",
    "BookingAgent": "上海麟泽国际物流有限公司",
    "OriginStation": "",
    "DestinationStation": "",
    "TransitStation": "",
    "DestinationAgent": "COMM FORWARDING COMPANY",
    "SalesPerson": "刘风彩",
    "OperationPerson": "刘风彩",
    "CustomerServicePerson": "",
    "DocumentPerson": "",
    "BusinessReferenceNumber": "",
    "AccrualAmount": 0,
    "FinancialDate": "",
    "DomesticOrForeign": "国内",
    "RevenueOrExpenditureType": "应收",
    "FeeStatus": "未提交",
    "Auditor": "",
    "ConfirmationStatus": "1",
    "FeeName": "装箱费",
    "Unit": "普通价",
    "Currency": "RMB",
    "Quantity": 1,
    "UnitPrice": 1200,
    "TaxInclusivePrice": 1200,
    "TaxExclusivePrice": 1200,
    "TaxAmount": 0,
    "TaxRate": 0,
    "WriteOffAmount": 1200,
    "UnwrittenAmount": 0,
    "ContactPerson": "",
    "Creator": "徐伟力",
    "Remark": "",
    "RelatedNumber": "",
    "ConsignmentRelatedNumber": "",
    "Carrier": "高丽海运株式会社",
    "ConfirmationDate": "2020-08-10",
    "FeeConfirmationPerson": "徐伟力",
    "RouteManager": "",
    "InvoiceDate": "2020-09-11",
    "InvoiceNumber": "",
    "InvoiceTitle": "上海大洋行有限公司",
    "IsInvoiceRequired": "是",
    "WriteOffDate": "2020-08-21",
    "BusinessStatus": "正操作",
    "BargeSailingDate": "",
    "BargeName": "",
    "BargeVoyage": "",
    "BargePortOfLoading": "",
    "PaymentDate": "2020-08-21",
    "SalesDepartment": "管理部",
    "DeliveryTime": "",
    "ConfirmationRemark": "",
    "FeeWriteOffStatus": "全部核销",
    "OperationDate": "",
    "EstimatedLoadingDate": "2020/08/05 00:00,2020/08/05 00:00",
    "ActualReturnEmptyTime": "",
    "ContainerQuantityDescription": "1*40HC,1*20GP",
    "FeeCreationDate": "2020-08-05 12:50:44",
    "CustomerLevel": "VIP客户",
    "DeliveryCompletionTime": "",
    "FeeChanger": "",
    "SettlementAgent": "",
    "IsFeeAdjusted": "否",
    "Route": "美西",
    "FeeModificationTime": "2025-02-21",
    "FeeModifier": "周文轩",
    "BillDate": "2020-08-10",
    "InvoiceDueDate": "",
    "CounterpartyInvoiceNumber": "",
    "ReceivableWriteOffStatus": "部分核销",
    "DesignatedForwarder": "",
    "ActualLoadingDate": "",
    "CounterpartyCounterNumber": "",
    "FeeDueDate": "",
    "RelatedFeeId": "",
    "FeeId": "311",
    "DataSource": "操作",
    "FeeContainerNumber": "",
    "PickupDeliveryLocation": "SHANGHAI",
    "ActualPickupTime": "",
    "WriteOffBank": "",
    "ParentCompany": "",
    "SettlementDepartment": "",
    "CargoSales": "",
    "SalesBranch": "",
    "OperationBranch": "",
    "FeeSyncStatus": "CARGOWARE基础版试用",
    "ExchangeAgent": "",
    "ReconciliationAmount": 1200,
    "Difference": "",
    "IsConfirmed": "1",
    "SettlementObjectTerm": "30天",
    "SettlementMethod": "按月结算",
    "AuditDate": "",
    "GpDescription": "",
    "ChargeableWeightActual": 1,
    "ChargeableWeightCommission": 0,
    "NumberOfPiecesActual": 4,
    "NumberOfPiecesCommission": 100,
    "VolumeActual": 0.879,
    "VolumeCommission": 23,
    "GrossWeightCommission": 2000,
    "GrossWeightActual": 518
  },
  {
    "ShippingCompany": "高丽海运株式会社",
    "PricingNature": "自有约价",
    "ActualPortEntryDate": "2020-07-23 13:11",
    "BusinessModel": "整箱",
    "BusinessNumber": "AFS2007004",
    "WarehouseEntryNumber": "AFS2007004",
    "BookingNumber": "",
    "CutoffDate": "2020-08-03",
    "ProjectNumber": "",
    "Sono": "KMTCSHAF703978,KMTCSHAF703978A",
    "ContainerNumber": ",FFAU1030131",
    "OverseasCustomerService": "",
    "SiteOperation": "",
    "PaymentApplicationNumber": "",
    "Eta": "",
    "Etd": "2020-08-07",
    "Atd": "",
    "Ata": "",
    "ExchangeRate": 7.15,
    "BillNumber": "SH20080001D",
    "SettlementObject": "上海大洋行有限公司",
    "CargoType": "自揽货",
    "MasterWaybillNumber": "KMTCSHAF703978",
    "HouseWaybillNumber": "AFS2007004",
    "Consignor": "上海大洋行有限公司",
    "BusinessType": "海运出口",
    "BusinessDate": "2020-08-07",
    "IsFba": "否",
    "AmazonWarehouseCode": "",
    "DestinationDeliveryMethod": "",
    "CourierNumber": "",
    "IsRemoteWarehouse": "否",
    "ShipNameAndVoyage": "KMTC QINGDAO V.2008S",
    "PortOfLoading": "SHANGHAI",
    "PortOfDestination": "LOS ANGELES,CA",
    "BookingAgent": "上海麟泽国际物流有限公司",
    "OriginStation": "",
    "DestinationStation": "",
    "TransitStation": "",
    "DestinationAgent": "COMM FORWARDING COMPANY",
    "SalesPerson": "刘风彩",
    "OperationPerson": "刘风彩",
    "CustomerServicePerson": "",
    "DocumentPerson": "",
    "BusinessReferenceNumber": "",
    "AccrualAmount": 0,
    "FinancialDate": "",
    "DomesticOrForeign": "国内",
    "RevenueOrExpenditureType": "应收",
    "FeeStatus": "未提交",
    "Auditor": "",
    "ConfirmationStatus": "1",
    "FeeName": "拖车费",
    "Unit": "普通价",
    "Currency": "USD",
    "Quantity": 1,
    "UnitPrice": 3000,
    "TaxInclusivePrice": 3000,
    "TaxExclusivePrice": 3000,
    "TaxAmount": 0,
    "TaxRate": 0,
    "WriteOffAmount": 3000,
    "UnwrittenAmount": 0,
    "ContactPerson": "",
    "Creator": "徐伟力",
    "Remark": "",
    "RelatedNumber": "",
    "ConsignmentRelatedNumber": "",
    "Carrier": "高丽海运株式会社",
    "ConfirmationDate": "2020-08-10",
    "FeeConfirmationPerson": "徐伟力",
    "RouteManager": "",
    "InvoiceDate": "2020-09-11",
    "InvoiceNumber": "",
    "InvoiceTitle": "上海大洋行有限公司",
    "IsInvoiceRequired": "是",
    "WriteOffDate": "2020-08-21",
    "BusinessStatus": "正操作",
    "BargeSailingDate": "",
    "BargeName": "",
    "BargeVoyage": "",
    "BargePortOfLoading": "",
    "PaymentDate": "2020-08-21",
    "SalesDepartment": "管理部",
    "DeliveryTime": "",
    "ConfirmationRemark": "",
    "FeeWriteOffStatus": "全部核销",
    "OperationDate": "",
    "EstimatedLoadingDate": "2020/08/05 00:00,2020/08/05 00:00",
    "ActualReturnEmptyTime": "",
    "ContainerQuantityDescription": "1*40HC,1*20GP",
    "FeeCreationDate": "2020-08-05 12:50:44",
    "CustomerLevel": "VIP客户",
    "DeliveryCompletionTime": "",
    "FeeChanger": "",
    "SettlementAgent": "",
    "IsFeeAdjusted": "否",
    "Route": "美西",
    "FeeModificationTime": "2025-02-21",
    "FeeModifier": "周文轩",
    "BillDate": "2020-08-10",
    "InvoiceDueDate": "",
    "CounterpartyInvoiceNumber": "",
    "ReceivableWriteOffStatus": "部分核销",
    "DesignatedForwarder": "",
    "ActualLoadingDate": "",
    "CounterpartyCounterNumber": "",
    "FeeDueDate": "",
    "RelatedFeeId": "",
    "FeeId": "309",
    "DataSource": "操作",
    "FeeContainerNumber": "",
    "PickupDeliveryLocation": "SHANGHAI",
    "ActualPickupTime": "",
    "WriteOffBank": "",
    "ParentCompany": "",
    "SettlementDepartment": "",
    "CargoSales": "",
    "SalesBranch": "",
    "OperationBranch": "",
    "FeeSyncStatus": "CARGOWARE基础版试用",
    "ExchangeAgent": "",
    "ReconciliationAmount": 3000,
    "Difference": "",
    "IsConfirmed": "1",
    "SettlementObjectTerm": "30天",
    "SettlementMethod": "按月结算",
    "AuditDate": "",
    "GpDescription": "",
    "ChargeableWeightActual": 1,
    "ChargeableWeightCommission": 0,
    "NumberOfPiecesActual": 4,
    "NumberOfPiecesCommission": 100,
    "VolumeActual": 0.879,
    "VolumeCommission": 23,
    "GrossWeightCommission": 2000,
    "GrossWeightActual": 518
  },
  {
    "ShippingCompany": "高丽海运株式会社",
    "PricingNature": "自有约价",
    "ActualPortEntryDate": "2020-07-23 13:11",
    "BusinessModel": "整箱",
    "BusinessNumber": "AFS2007004",
    "WarehouseEntryNumber": "AFS2007004",
    "BookingNumber": "",
    "CutoffDate": "2020-08-03",
    "ProjectNumber": "",
    "Sono": "KMTCSHAF703978,KMTCSHAF703978A",
    "ContainerNumber": ",FFAU1030131",
    "OverseasCustomerService": "",
    "SiteOperation": "",
    "PaymentApplicationNumber": "",
    "Eta": "",
    "Etd": "2020-08-07",
    "Atd": "",
    "Ata": "",
    "ExchangeRate": 1,
    "BillNumber": "SH20080001D",
    "SettlementObject": "上海大洋行有限公司",
    "CargoType": "自揽货",
    "MasterWaybillNumber": "KMTCSHAF703978",
    "HouseWaybillNumber": "AFS2007004",
    "Consignor": "上海大洋行有限公司",
    "BusinessType": "海运出口",
    "BusinessDate": "2020-08-07",
    "IsFba": "否",
    "AmazonWarehouseCode": "",
    "DestinationDeliveryMethod": "",
    "CourierNumber": "",
    "IsRemoteWarehouse": "否",
    "ShipNameAndVoyage": "KMTC QINGDAO V.2008S",
    "PortOfLoading": "SHANGHAI",
    "PortOfDestination": "LOS ANGELES,CA",
    "BookingAgent": "上海麟泽国际物流有限公司",
    "OriginStation": "",
    "DestinationStation": "",
    "TransitStation": "",
    "DestinationAgent": "COMM FORWARDING COMPANY",
    "SalesPerson": "刘风彩",
    "OperationPerson": "刘风彩",
    "CustomerServicePerson": "",
    "DocumentPerson": "",
    "BusinessReferenceNumber": "",
    "AccrualAmount": 0,
    "FinancialDate": "",
    "DomesticOrForeign": "国内",
    "RevenueOrExpenditureType": "应收",
    "FeeStatus": "未提交",
    "Auditor": "",
    "ConfirmationStatus": "1",
    "FeeName": "拖车费",
    "Unit": "普通价",
    "Currency": "RMB",
    "Quantity": 1,
    "UnitPrice": 1200,
    "TaxInclusivePrice": 1200,
    "TaxExclusivePrice": 1200,
    "TaxAmount": 0,
    "TaxRate": 0,
    "WriteOffAmount": 1200,
    "UnwrittenAmount": 0,
    "ContactPerson": "",
    "Creator": "徐伟力",
    "Remark": "",
    "RelatedNumber": "",
    "ConsignmentRelatedNumber": "",
    "Carrier": "高丽海运株式会社",
    "ConfirmationDate": "2020-08-10",
    "FeeConfirmationPerson": "徐伟力",
    "RouteManager": "",
    "InvoiceDate": "2020-09-11",
    "InvoiceNumber": "",
    "InvoiceTitle": "上海大洋行有限公司",
    "IsInvoiceRequired": "是",
    "WriteOffDate": "2020-08-21",
    "BusinessStatus": "正操作",
    "BargeSailingDate": "",
    "BargeName": "",
    "BargeVoyage": "",
    "BargePortOfLoading": "",
    "PaymentDate": "2020-08-21",
    "SalesDepartment": "管理部",
    "DeliveryTime": "",
    "ConfirmationRemark": "",
    "FeeWriteOffStatus": "全部核销",
    "OperationDate": "",
    "EstimatedLoadingDate": "2020/08/05 00:00,2020/08/05 00:00",
    "ActualReturnEmptyTime": "",
    "ContainerQuantityDescription": "1*40HC,1*20GP",
    "FeeCreationDate": "2020-08-05 12:50:44",
    "CustomerLevel": "VIP客户",
    "DeliveryCompletionTime": "",
    "FeeChanger": "",
    "SettlementAgent": "",
    "IsFeeAdjusted": "否",
    "Route": "美西",
    "FeeModificationTime": "2025-02-21",
    "FeeModifier": "周文轩",
    "BillDate": "2020-08-10",
    "InvoiceDueDate": "",
    "CounterpartyInvoiceNumber": "",
    "ReceivableWriteOffStatus": "部分核销",
    "DesignatedForwarder": "",
    "ActualLoadingDate": "",
    "CounterpartyCounterNumber": "",
    "FeeDueDate": "",
    "RelatedFeeId": "",
    "FeeId": "310",
    "DataSource": "操作",
    "FeeContainerNumber": "",
    "PickupDeliveryLocation": "SHANGHAI",
    "ActualPickupTime": "",
    "WriteOffBank": "",
    "ParentCompany": "",
    "SettlementDepartment": "",
    "CargoSales": "",
    "SalesBranch": "",
    "OperationBranch": "",
    "FeeSyncStatus": "CARGOWARE基础版试用",
    "ExchangeAgent": "",
    "ReconciliationAmount": 1200,
    "Difference": "",
    "IsConfirmed": "1",
    "SettlementObjectTerm": "30天",
    "SettlementMethod": "按月结算",
    "AuditDate": "",
    "GpDescription": "",
    "ChargeableWeightActual": 1,
    "ChargeableWeightCommission": 0,
    "NumberOfPiecesActual": 4,
    "NumberOfPiecesCommission": 100,
    "VolumeActual": 0.879,
    "VolumeCommission": 23,
    "GrossWeightCommission": 2000,
    "GrossWeightActual": 518
  },
];

const reconciliationRuleEngineItems: ReconciliationRuleEngineItemProps[] = [
  {
    RowKey: Mock.mock("@id"),
    CompanyName: '公司A',
    ReconciliationRuleName: '初始多行汇总对账规则',
  },
  {
    RowKey: Mock.mock("@id"),
    CompanyName: '公司B',
    ReconciliationRuleName: '初始单行明细对账规则',
  },
];

const reconciliationMatchItems: ReconciliationMatchFieldsItemProps[] = [
  {
    RowKey: Mock.mock("@id"),
    MatchFieldsName: 'MBL NO.',
    MatchFieldRelation: '与',
    MatchFieldOrderBy: '1',
  },
  {
    RowKey: Mock.mock("@id"),
    MatchFieldsName: '费用名称',
    MatchFieldRelation: '与',
    MatchFieldOrderBy: '2',
  },
];

const reconciliationCompareItems: ReconciliationCompareFieldsItemProps[] = [
  {
    RowKey: Mock.mock("@id"),
    CompareFieldsName: '金额',
    CompareFieldRelation: '与',
    CompareFieldOrderBy: '1',
    CompareFieldOperator: '多行汇总方式',
  },
  {
    RowKey: Mock.mock("@id"),
    CompareFieldsName: '单价',
    CompareFieldRelation: '与',
    CompareFieldOrderBy: '2',
    CompareFieldOperator: '单行明细对比',
  },
];

// 获取费用对账台账列表
export const getFeeReconciliationList = async (): Promise<FeeReconciliationItemProps[]> => {
  return feeReconciliationItems;
}

export const getReconciliationRuleEngineList = async (): Promise<ReconciliationRuleEngineItemProps[]> => {
  return reconciliationRuleEngineItems;
}

export const getMatchFieldsList = async (): Promise<ReconciliationMatchFieldsItemProps[]> => {
  return reconciliationMatchItems;
}

export const getCompareFieldsList = async (): Promise<ReconciliationCompareFieldsItemProps[]> => {
  return reconciliationCompareItems;
}

// 保存费用对账台账
export const saveFeeReconciliation = async (data: FeeReconciliationItemProps, onUploadProgress?: (progress: number) => void): Promise<FeeReconciliationItemProps> => {
  // 模拟上传进度
  if (onUploadProgress) {
    let progress = 0;
    const interval = setInterval(() => {
      progress += 10;
      onUploadProgress(progress);
      if (progress >= 100) {
        clearInterval(interval);
      }
    }, 1000);
  }
  return data;
}

// 原有API接口代码（已注释）
/*
// 获取费用对账台账列表
export const getFeeReconciliationList = async () : Promise<FeeReconciliationItemProps[]> => {
  const response = await request({
    method: "GET",
    url: "/fee_reconciliation"
  });
  const responseData = response?.data as ApiRes<FeeReconciliationItemProps[]>;
  return responseData.data || [];
}

// 保存费用对账台账
export const saveFeeReconciliation = (data:FeeReconciliationItemProps, onUploadProgress: (progress: number) => void) => {
  return requestWithProgress({
    method: 'POST',
    url: "/fee_reconciliation/save",
    data:data,
    onUploadProgress: (progress) => {
        onUploadProgress(progress);
    }
  })
}
*/

