
import { PaymentApplicationFeeItemProps } from '@/types/cost_manage/payment_application_fee';
import request, {ApiRes,requestWithProgress } from '../request'
import { PaymentApplicationItemProps } from "@/types/cost_manage/payment_application";
import { PaymentApplicationBusinessItemProps } from '@/types/cost_manage/payment_application_business';

const paymentApplicationItems: PaymentApplicationItemProps[] = [
  {
    "PaymentNotificationNumber": "FK25020001",
    "SettlementObject": "上海四海仓库",
    "SettlementAgent": "",
    "EntrustingUnit": "上海大洋行有限公司",
    "ModificationTime": "2025-02-21T16:28:20",
    "Modifier": "周文轩",
    "InvoiceTitle": "上海四海仓库",
    "BusinessNumber": "AFS2007004",
    "ApplicationDate": "2025-02-21",
    "Applicant": "周文轩",
    "ApplicantDepartment": "管理部",
    "PaymentDeadline": "2025-02-28",
    "PaymentMethod": "银行转账",
    "InvoiceNumber": "1111.0",
    "CurrencyCode": "RMB",
    "Amount": 800.0,
    "ReconciliationAmountByCurrency": "RMB:800.00",
    "ApprovalStatus": "已财务审批",
    "ReconciliationStatus": "全部核销",
    "Remarks": "",
    "ProcessNumber": "",
    "TotalByCurrency": "RMB:800.00",
    "VoucherNumber": "",
    "VoucherCreationDate": "",
    "Carrier": "高丽海运株式会社",
    "ShippingLocation": "SHANGHAI",
    "ActualTrailerPickupTime": "",
    "DocumentDate": "",
    "FinancialPayableStatus": ""
  },
  {
    "PaymentNotificationNumber": "FK20050001",
    "SettlementObject": "长锦商船船务有限公司",
    "SettlementAgent": "",
    "EntrustingUnit": "苏州永翔五金塑胶有限公司",
    "ModificationTime": "2020-05-20T15:15:36",
    "Modifier": "周文轩",
    "InvoiceTitle": "长锦商船船务有限公司",
    "BusinessNumber": "SHSE20040001A",
    "ApplicationDate": "2020-05-20",
    "Applicant": "周文轩",
    "ApplicantDepartment": "管理部",
    "PaymentDeadline": "2020-05-20",
    "PaymentMethod": "银行转账",
    "InvoiceNumber": "9.0",
    "CurrencyCode": "USD",
    "Amount": 15.37,
    "ReconciliationAmountByCurrency": "USD:0.00",
    "ApprovalStatus": "已业务审批",
    "ReconciliationStatus": "未核销",
    "Remarks": "",
    "ProcessNumber": "",
    "TotalByCurrency": "USD:15.37",
    "VoucherNumber": "",
    "VoucherCreationDate": "",
    "Carrier": "长锦商船船务有限公司",
    "ShippingLocation": "SHANGHAI",
    "ActualTrailerPickupTime": "",
    "DocumentDate": "",
    "FinancialPayableStatus": ""
  },
  {
    "PaymentNotificationNumber": "FK20030001",
    "SettlementObject": "新西兰航空公司",
    "SettlementAgent": "",
    "EntrustingUnit": "上海苍鹭实业有限公司",
    "ModificationTime": "2020-03-12T14:43:34",
    "Modifier": "肖宝珠",
    "InvoiceTitle": "长锦商船船务有限公司",
    "BusinessNumber": "SHSE20020015",
    "ApplicationDate": "2020-03-12",
    "Applicant": "肖宝珠",
    "ApplicantDepartment": "管理部",
    "PaymentDeadline": "2020-03-19",
    "PaymentMethod": "银行转账",
    "InvoiceNumber": "9.0",
    "CurrencyCode": "RMB",
    "Amount": 2000.0,
    "ReconciliationAmountByCurrency": "RMB:0.00",
    "ApprovalStatus": "已提交",
    "ReconciliationStatus": "未核销",
    "Remarks": "",
    "ProcessNumber": "",
    "TotalByCurrency": "RMB:2000.00",
    "VoucherNumber": "",
    "VoucherCreationDate": "",
    "Carrier": "上海市锦江航运有限公司",
    "ShippingLocation": "SHANGHAI",
    "ActualTrailerPickupTime": "",
    "DocumentDate": "",
    "FinancialPayableStatus": ""
  },
  {
    "PaymentNotificationNumber": "FK20020002",
    "SettlementObject": "澳大利亚航空公司",
    "SettlementAgent": "",
    "EntrustingUnit": "上海沃行信息技术有限公司",
    "ModificationTime": "2020-02-19T21:00:53",
    "Modifier": "王乾",
    "InvoiceTitle": "长锦商船船务有限公司",
    "BusinessNumber": "SHSE20020002",
    "ApplicationDate": "2020-02-19",
    "Applicant": "王乾",
    "ApplicantDepartment": "管理部",
    "PaymentDeadline": "2020-02-28",
    "PaymentMethod": "银行转账",
    "InvoiceNumber": "9.0",
    "CurrencyCode": "RMB",
    "Amount": 2000.0,
    "ReconciliationAmountByCurrency": "RMB:0.00",
    "ApprovalStatus": "已财务审批",
    "ReconciliationStatus": "未核销",
    "Remarks": "",
    "ProcessNumber": "",
    "TotalByCurrency": "RMB:2000.00",
    "VoucherNumber": "",
    "VoucherCreationDate": "",
    "Carrier": "上海市锦江航运有限公司",
    "ShippingLocation": "SHANGHAI",
    "ActualTrailerPickupTime": "",
    "DocumentDate": "",
    "FinancialPayableStatus": ""
  },
  {
    "PaymentNotificationNumber": "FK20020001",
    "SettlementObject": "新西兰航空公司",
    "SettlementAgent": "",
    "EntrustingUnit": "上海沃行信息技术有限公司",
    "ModificationTime": "2020-02-12T19:21:29",
    "Modifier": "张雷",
    "InvoiceTitle": "长锦商船船务有限公司",
    "BusinessNumber": "SHSE20020002",
    "ApplicationDate": "2020-02-12",
    "Applicant": "张雷",
    "ApplicantDepartment": "管理部",
    "PaymentDeadline": "2020-02-28",
    "PaymentMethod": "银行转账",
    "InvoiceNumber": "9.0",
    "CurrencyCode": "RMB",
    "Amount": 5000.0,
    "ReconciliationAmountByCurrency": "RMB:0.00",
    "ApprovalStatus": "已提交",
    "ReconciliationStatus": "未核销",
    "Remarks": "",
    "ProcessNumber": "",
    "TotalByCurrency": "RMB:5000",
    "VoucherNumber": "",
    "VoucherCreationDate": "",
    "Carrier": "上海市锦江航运有限公司",
    "ShippingLocation": "SHANGHAI",
    "ActualTrailerPickupTime": "",
    "DocumentDate": "",
    "FinancialPayableStatus": ""
  }
];

const paymentApplicationFeeItems: PaymentApplicationFeeItemProps[] = [
  {
    "BusinessNumber": "SE2011005",
    "InWarehouseNumber": "SE2011005",
    "BookingNumber": "",
    "CutOffDate": "2020-11-25",
    "ProjectNumber": "",
    "Sono": "",
    "ContainerNumber": "",
    "OverseasCustomerService": "",
    "PaymentApplicationNumber": "",
    "BillNumber": "",
    "SettlementObject": "德翔航运（上海德圣船务有限公司）",
    "ConsignmentType": "自揽货",
    "MasterWaybillNumber": "SHCR0W809700",
    "SubWaybillNumber": "SE2011005",
    "Consignor": "上海合金",
    "BusinessType": "海运出口",
    "BusinessDate": "2020-12-01",
    "VesselVoyage": "SM MUMBAI 2008E",
    "PortOfLoading": "SHANGHAI",
    "PortOfDestination": "TORONTO",
    "PlaceOfDeparture": "",
    "PlaceOfDestination": "",
    "TransitPort": "",
    "DestinationAgent": "",
    "Sales": "邵阳",
    "Operation": "黄琪",
    "CustomerService": "",
    "Document": "",
    "BusinessReferenceNumber": "",
    "DomesticOrForeign": "国内",
    "RevenueOrExpenditureType": "应付",
    "FeeStatus": "未提交",
    "Reviewer": "",
    "ConfirmationStatus": "未确认",
    "FeeName": "海运费",
    "Unit": "CNTR",
    "Currency": "USD",
    "Quantity": 1,
    "UnitPrice": 12,
    "TaxInclusivePrice": 12,
    "TaxExclusivePrice": 12,
    "TaxAmount": 0,
    "TaxRate": 0,
    "BusinessStatus": "正操作"
  },
  {
    "BusinessNumber": "SE2011004",
    "InWarehouseNumber": "SE2011004",
    "BookingNumber": "",
    "CutOffDate": "2020-11-25",
    "ProjectNumber": "",
    "Sono": "",
    "ContainerNumber": "",
    "OverseasCustomerService": "",
    "PaymentApplicationNumber": "",
    "BillNumber": "",
    "SettlementObject": "德翔航运（上海德圣船务有限公司）",
    "ConsignmentType": "自揽货",
    "MasterWaybillNumber": "SHCR0W808600",
    "SubWaybillNumber": "SE2011004",
    "Consignor": "上海合金",
    "BusinessType": "海运出口",
    "BusinessDate": "2020-12-01",
    "VesselVoyage": "SM MUMBAI 2008E",
    "PortOfLoading": "SHANGHAI",
    "PortOfDestination": "TORONTO",
    "PlaceOfDeparture": "",
    "PlaceOfDestination": "",
    "TransitPort": "",
    "DestinationAgent": "",
    "Sales": "邵阳",
    "Operation": "黄琪",
    "CustomerService": "",
    "Document": "",
    "BusinessReferenceNumber": "",
    "DomesticOrForeign": "国内",
    "RevenueOrExpenditureType": "应付",
    "FeeStatus": "未提交",
    "Reviewer": "",
    "ConfirmationStatus": "未确认",
    "FeeName": "海运费",
    "Unit": "CNTR",
    "Currency": "USD",
    "Quantity": 1,
    "UnitPrice": 11,
    "TaxInclusivePrice": 11,
    "TaxExclusivePrice": 11,
    "TaxAmount": 0,
    "TaxRate": 0,
    "BusinessStatus": "正操作"
  },
  {
    "BusinessNumber": "SE2011010",
    "InWarehouseNumber": "SE2011010",
    "BookingNumber": "",
    "CutOffDate": "2020-11-25",
    "ProjectNumber": "",
    "Sono": "",
    "ContainerNumber": "",
    "OverseasCustomerService": "",
    "PaymentApplicationNumber": "",
    "BillNumber": "",
    "SettlementObject": "澳大利亚航空公司",
    "ConsignmentType": "自揽货",
    "MasterWaybillNumber": "SHCR0W797600",
    "SubWaybillNumber": "SE2011010",
    "Consignor": "上海合金",
    "BusinessType": "海运出口",
    "BusinessDate": "2020-12-01",
    "VesselVoyage": "SM MUMBAI 2008E",
    "PortOfLoading": "SHANGHAI",
    "PortOfDestination": "TORONTO",
    "PlaceOfDeparture": "",
    "PlaceOfDestination": "",
    "TransitPort": "",
    "DestinationAgent": "",
    "Sales": "邵阳",
    "Operation": "黄琪",
    "CustomerService": "",
    "Document": "",
    "BusinessReferenceNumber": "",
    "DomesticOrForeign": "国内",
    "RevenueOrExpenditureType": "应付",
    "FeeStatus": "未提交",
    "Reviewer": "",
    "ConfirmationStatus": "未确认",
    "FeeName": "报关单打印费",
    "Unit": "NML",
    "Currency": "RMB",
    "Quantity": 1,
    "UnitPrice": 21,
    "TaxInclusivePrice": 21,
    "TaxExclusivePrice": 21,
    "TaxAmount": 0,
    "TaxRate": 0,
    "BusinessStatus": "正操作"
  },
  {
    "BusinessNumber": "SE2011011",
    "InWarehouseNumber": "SE2011011",
    "BookingNumber": "ASHAYIN200595345",
    "CutOffDate": "2020-11-25",
    "ProjectNumber": "",
    "Sono": "",
    "ContainerNumber": "",
    "OverseasCustomerService": "",
    "PaymentApplicationNumber": "",
    "BillNumber": "",
    "SettlementObject": "德翔航运（上海德圣船务有限公司）",
    "ConsignmentType": "自揽货",
    "MasterWaybillNumber": "SHCR0W797600",
    "SubWaybillNumber": "SE2011011",
    "Consignor": "上海合金",
    "BusinessType": "海运出口",
    "BusinessDate": "2020-12-01",
    "VesselVoyage": "SM MUMBAI 2008E",
    "PortOfLoading": "SHANGHAI",
    "PortOfDestination": "TORONTO",
    "PlaceOfDeparture": "",
    "PlaceOfDestination": "",
    "TransitPort": "",
    "DestinationAgent": "",
    "Sales": "邵阳",
    "Operation": "黄琪",
    "CustomerService": "",
    "Document": "",
    "BusinessReferenceNumber": "1233.0",
    "DomesticOrForeign": "国内",
    "RevenueOrExpenditureType": "应付",
    "FeeStatus": "未提交",
    "Reviewer": "",
    "ConfirmationStatus": "未确认",
    "FeeName": "海运费",
    "Unit": "CNTR",
    "Currency": "USD",
    "Quantity": 1,
    "UnitPrice": 20,
    "TaxInclusivePrice": 20,
    "TaxExclusivePrice": 20,
    "TaxAmount": 0,
    "TaxRate": 0,
    "BusinessStatus": "正操作"
  },
  {
    "BusinessNumber": "SE2011007",
    "InWarehouseNumber": "SE2011007",
    "BookingNumber": "ASHAYIN200595345",
    "CutOffDate": "2020-11-25",
    "ProjectNumber": "",
    "Sono": "",
    "ContainerNumber": "",
    "OverseasCustomerService": "",
    "PaymentApplicationNumber": "",
    "BillNumber": "",
    "SettlementObject": "德翔航运（上海德圣船务有限公司）",
    "ConsignmentType": "自揽货",
    "MasterWaybillNumber": "ASHAYIN200624814",
    "SubWaybillNumber": "SE2011007",
    "Consignor": "上海合金",
    "BusinessType": "海运出口",
    "BusinessDate": "2020-12-01",
    "VesselVoyage": "SM MUMBAI 2008E",
    "PortOfLoading": "SHANGHAI",
    "PortOfDestination": "TORONTO",
    "PlaceOfDeparture": "",
    "PlaceOfDestination": "",
    "TransitPort": "",
    "DestinationAgent": "",
    "Sales": "邵阳",
    "Operation": "黄琪",
    "CustomerService": "",
    "Document": "",
    "BusinessReferenceNumber": "1233.0",
    "DomesticOrForeign": "国内",
    "RevenueOrExpenditureType": "应付",
    "FeeStatus": "未提交",
    "Reviewer": "",
    "ConfirmationStatus": "未确认",
    "FeeName": "海运费",
    "Unit": "CNTR",
    "Currency": "USD",
    "Quantity": 1,
    "UnitPrice": 20,
    "TaxInclusivePrice": 20,
    "TaxExclusivePrice": 20,
    "TaxAmount": 0,
    "TaxRate": 0,
    "BusinessStatus": "正操作"
  },
  {
    "BusinessNumber": "SE2011009",
    "InWarehouseNumber": "SE2011009",
    "BookingNumber": "ASHAYIN200595345",
    "CutOffDate": "2020-11-25",
    "ProjectNumber": "",
    "Sono": "",
    "ContainerNumber": "",
    "OverseasCustomerService": "",
    "PaymentApplicationNumber": "",
    "BillNumber": "",
    "SettlementObject": "德翔航运（上海德圣船务有限公司）",
    "ConsignmentType": "自揽货",
    "MasterWaybillNumber": "ASHAYIN200604654I",
    "SubWaybillNumber": "SE2011009",
    "Consignor": "上海合金",
    "BusinessType": "海运出口",
    "BusinessDate": "2020-12-01",
    "VesselVoyage": "SM MUMBAI 2008E",
    "PortOfLoading": "SHANGHAI",
    "PortOfDestination": "TORONTO",
    "PlaceOfDeparture": "",
    "PlaceOfDestination": "",
    "TransitPort": "",
    "DestinationAgent": "",
    "Sales": "邵阳",
    "Operation": "黄琪",
    "CustomerService": "",
    "Document": "",
    "BusinessReferenceNumber": "1233.0",
    "DomesticOrForeign": "国内",
    "RevenueOrExpenditureType": "应付",
    "FeeStatus": "未提交",
    "Reviewer": "",
    "ConfirmationStatus": "未确认",
    "FeeName": "海运费",
    "Unit": "CNTR",
    "Currency": "USD",
    "Quantity": 1,
    "UnitPrice": 20,
    "TaxInclusivePrice": 20,
    "TaxExclusivePrice": 20,
    "TaxAmount": 0,
    "TaxRate": 0,
    "BusinessStatus": "正操作"
  },
  {
    "BusinessNumber": "SE2011005",
    "InWarehouseNumber": "SE2011005",
    "BookingNumber": "ASHAYIN200595345",
    "CutOffDate": "2020-11-25",
    "ProjectNumber": "",
    "Sono": "",
    "ContainerNumber": "",
    "OverseasCustomerService": "",
    "PaymentApplicationNumber": "",
    "BillNumber": "",
    "SettlementObject": "澳大利亚航空公司",
    "ConsignmentType": "自揽货",
    "MasterWaybillNumber": "SHCR0W809700",
    "SubWaybillNumber": "SE2011005",
    "Consignor": "上海合金",
    "BusinessType": "海运出口",
    "BusinessDate": "2020-12-01",
    "VesselVoyage": "SM MUMBAI 2008E",
    "PortOfLoading": "SHANGHAI",
    "PortOfDestination": "TORONTO",
    "PlaceOfDeparture": "",
    "PlaceOfDestination": "",
    "TransitPort": "",
    "DestinationAgent": "",
    "Sales": "邵阳",
    "Operation": "黄琪",
    "CustomerService": "",
    "Document": "",
    "BusinessReferenceNumber": "1233.0",
    "DomesticOrForeign": "国内",
    "RevenueOrExpenditureType": "应付",
    "FeeStatus": "未提交",
    "Reviewer": "",
    "ConfirmationStatus": "未确认",
    "FeeName": "报关单打印费",
    "Unit": "NML",
    "Currency": "RMB",
    "Quantity": 1,
    "UnitPrice": 13,
    "TaxInclusivePrice": 13,
    "TaxExclusivePrice": 13,
    "TaxAmount": 0,
    "TaxRate": 0,
    "BusinessStatus": "正操作"
  },
  {
    "BusinessNumber": "SE2011006",
    "InWarehouseNumber": "SE2011006",
    "BookingNumber": "ASHAYIN200595345",
    "CutOffDate": "2020-11-25",
    "ProjectNumber": "",
    "Sono": "",
    "ContainerNumber": "",
    "OverseasCustomerService": "",
    "PaymentApplicationNumber": "",
    "BillNumber": "",
    "SettlementObject": "澳大利亚航空公司",
    "ConsignmentType": "自揽货",
    "MasterWaybillNumber": "SHCR0W810600",
    "SubWaybillNumber": "SE2011006",
    "Consignor": "上海合金",
    "BusinessType": "海运出口",
    "BusinessDate": "2020-12-01",
    "VesselVoyage": "SM MUMBAI 2008E",
    "PortOfLoading": "SHANGHAI",
    "PortOfDestination": "TORONTO",
    "PlaceOfDeparture": "",
    "PlaceOfDestination": "",
    "TransitPort": "",
    "DestinationAgent": "",
    "Sales": "邵阳",
    "Operation": "黄琪",
    "CustomerService": "",
    "Document": "",
    "BusinessReferenceNumber": "1233.0",
    "DomesticOrForeign": "国内",
    "RevenueOrExpenditureType": "应付",
    "FeeStatus": "未提交",
    "Reviewer": "",
    "ConfirmationStatus": "未确认",
    "FeeName": "报关单打印费",
    "Unit": "NML",
    "Currency": "RMB",
    "Quantity": 1,
    "UnitPrice": 15,
    "TaxInclusivePrice": 15,
    "TaxExclusivePrice": 15,
    "TaxAmount": 0,
    "TaxRate": 0,
    "BusinessStatus": "正操作"
  },
  {
    "BusinessNumber": "SE2011004",
    "InWarehouseNumber": "SE2011004",
    "BookingNumber": "ASHAYIN200595345",
    "CutOffDate": "2020-11-25",
    "ProjectNumber": "",
    "Sono": "",
    "ContainerNumber": "",
    "OverseasCustomerService": "",
    "PaymentApplicationNumber": "",
    "BillNumber": "",
    "SettlementObject": "澳大利亚航空公司",
    "ConsignmentType": "自揽货",
    "MasterWaybillNumber": "SHCR0W808600",
    "SubWaybillNumber": "SE2011004",
    "Consignor": "上海合金",
    "BusinessType": "海运出口",
    "BusinessDate": "2020-12-01",
    "VesselVoyage": "SM MUMBAI 2008E",
    "PortOfLoading": "SHANGHAI",
    "PortOfDestination": "TORONTO",
    "PlaceOfDeparture": "",
    "PlaceOfDestination": "",
    "TransitPort": "",
    "DestinationAgent": "",
    "Sales": "邵阳",
    "Operation": "黄琪",
    "CustomerService": "",
    "Document": "",
    "BusinessReferenceNumber": "1233.0",
    "DomesticOrForeign": "国内",
    "RevenueOrExpenditureType": "应付",
    "FeeStatus": "未提交",
    "Reviewer": "",
    "ConfirmationStatus": "未确认",
    "FeeName": "报关单打印费",
    "Unit": "NML",
    "Currency": "RMB",
    "Quantity": 1,
    "UnitPrice": 11,
    "TaxInclusivePrice": 11,
    "TaxExclusivePrice": 11,
    "TaxAmount": 0,
    "TaxRate": 0,
    "BusinessStatus": "正操作"
  },
  {
    "BusinessNumber": "SE2011002",
    "InWarehouseNumber": "SE2011002",
    "BookingNumber": "ASHAYIN200595345",
    "CutOffDate": "2020-11-25",
    "ProjectNumber": "",
    "Sono": "",
    "ContainerNumber": "",
    "OverseasCustomerService": "",
    "PaymentApplicationNumber": "",
    "BillNumber": "",
    "SettlementObject": "澳大利亚航空公司",
    "ConsignmentType": "自揽货",
    "MasterWaybillNumber": "SHFO0D657700",
    "SubWaybillNumber": "SE2011002",
    "Consignor": "上海合金",
    "BusinessType": "海运出口",
    "BusinessDate": "2020-12-01",
    "VesselVoyage": "SM MUMBAI 2008E",
    "PortOfLoading": "SHANGHAI",
    "PortOfDestination": "TORONTO",
    "PlaceOfDeparture": "",
    "PlaceOfDestination": "",
    "TransitPort": "",
    "DestinationAgent": "",
    "Sales": "邵阳",
    "Operation": "黄琪",
    "CustomerService": "",
    "Document": "",
    "BusinessReferenceNumber": "1233.0",
    "DomesticOrForeign": "国内",
    "RevenueOrExpenditureType": "应付",
    "FeeStatus": "未提交",
    "Reviewer": "",
    "ConfirmationStatus": "未确认",
    "FeeName": "报关单打印费",
    "Unit": "NML",
    "Currency": "RMB",
    "Quantity": 1,
    "UnitPrice": 11,
    "TaxInclusivePrice": 11,
    "TaxExclusivePrice": 11,
    "TaxAmount": 0,
    "TaxRate": 0,
    "BusinessStatus": "正操作"
  },
  {
    "BusinessNumber": "SE2011008",
    "InWarehouseNumber": "SE2011008",
    "BookingNumber": "ASHAYIN200595345",
    "CutOffDate": "2020-11-25",
    "ProjectNumber": "",
    "Sono": "",
    "ContainerNumber": "",
    "OverseasCustomerService": "",
    "PaymentApplicationNumber": "",
    "BillNumber": "",
    "SettlementObject": "澳大利亚航空公司",
    "ConsignmentType": "自揽货",
    "MasterWaybillNumber": "ASHAYIN200624814E",
    "SubWaybillNumber": "SE2011008",
    "Consignor": "上海合金",
    "BusinessType": "海运出口",
    "BusinessDate": "2020-12-01",
    "VesselVoyage": "SM MUMBAI 2008E",
    "PortOfLoading": "SHANGHAI",
    "PortOfDestination": "TORONTO",
    "PlaceOfDeparture": "",
    "PlaceOfDestination": "",
    "TransitPort": "",
    "DestinationAgent": "",
    "Sales": "邵阳",
    "Operation": "黄琪",
    "CustomerService": "",
    "Document": "",
    "BusinessReferenceNumber": "1233.0",
    "DomesticOrForeign": "国内",
    "RevenueOrExpenditureType": "应付",
    "FeeStatus": "未提交",
    "Reviewer": "",
    "ConfirmationStatus": "未确认",
    "FeeName": "报关单打印费",
    "Unit": "NML",
    "Currency": "RMB",
    "Quantity": 1,
    "UnitPrice": 21,
    "TaxInclusivePrice": 21,
    "TaxExclusivePrice": 21,
    "TaxAmount": 0,
    "TaxRate": 0,
    "BusinessStatus": "正操作"
  },
  {
    "BusinessNumber": "SE2011007",
    "InWarehouseNumber": "SE2011007",
    "BookingNumber": "ASHAYIN200595345",
    "CutOffDate": "2020-11-25",
    "ProjectNumber": "",
    "Sono": "",
    "ContainerNumber": "",
    "OverseasCustomerService": "",
    "PaymentApplicationNumber": "",
    "BillNumber": "",
    "SettlementObject": "澳大利亚航空公司",
    "ConsignmentType": "自揽货",
    "MasterWaybillNumber": "ASHAYIN200624814",
    "SubWaybillNumber": "SE2011007",
    "Consignor": "上海合金",
    "BusinessType": "海运出口",
    "BusinessDate": "2020-12-01",
    "VesselVoyage": "SM MUMBAI 2008E",
    "PortOfLoading": "SHANGHAI",
    "PortOfDestination": "TORONTO",
    "PlaceOfDeparture": "",
    "PlaceOfDestination": "",
    "TransitPort": "",
    "DestinationAgent": "",
    "Sales": "邵阳",
    "Operation": "黄琪",
    "CustomerService": "",
    "Document": "",
    "BusinessReferenceNumber": "1233.0",
    "DomesticOrForeign": "国内",
    "RevenueOrExpenditureType": "应付",
    "FeeStatus": "未提交",
    "Reviewer": "",
    "ConfirmationStatus": "未确认",
    "FeeName": "报关单打印费",
    "Unit": "NML",
    "Currency": "RMB",
    "Quantity": 1,
    "UnitPrice": 21,
    "TaxInclusivePrice": 21,
    "TaxExclusivePrice": 21,
    "TaxAmount": 0,
    "TaxRate": 0,
    "BusinessStatus": "正操作"
  },
  {
    "BusinessNumber": "SE2011003",
    "InWarehouseNumber": "SE2011003",
    "BookingNumber": "ASHAYIN200595345",
    "CutOffDate": "2020-11-25",
    "ProjectNumber": "",
    "Sono": "",
    "ContainerNumber": "",
    "OverseasCustomerService": "",
    "PaymentApplicationNumber": "",
    "BillNumber": "",
    "SettlementObject": "澳大利亚航空公司",
    "ConsignmentType": "自揽货",
    "MasterWaybillNumber": "SHFO0D658100",
    "SubWaybillNumber": "SE2011003",
    "Consignor": "上海合金",
    "BusinessType": "海运出口",
    "BusinessDate": "2020-12-01",
    "VesselVoyage": "SM MUMBAI 2008E",
    "PortOfLoading": "SHANGHAI",
    "PortOfDestination": "TORONTO",
    "PlaceOfDeparture": "",
    "PlaceOfDestination": "",
    "TransitPort": "",
    "DestinationAgent": "",
    "Sales": "邵阳",
    "Operation": "黄琪",
    "CustomerService": "",
    "Document": "",
    "BusinessReferenceNumber": "1233.0",
    "DomesticOrForeign": "国内",
    "RevenueOrExpenditureType": "应付",
    "FeeStatus": "未提交",
    "Reviewer": "",
    "ConfirmationStatus": "未确认",
    "FeeName": "报关单打印费",
    "Unit": "NML",
    "Currency": "RMB",
    "Quantity": 1,
    "UnitPrice": 11,
    "TaxInclusivePrice": 11,
    "TaxExclusivePrice": 11,
    "TaxAmount": 0,
    "TaxRate": 0,
    "BusinessStatus": "正操作"
  },
  {
    "BusinessNumber": "SE2011006",
    "InWarehouseNumber": "SE2011006",
    "BookingNumber": "ASHAYIN200595345",
    "CutOffDate": "2020-11-25",
    "ProjectNumber": "",
    "Sono": "",
    "ContainerNumber": "",
    "OverseasCustomerService": "",
    "PaymentApplicationNumber": "",
    "BillNumber": "",
    "SettlementObject": "德翔航运（上海德圣船务有限公司）",
    "ConsignmentType": "自揽货",
    "MasterWaybillNumber": "SHCR0W810600",
    "SubWaybillNumber": "SE2011006",
    "Consignor": "上海合金",
    "BusinessType": "海运出口",
    "BusinessDate": "2020-12-01",
    "VesselVoyage": "SM MUMBAI 2008E",
    "PortOfLoading": "SHANGHAI",
    "PortOfDestination": "TORONTO",
    "PlaceOfDeparture": "",
    "PlaceOfDestination": "",
    "TransitPort": "",
    "DestinationAgent": "",
    "Sales": "邵阳",
    "Operation": "黄琪",
    "CustomerService": "",
    "Document": "",
    "BusinessReferenceNumber": "1233.0",
    "DomesticOrForeign": "国内",
    "RevenueOrExpenditureType": "应付",
    "FeeStatus": "未提交",
    "Reviewer": "",
    "ConfirmationStatus": "未确认",
    "FeeName": "海运费",
    "Unit": "CNTR",
    "Currency": "USD",
    "Quantity": 1,
    "UnitPrice": 14,
    "TaxInclusivePrice": 14,
    "TaxExclusivePrice": 14,
    "TaxAmount": 0,
    "TaxRate": 0,
    "BusinessStatus": "正操作"
  },
  {
    "BusinessNumber": "SE2011002",
    "InWarehouseNumber": "SE2011002",
    "BookingNumber": "ASHAYIN200595345",
    "CutOffDate": "2020-11-25",
    "ProjectNumber": "",
    "Sono": "",
    "ContainerNumber": "",
    "OverseasCustomerService": "",
    "PaymentApplicationNumber": "",
    "BillNumber": "",
    "SettlementObject": "德翔航运（上海德圣船务有限公司）",
    "ConsignmentType": "自揽货",
    "MasterWaybillNumber": "SHFO0D657700",
    "SubWaybillNumber": "SE2011002",
    "Consignor": "上海合金",
    "BusinessType": "海运出口",
    "BusinessDate": "2020-12-01",
    "VesselVoyage": "SM MUMBAI 2008E",
    "PortOfLoading": "SHANGHAI",
    "PortOfDestination": "TORONTO",
    "PlaceOfDeparture": "",
    "PlaceOfDestination": "",
    "TransitPort": "",
    "DestinationAgent": "",
    "Sales": "邵阳",
    "Operation": "黄琪",
    "CustomerService": "",
    "Document": "",
    "BusinessReferenceNumber": "1233.0",
    "DomesticOrForeign": "国内",
    "RevenueOrExpenditureType": "应付",
    "FeeStatus": "未提交",
    "Reviewer": "",
    "ConfirmationStatus": "未确认",
    "FeeName": "海运费",
    "Unit": "CNTR",
    "Currency": "USD",
    "Quantity": 1,
    "UnitPrice": 11,
    "TaxInclusivePrice": 11,
    "TaxExclusivePrice": 11,
    "TaxAmount": 0,
    "TaxRate": 0,
    "BusinessStatus": "正操作"
  },
  {
    "BusinessNumber": "SE2011008",
    "InWarehouseNumber": "SE2011008",
    "BookingNumber": "ASHAYIN200595345",
    "CutOffDate": "2020-11-25",
    "ProjectNumber": "",
    "Sono": "",
    "ContainerNumber": "",
    "OverseasCustomerService": "",
    "PaymentApplicationNumber": "",
    "BillNumber": "",
    "SettlementObject": "德翔航运（上海德圣船务有限公司）",
    "ConsignmentType": "自揽货",
    "MasterWaybillNumber": "ASHAYIN200624814E",
    "SubWaybillNumber": "SE2011008",
    "Consignor": "上海合金",
    "BusinessType": "海运出口",
    "BusinessDate": "2020-12-01",
    "VesselVoyage": "SM MUMBAI 2008E",
    "PortOfLoading": "SHANGHAI",
    "PortOfDestination": "TORONTO",
    "PlaceOfDeparture": "",
    "PlaceOfDestination": "",
    "TransitPort": "",
    "DestinationAgent": "",
    "Sales": "邵阳",
    "Operation": "黄琪",
    "CustomerService": "",
    "Document": "",
    "BusinessReferenceNumber": "1233.0",
    "DomesticOrForeign": "国内",
    "RevenueOrExpenditureType": "应付",
    "FeeStatus": "未提交",
    "Reviewer": "",
    "ConfirmationStatus": "未确认",
    "FeeName": "海运费",
    "Unit": "CNTR",
    "Currency": "USD",
    "Quantity": 1,
    "UnitPrice": 20,
    "TaxInclusivePrice": 20,
    "TaxExclusivePrice": 20,
    "TaxAmount": 0,
    "TaxRate": 0,
    "BusinessStatus": "正操作"
  },
  {
    "BusinessNumber": "SE2011003",
    "InWarehouseNumber": "SE2011003",
    "BookingNumber": "ASHAYIN200595345",
    "CutOffDate": "2020-11-25",
    "ProjectNumber": "",
    "Sono": "",
    "ContainerNumber": "",
    "OverseasCustomerService": "",
    "PaymentApplicationNumber": "",
    "BillNumber": "",
    "SettlementObject": "德翔航运（上海德圣船务有限公司）",
    "ConsignmentType": "自揽货",
    "MasterWaybillNumber": "SHFO0D658100",
    "SubWaybillNumber": "SE2011003",
    "Consignor": "上海合金",
    "BusinessType": "海运出口",
    "BusinessDate": "2020-12-01",
    "VesselVoyage": "SM MUMBAI 2008E",
    "PortOfLoading": "SHANGHAI",
    "PortOfDestination": "TORONTO",
    "PlaceOfDeparture": "",
    "PlaceOfDestination": "",
    "TransitPort": "",
    "DestinationAgent": "",
    "Sales": "邵阳",
    "Operation": "黄琪",
    "CustomerService": "",
    "Document": "",
    "BusinessReferenceNumber": "1233.0",
    "DomesticOrForeign": "国内",
    "RevenueOrExpenditureType": "应付",
    "FeeStatus": "未提交",
    "Reviewer": "",
    "ConfirmationStatus": "未确认",
    "FeeName": "海运费",
    "Unit": "CNTR",
    "Currency": "USD",
    "Quantity": 1,
    "UnitPrice": 11,
    "TaxInclusivePrice": 11,
    "TaxExclusivePrice": 11,
    "TaxAmount": 0,
    "TaxRate": 0,
    "BusinessStatus": "正操作"
  },
  {
    "BusinessNumber": "SE2011009",
    "InWarehouseNumber": "SE2011009",
    "BookingNumber": "ASHAYIN200595345",
    "CutOffDate": "2020-11-25",
    "ProjectNumber": "",
    "Sono": "",
    "ContainerNumber": "",
    "OverseasCustomerService": "",
    "PaymentApplicationNumber": "",
    "BillNumber": "",
    "SettlementObject": "澳大利亚航空公司",
    "ConsignmentType": "自揽货",
    "MasterWaybillNumber": "ASHAYIN200604654I",
    "SubWaybillNumber": "SE2011009",
    "Consignor": "上海合金",
    "BusinessType": "海运出口",
    "BusinessDate": "2020-12-01",
    "VesselVoyage": "SM MUMBAI 2008E",
    "PortOfLoading": "SHANGHAI",
    "PortOfDestination": "TORONTO",
    "PlaceOfDeparture": "",
    "PlaceOfDestination": "",
    "TransitPort": "",
    "DestinationAgent": "",
    "Sales": "邵阳",
    "Operation": "黄琪",
    "CustomerService": "",
    "Document": "",
    "BusinessReferenceNumber": "1233.0",
    "DomesticOrForeign": "国内",
    "RevenueOrExpenditureType": "应付",
    "FeeStatus": "未提交",
    "Reviewer": "",
    "ConfirmationStatus": "未确认",
    "FeeName": "报关单打印费",
    "Unit": "NML",
    "Currency": "RMB",
    "Quantity": 1,
    "UnitPrice": 21,
    "TaxInclusivePrice": 21,
    "TaxExclusivePrice": 21,
    "TaxAmount": 0,
    "TaxRate": 0,
    "BusinessStatus": "正操作"
  },
  {
    "BusinessNumber": "SE2011010",
    "InWarehouseNumber": "SE2011010",
    "BookingNumber": "ASHAYIN200595345",
    "CutOffDate": "2020-11-25",
    "ProjectNumber": "",
    "Sono": "",
    "ContainerNumber": "",
    "OverseasCustomerService": "",
    "PaymentApplicationNumber": "",
    "BillNumber": "",
    "SettlementObject": "德翔航运（上海德圣船务有限公司）",
    "ConsignmentType": "自揽货",
    "MasterWaybillNumber": "SHCR0W797600",
    "SubWaybillNumber": "SE2011010",
    "Consignor": "上海合金",
    "BusinessType": "海运出口",
    "BusinessDate": "2020-12-01",
    "VesselVoyage": "SM MUMBAI 2008E",
    "PortOfLoading": "SHANGHAI",
    "PortOfDestination": "TORONTO",
    "PlaceOfDeparture": "",
    "PlaceOfDestination": "",
    "TransitPort": "",
    "DestinationAgent": "",
    "Sales": "邵阳",
    "Operation": "黄琪",
    "CustomerService": "",
    "Document": "",
    "BusinessReferenceNumber": "1233.0",
    "DomesticOrForeign": "国内",
    "RevenueOrExpenditureType": "应付",
    "FeeStatus": "未提交",
    "Reviewer": "",
    "ConfirmationStatus": "未确认",
    "FeeName": "海运费",
    "Unit": "CNTR",
    "Currency": "USD",
    "Quantity": 1,
    "UnitPrice": 20,
    "TaxInclusivePrice": 20,
    "TaxExclusivePrice": 20,
    "TaxAmount": 0,
    "TaxRate": 0,
    "BusinessStatus": "正操作"
  },
  {
    "BusinessNumber": "SHSI200009001",
    "InWarehouseNumber": "SHSI200009001",
    "BookingNumber": "ASHAYIN200595345",
    "CutOffDate": "2020-11-25",
    "ProjectNumber": "",
    "Sono": "",
    "ContainerNumber": "",
    "OverseasCustomerService": "",
    "PaymentApplicationNumber": "",
    "BillNumber": "",
    "SettlementObject": "上海丽禧运输有限公司",
    "ConsignmentType": "自揽货",
    "MasterWaybillNumber": "5485495",
    "SubWaybillNumber": "SE2011010",
    "Consignor": "浙江森诺进出口有限公司",
    "BusinessType": "海运进口",
    "BusinessDate": "2020-10-29",
    "VesselVoyage": "",
    "PortOfLoading": "CAGAYAN",
    "PortOfDestination": "SHANGHAI",
    "PlaceOfDeparture": "",
    "PlaceOfDestination": "",
    "TransitPort": "",
    "DestinationAgent": "",
    "Sales": "崔晓光",
    "Operation": "黄琪",
    "CustomerService": "黄琪",
    "Document": "",
    "BusinessReferenceNumber": "1233.0",
    "DomesticOrForeign": "国内",
    "RevenueOrExpenditureType": "应付",
    "FeeStatus": "未提交",
    "Reviewer": "",
    "ConfirmationStatus": "未确认",
    "FeeName": "放箱费",
    "Unit": "NML",
    "Currency": "RMB",
    "Quantity": 5,
    "UnitPrice": 35,
    "TaxInclusivePrice": 175,
    "TaxExclusivePrice": 175,
    "TaxAmount": 0,
    "TaxRate": 0,
    "BusinessStatus": "正操作"
  }
];

const paymentApplicationBusinessItems:PaymentApplicationBusinessItemProps[] = [
  {
      "BusinessNumber":"SE2011005",
      "MasterOrderNumber":"SHCR0W809700",
      "Consignor":"上海合金",
      "SettlementObject":"德翔航运（上海德圣船务有限公司）",
      "Carrier":"德翔航运",
      "Sono":"",
      "OverseasCustomerService":"",
      "BusinessType":"海运出口",
      "BusinessDate":"2020-12-01",
      "VesselVoyage":"SM MUMBAI 2008E",
      "PortOfLoading":"SHANGHAI",
      "PortOfDestination":"TORONTO",
      "Operation":"黄琪",
      "Sales":"邵阳",
      "AccruedAmount":12,
      "Currency":"USD",
      "TaxInclusivePrice":12
  },
  {
      "BusinessNumber":"SE2011004",
      "MasterOrderNumber":"SHCR0W808600",
      "Consignor":"上海合金",
      "SettlementObject":"德翔航运（上海德圣船务有限公司）",
      "Carrier":"德翔航运",
      "Sono":"",
      "OverseasCustomerService":"",
      "BusinessType":"海运出口",
      "BusinessDate":"2020-12-01",
      "VesselVoyage":"SM MUMBAI 2008E",
      "PortOfLoading":"SHANGHAI",
      "PortOfDestination":"TORONTO",
      "Operation":"黄琪",
      "Sales":"邵阳",
      "AccruedAmount":11,
      "Currency":"USD",
      "TaxInclusivePrice":11
  },
  {
      "BusinessNumber":"SE2011010",
      "MasterOrderNumber":"SHCR0W797600",
      "Consignor":"上海合金",
      "SettlementObject":"澳大利亚航空公司",
      "Carrier":"德翔航运",
      "Sono":"",
      "OverseasCustomerService":"",
      "BusinessType":"海运出口",
      "BusinessDate":"2020-12-01",
      "VesselVoyage":"SM MUMBAI 2008E",
      "PortOfLoading":"SHANGHAI",
      "PortOfDestination":"TORONTO",
      "Operation":"黄琪",
      "Sales":"邵阳",
      "AccruedAmount":21,
      "Currency":"RMB",
      "TaxInclusivePrice":21
  },
  {
      "BusinessNumber":"SE2011011",
      "MasterOrderNumber":"SHCR0W797600",
      "Consignor":"上海合金",
      "SettlementObject":"德翔航运（上海德圣船务有限公司）",
      "Carrier":"德翔航运",
      "Sono":"",
      "OverseasCustomerService":"",
      "BusinessType":"海运出口",
      "BusinessDate":"2020-12-01",
      "VesselVoyage":"SM MUMBAI 2008E",
      "PortOfLoading":"SHANGHAI",
      "PortOfDestination":"TORONTO",
      "Operation":"黄琪",
      "Sales":"邵阳",
      "AccruedAmount":20,
      "Currency":"USD",
      "TaxInclusivePrice":20
  },
  {
      "BusinessNumber":"SE2011007",
      "MasterOrderNumber":"ASHAYIN200624814",
      "Consignor":"上海合金",
      "SettlementObject":"德翔航运（上海德圣船务有限公司）",
      "Carrier":"德翔航运",
      "Sono":"",
      "OverseasCustomerService":"",
      "BusinessType":"海运出口",
      "BusinessDate":"2020-12-01",
      "VesselVoyage":"SM MUMBAI 2008E",
      "PortOfLoading":"SHANGHAI",
      "PortOfDestination":"TORONTO",
      "Operation":"黄琪",
      "Sales":"邵阳",
      "AccruedAmount":20,
      "Currency":"USD",
      "TaxInclusivePrice":20
  },
  {
      "BusinessNumber":"SE2011009",
      "MasterOrderNumber":"ASHAYIN200604654I",
      "Consignor":"上海合金",
      "SettlementObject":"德翔航运（上海德圣船务有限公司）",
      "Carrier":"德翔航运",
      "Sono":"",
      "OverseasCustomerService":"",
      "BusinessType":"海运出口",
      "BusinessDate":"2020-12-01",
      "VesselVoyage":"SM MUMBAI 2008E",
      "PortOfLoading":"SHANGHAI",
      "PortOfDestination":"TORONTO",
      "Operation":"黄琪",
      "Sales":"邵阳",
      "AccruedAmount":20,
      "Currency":"USD",
      "TaxInclusivePrice":20
  },
  {
      "BusinessNumber":"SE2011005",
      "MasterOrderNumber":"SHCR0W809700",
      "Consignor":"上海合金",
      "SettlementObject":"澳大利亚航空公司",
      "Carrier":"德翔航运",
      "Sono":"",
      "OverseasCustomerService":"",
      "BusinessType":"海运出口",
      "BusinessDate":"2020-12-01",
      "VesselVoyage":"SM MUMBAI 2008E",
      "PortOfLoading":"SHANGHAI",
      "PortOfDestination":"TORONTO",
      "Operation":"黄琪",
      "Sales":"邵阳",
      "AccruedAmount":13,
      "Currency":"RMB",
      "TaxInclusivePrice":13
  },
  {
      "BusinessNumber":"SE2011006",
      "MasterOrderNumber":"SHCR0W810600",
      "Consignor":"上海合金",
      "SettlementObject":"澳大利亚航空公司",
      "Carrier":"德翔航运",
      "Sono":"",
      "OverseasCustomerService":"",
      "BusinessType":"海运出口",
      "BusinessDate":"2020-12-01",
      "VesselVoyage":"SM MUMBAI 2008E",
      "PortOfLoading":"SHANGHAI",
      "PortOfDestination":"TORONTO",
      "Operation":"黄琪",
      "Sales":"邵阳",
      "AccruedAmount":15,
      "Currency":"RMB",
      "TaxInclusivePrice":15
  },
  {
      "BusinessNumber":"SE2011004",
      "MasterOrderNumber":"SHCR0W808600",
      "Consignor":"上海合金",
      "SettlementObject":"澳大利亚航空公司",
      "Carrier":"德翔航运",
      "Sono":"",
      "OverseasCustomerService":"",
      "BusinessType":"海运出口",
      "BusinessDate":"2020-12-01",
      "VesselVoyage":"SM MUMBAI 2008E",
      "PortOfLoading":"SHANGHAI",
      "PortOfDestination":"TORONTO",
      "Operation":"黄琪",
      "Sales":"邵阳",
      "AccruedAmount":11,
      "Currency":"RMB",
      "TaxInclusivePrice":11
  },
  {
      "BusinessNumber":"SE2011002",
      "MasterOrderNumber":"SHFO0D657700",
      "Consignor":"上海合金",
      "SettlementObject":"澳大利亚航空公司",
      "Carrier":"德翔航运",
      "Sono":"",
      "OverseasCustomerService":"",
      "BusinessType":"海运出口",
      "BusinessDate":"2020-12-01",
      "VesselVoyage":"SM MUMBAI 2008E",
      "PortOfLoading":"SHANGHAI",
      "PortOfDestination":"TORONTO",
      "Operation":"黄琪",
      "Sales":"邵阳",
      "AccruedAmount":11,
      "Currency":"RMB",
      "TaxInclusivePrice":11
  },
  {
      "BusinessNumber":"SE2011008",
      "MasterOrderNumber":"ASHAYIN200624814E",
      "Consignor":"上海合金",
      "SettlementObject":"澳大利亚航空公司",
      "Carrier":"德翔航运",
      "Sono":"",
      "OverseasCustomerService":"",
      "BusinessType":"海运出口",
      "BusinessDate":"2020-12-01",
      "VesselVoyage":"SM MUMBAI 2008E",
      "PortOfLoading":"SHANGHAI",
      "PortOfDestination":"TORONTO",
      "Operation":"黄琪",
      "Sales":"邵阳",
      "AccruedAmount":21,
      "Currency":"RMB",
      "TaxInclusivePrice":21
  },
  {
      "BusinessNumber":"SE2011007",
      "MasterOrderNumber":"ASHAYIN200624814",
      "Consignor":"上海合金",
      "SettlementObject":"澳大利亚航空公司",
      "Carrier":"德翔航运",
      "Sono":"",
      "OverseasCustomerService":"",
      "BusinessType":"海运出口",
      "BusinessDate":"2020-12-01",
      "VesselVoyage":"SM MUMBAI 2008E",
      "PortOfLoading":"SHANGHAI",
      "PortOfDestination":"TORONTO",
      "Operation":"黄琪",
      "Sales":"邵阳",
      "AccruedAmount":21,
      "Currency":"RMB",
      "TaxInclusivePrice":21
  },
  {
      "BusinessNumber":"SE2011003",
      "MasterOrderNumber":"SHFO0D658100",
      "Consignor":"上海合金",
      "SettlementObject":"澳大利亚航空公司",
      "Carrier":"德翔航运",
      "Sono":"",
      "OverseasCustomerService":"",
      "BusinessType":"海运出口",
      "BusinessDate":"2020-12-01",
      "VesselVoyage":"SM MUMBAI 2008E",
      "PortOfLoading":"SHANGHAI",
      "PortOfDestination":"TORONTO",
      "Operation":"黄琪",
      "Sales":"邵阳",
      "AccruedAmount":11,
      "Currency":"RMB",
      "TaxInclusivePrice":11
  },
  {
      "BusinessNumber":"SE2011006",
      "MasterOrderNumber":"SHCR0W810600",
      "Consignor":"上海合金",
      "SettlementObject":"德翔航运（上海德圣船务有限公司）",
      "Carrier":"德翔航运",
      "Sono":"",
      "OverseasCustomerService":"",
      "BusinessType":"海运出口",
      "BusinessDate":"2020-12-01",
      "VesselVoyage":"SM MUMBAI 2008E",
      "PortOfLoading":"SHANGHAI",
      "PortOfDestination":"TORONTO",
      "Operation":"黄琪",
      "Sales":"邵阳",
      "AccruedAmount":14,
      "Currency":"USD",
      "TaxInclusivePrice":14
  },
  {
      "BusinessNumber":"SE2011002",
      "MasterOrderNumber":"SHFO0D657700",
      "Consignor":"上海合金",
      "SettlementObject":"德翔航运（上海德圣船务有限公司）",
      "Carrier":"德翔航运",
      "Sono":"",
      "OverseasCustomerService":"",
      "BusinessType":"海运出口",
      "BusinessDate":"2020-12-01",
      "VesselVoyage":"SM MUMBAI 2008E",
      "PortOfLoading":"SHANGHAI",
      "PortOfDestination":"TORONTO",
      "Operation":"黄琪",
      "Sales":"邵阳",
      "AccruedAmount":11,
      "Currency":"USD",
      "TaxInclusivePrice":11
  },
  {
      "BusinessNumber":"SE2011008",
      "MasterOrderNumber":"ASHAYIN200624814E",
      "Consignor":"上海合金",
      "SettlementObject":"德翔航运（上海德圣船务有限公司）",
      "Carrier":"德翔航运",
      "Sono":"",
      "OverseasCustomerService":"",
      "BusinessType":"海运出口",
      "BusinessDate":"2020-12-01",
      "VesselVoyage":"SM MUMBAI 2008E",
      "PortOfLoading":"SHANGHAI",
      "PortOfDestination":"TORONTO",
      "Operation":"黄琪",
      "Sales":"邵阳",
      "AccruedAmount":20,
      "Currency":"USD",
      "TaxInclusivePrice":20
  },
  {
      "BusinessNumber":"SE2011003",
      "MasterOrderNumber":"SHFO0D658100",
      "Consignor":"上海合金",
      "SettlementObject":"德翔航运（上海德圣船务有限公司）",
      "Carrier":"德翔航运",
      "Sono":"",
      "OverseasCustomerService":"",
      "BusinessType":"海运出口",
      "BusinessDate":"2020-12-01",
      "VesselVoyage":"SM MUMBAI 2008E",
      "PortOfLoading":"SHANGHAI",
      "PortOfDestination":"TORONTO",
      "Operation":"黄琪",
      "Sales":"邵阳",
      "AccruedAmount":11,
      "Currency":"USD",
      "TaxInclusivePrice":11
  },
  {
      "BusinessNumber":"SE2011009",
      "MasterOrderNumber":"ASHAYIN200604654I",
      "Consignor":"上海合金",
      "SettlementObject":"澳大利亚航空公司",
      "Carrier":"德翔航运",
      "Sono":"",
      "OverseasCustomerService":"",
      "BusinessType":"海运出口",
      "BusinessDate":"2020-12-01",
      "VesselVoyage":"SM MUMBAI 2008E",
      "PortOfLoading":"SHANGHAI",
      "PortOfDestination":"TORONTO",
      "Operation":"黄琪",
      "Sales":"邵阳",
      "AccruedAmount":21,
      "Currency":"RMB",
      "TaxInclusivePrice":21
  },
  {
      "BusinessNumber":"SE2011010",
      "MasterOrderNumber":"SHCR0W797600",
      "Consignor":"上海合金",
      "SettlementObject":"德翔航运（上海德圣船务有限公司）",
      "Carrier":"德翔航运",
      "Sono":"",
      "OverseasCustomerService":"",
      "BusinessType":"海运出口",
      "BusinessDate":"2020-12-01",
      "VesselVoyage":"SM MUMBAI 2008E",
      "PortOfLoading":"SHANGHAI",
      "PortOfDestination":"TORONTO",
      "Operation":"黄琪",
      "Sales":"邵阳",
      "AccruedAmount":20,
      "Currency":"USD",
      "TaxInclusivePrice":20
  },
  {
      "BusinessNumber":"SHSI200009001",
      "MasterOrderNumber":"5485495",
      "Consignor":"浙江森诺进出口有限公司",
      "SettlementObject":"上海丽禧运输有限公司",
      "Carrier":"德翔航运",
      "Sono":"",
      "OverseasCustomerService":"",
      "BusinessType":"海运进口",
      "BusinessDate":"2020-10-29",
      "VesselVoyage":"",
      "PortOfLoading":"CAGAYAN",
      "PortOfDestination":"SHANGHAI",
      "Operation":"黄琪",
      "Sales":"崔晓光",
      "AccruedAmount":175,
      "Currency":"RMB",
      "TaxInclusivePrice":175
  }
];
// 获取币制信息
export const getPaymentApplicationList = async (): Promise<PaymentApplicationItemProps[]> => {
  // const response = await request({
  //   method: "GET",
  //   url: "/payment_application"
  // })
  // const responseData = response?.data as ApiRes<PaymentApplicationItemProps[]>;
  // return responseData.data || [];
  return paymentApplicationItems;
}

export const getPaymentApplicationFeeList = async (): Promise<PaymentApplicationFeeItemProps[]> => {
  // const response = await request({
  //   method: "GET",
  //   url: "/payment_application_fee"
  // })
  // const responseData = response?.data as ApiRes<PaymentApplicationFeeItemProps[]>;
  // return responseData.data || [];
  return paymentApplicationFeeItems;
}

export const getPaymentApplicationBusinessList = async (): Promise<PaymentApplicationBusinessItemProps[]> => {
  // const response = await request({
  //   method: "GET",
  //   url: "/payment_application_business"
  // })
  // const responseData = response?.data as ApiRes<PaymentApplicationBusinessItemProps[]>;
  // return responseData.data || [];
  return paymentApplicationBusinessItems;
}

export const savePaymentApplication = (data:PaymentApplicationItemProps,onUploadProgress: (progress: number) => void) => {
  return requestWithProgress({
    method: 'POST',
    url: "/payment_application/save",
    data:data,
    onUploadProgress: (progress) => {
        onUploadProgress(progress);
    }
  })
}

