
import request, { ApiRes, requestWithProgress } from '../request'
import { PhysicalInvoiceItemProps } from "@/types/cost_manage/physical_invoice";
import Mock from "mockjs";
const physicalInvoiceItems:PhysicalInvoiceItemProps[] = [
  {
      InvoiceSerialNumber:Mock.mock('@ctitle(5)'),
      InvoiceType:Mock.mock('@ctitle(5)'),
      PurchaserName:Mock.mock('@ctitle(5)'),
      PurchaserTaxNumber:Mock.mock('@ctitle(5)'),
      InvoiceCode:Mock.mock('@ctitle(5)'),
      InvoiceNumber:Mock.mock('@ctitle(5)'),
      InvoiceDate:Mock.mock('@datetime()'),
      SellerName:Mock.mock('@ctitle(5)'),
      SellerTaxNumber:Mock.mock('@ctitle(5)'),
      TotalAmount:Mock.mock('@float(60, 100, 0, 2)'),
      FileName:Mock.mock('@ctitle(5)'),
      FilePath:Mock.mock('@ctitle(5)'),
      DownloadCount:Mock.mock('@string("number", 1, 3)'),
  },  
  {
      InvoiceSerialNumber:Mock.mock('@ctitle(5)'),
      InvoiceType:Mock.mock('@ctitle(5)'),
      PurchaserName:Mock.mock('@ctitle(5)'),
      PurchaserTaxNumber:Mock.mock('@ctitle(5)'),
      InvoiceCode:Mock.mock('@ctitle(5)'),
      InvoiceNumber:Mock.mock('@ctitle(5)'),
      InvoiceDate:Mock.mock('@datetime()'),
      SellerName:Mock.mock('@ctitle(5)'),
      SellerTaxNumber:Mock.mock('@ctitle(5)'),
      TotalAmount:Mock.mock('@float(60, 100, 0, 2)'),
      FileName:Mock.mock('@ctitle(5)'),
      FilePath:Mock.mock('@ctitle(5)'),
      DownloadCount:Mock.mock('@string("number", 1, 3)'),
  },  
  {
      InvoiceSerialNumber:Mock.mock('@ctitle(5)'),
      InvoiceType:Mock.mock('@ctitle(5)'),
      PurchaserName:Mock.mock('@ctitle(5)'),
      PurchaserTaxNumber:Mock.mock('@ctitle(5)'),
      InvoiceCode:Mock.mock('@ctitle(5)'),
      InvoiceNumber:Mock.mock('@ctitle(5)'),
      InvoiceDate:Mock.mock('@datetime()'),
      SellerName:Mock.mock('@ctitle(5)'),
      SellerTaxNumber:Mock.mock('@ctitle(5)'),
      TotalAmount:Mock.mock('@float(60, 100, 0, 2)'),
      FileName:Mock.mock('@ctitle(5)'),
      FilePath:Mock.mock('@ctitle(5)'),
      DownloadCount:Mock.mock('@string("number", 1, 3)'),
  },  
  {
      InvoiceSerialNumber:Mock.mock('@ctitle(5)'),
      InvoiceType:Mock.mock('@ctitle(5)'),
      PurchaserName:Mock.mock('@ctitle(5)'),
      PurchaserTaxNumber:Mock.mock('@ctitle(5)'),
      InvoiceCode:Mock.mock('@ctitle(5)'),
      InvoiceNumber:Mock.mock('@ctitle(5)'),
      InvoiceDate:Mock.mock('@datetime()'),
      SellerName:Mock.mock('@ctitle(5)'),
      SellerTaxNumber:Mock.mock('@ctitle(5)'),
      TotalAmount:Mock.mock('@float(60, 100, 0, 2)'),
      FileName:Mock.mock('@ctitle(5)'),
      FilePath:Mock.mock('@ctitle(5)'),
      DownloadCount:Mock.mock('@string("number", 1, 3)'),
  },  
  {
      InvoiceSerialNumber:Mock.mock('@ctitle(5)'),
      InvoiceType:Mock.mock('@ctitle(5)'),
      PurchaserName:Mock.mock('@ctitle(5)'),
      PurchaserTaxNumber:Mock.mock('@ctitle(5)'),
      InvoiceCode:Mock.mock('@ctitle(5)'),
      InvoiceNumber:Mock.mock('@ctitle(5)'),
      InvoiceDate:Mock.mock('@datetime()'),
      SellerName:Mock.mock('@ctitle(5)'),
      SellerTaxNumber:Mock.mock('@ctitle(5)'),
      TotalAmount:Mock.mock('@float(60, 100, 0, 2)'),
      FileName:Mock.mock('@ctitle(5)'),
      FilePath:Mock.mock('@ctitle(5)'),
      DownloadCount:Mock.mock('@string("number", 1, 3)'),
  },  
  {
      InvoiceSerialNumber:Mock.mock('@ctitle(5)'),
      InvoiceType:Mock.mock('@ctitle(5)'),
      PurchaserName:Mock.mock('@ctitle(5)'),
      PurchaserTaxNumber:Mock.mock('@ctitle(5)'),
      InvoiceCode:Mock.mock('@ctitle(5)'),
      InvoiceNumber:Mock.mock('@ctitle(5)'),
      InvoiceDate:Mock.mock('@datetime()'),
      SellerName:Mock.mock('@ctitle(5)'),
      SellerTaxNumber:Mock.mock('@ctitle(5)'),
      TotalAmount:Mock.mock('@float(60, 100, 0, 2)'),
      FileName:Mock.mock('@ctitle(5)'),
      FilePath:Mock.mock('@ctitle(5)'),
      DownloadCount:Mock.mock('@string("number", 1, 3)'),
  },  
  {
      InvoiceSerialNumber:Mock.mock('@ctitle(5)'),
      InvoiceType:Mock.mock('@ctitle(5)'),
      PurchaserName:Mock.mock('@ctitle(5)'),
      PurchaserTaxNumber:Mock.mock('@ctitle(5)'),
      InvoiceCode:Mock.mock('@ctitle(5)'),
      InvoiceNumber:Mock.mock('@ctitle(5)'),
      InvoiceDate:Mock.mock('@datetime()'),
      SellerName:Mock.mock('@ctitle(5)'),
      SellerTaxNumber:Mock.mock('@ctitle(5)'),
      TotalAmount:Mock.mock('@float(60, 100, 0, 2)'),
      FileName:Mock.mock('@ctitle(5)'),
      FilePath:Mock.mock('@ctitle(5)'),
      DownloadCount:Mock.mock('@string("number", 1, 3)'),
  },  
  {
      InvoiceSerialNumber:Mock.mock('@ctitle(5)'),
      InvoiceType:Mock.mock('@ctitle(5)'),
      PurchaserName:Mock.mock('@ctitle(5)'),
      PurchaserTaxNumber:Mock.mock('@ctitle(5)'),
      InvoiceCode:Mock.mock('@ctitle(5)'),
      InvoiceNumber:Mock.mock('@ctitle(5)'),
      InvoiceDate:Mock.mock('@datetime()'),
      SellerName:Mock.mock('@ctitle(5)'),
      SellerTaxNumber:Mock.mock('@ctitle(5)'),
      TotalAmount:Mock.mock('@float(60, 100, 0, 2)'),
      FileName:Mock.mock('@ctitle(5)'),
      FilePath:Mock.mock('@ctitle(5)'),
      DownloadCount:Mock.mock('@string("number", 1, 3)'),
  },  
  {
      InvoiceSerialNumber:Mock.mock('@ctitle(5)'),
      InvoiceType:Mock.mock('@ctitle(5)'),
      PurchaserName:Mock.mock('@ctitle(5)'),
      PurchaserTaxNumber:Mock.mock('@ctitle(5)'),
      InvoiceCode:Mock.mock('@ctitle(5)'),
      InvoiceNumber:Mock.mock('@ctitle(5)'),
      InvoiceDate:Mock.mock('@datetime()'),
      SellerName:Mock.mock('@ctitle(5)'),
      SellerTaxNumber:Mock.mock('@ctitle(5)'),
      TotalAmount:Mock.mock('@float(60, 100, 0, 2)'),
      FileName:Mock.mock('@ctitle(5)'),
      FilePath:Mock.mock('@ctitle(5)'),
      DownloadCount:Mock.mock('@string("number", 1, 3)'),
  },  
  {
      InvoiceSerialNumber:Mock.mock('@ctitle(5)'),
      InvoiceType:Mock.mock('@ctitle(5)'),
      PurchaserName:Mock.mock('@ctitle(5)'),
      PurchaserTaxNumber:Mock.mock('@ctitle(5)'),
      InvoiceCode:Mock.mock('@ctitle(5)'),
      InvoiceNumber:Mock.mock('@ctitle(5)'),
      InvoiceDate:Mock.mock('@datetime()'),
      SellerName:Mock.mock('@ctitle(5)'),
      SellerTaxNumber:Mock.mock('@ctitle(5)'),
      TotalAmount:Mock.mock('@float(60, 100, 0, 2)'),
      FileName:Mock.mock('@ctitle(5)'),
      FilePath:Mock.mock('@ctitle(5)'),
      DownloadCount:Mock.mock('@string("number", 1, 3)'),
  },  
  {
      InvoiceSerialNumber:Mock.mock('@ctitle(5)'),
      InvoiceType:Mock.mock('@ctitle(5)'),
      PurchaserName:Mock.mock('@ctitle(5)'),
      PurchaserTaxNumber:Mock.mock('@ctitle(5)'),
      InvoiceCode:Mock.mock('@ctitle(5)'),
      InvoiceNumber:Mock.mock('@ctitle(5)'),
      InvoiceDate:Mock.mock('@datetime()'),
      SellerName:Mock.mock('@ctitle(5)'),
      SellerTaxNumber:Mock.mock('@ctitle(5)'),
      TotalAmount:Mock.mock('@float(60, 100, 0, 2)'),
      FileName:Mock.mock('@ctitle(5)'),
      FilePath:Mock.mock('@ctitle(5)'),
      DownloadCount:Mock.mock('@string("number", 1, 3)'),
  },  
  {
      InvoiceSerialNumber:Mock.mock('@ctitle(5)'),
      InvoiceType:Mock.mock('@ctitle(5)'),
      PurchaserName:Mock.mock('@ctitle(5)'),
      PurchaserTaxNumber:Mock.mock('@ctitle(5)'),
      InvoiceCode:Mock.mock('@ctitle(5)'),
      InvoiceNumber:Mock.mock('@ctitle(5)'),
      InvoiceDate:Mock.mock('@datetime()'),
      SellerName:Mock.mock('@ctitle(5)'),
      SellerTaxNumber:Mock.mock('@ctitle(5)'),
      TotalAmount:Mock.mock('@float(60, 100, 0, 2)'),
      FileName:Mock.mock('@ctitle(5)'),
      FilePath:Mock.mock('@ctitle(5)'),
      DownloadCount:Mock.mock('@string("number", 1, 3)'),
  },  
  {
      InvoiceSerialNumber:Mock.mock('@ctitle(5)'),
      InvoiceType:Mock.mock('@ctitle(5)'),
      PurchaserName:Mock.mock('@ctitle(5)'),
      PurchaserTaxNumber:Mock.mock('@ctitle(5)'),
      InvoiceCode:Mock.mock('@ctitle(5)'),
      InvoiceNumber:Mock.mock('@ctitle(5)'),
      InvoiceDate:Mock.mock('@datetime()'),
      SellerName:Mock.mock('@ctitle(5)'),
      SellerTaxNumber:Mock.mock('@ctitle(5)'),
      TotalAmount:Mock.mock('@float(60, 100, 0, 2)'),
      FileName:Mock.mock('@ctitle(5)'),
      FilePath:Mock.mock('@ctitle(5)'),
      DownloadCount:Mock.mock('@string("number", 1, 3)'),
  },  
  {
      InvoiceSerialNumber:Mock.mock('@ctitle(5)'),
      InvoiceType:Mock.mock('@ctitle(5)'),
      PurchaserName:Mock.mock('@ctitle(5)'),
      PurchaserTaxNumber:Mock.mock('@ctitle(5)'),
      InvoiceCode:Mock.mock('@ctitle(5)'),
      InvoiceNumber:Mock.mock('@ctitle(5)'),
      InvoiceDate:Mock.mock('@datetime()'),
      SellerName:Mock.mock('@ctitle(5)'),
      SellerTaxNumber:Mock.mock('@ctitle(5)'),
      TotalAmount:Mock.mock('@float(60, 100, 0, 2)'),
      FileName:Mock.mock('@ctitle(5)'),
      FilePath:Mock.mock('@ctitle(5)'),
      DownloadCount:Mock.mock('@string("number", 1, 3)'),
  },  
  {
      InvoiceSerialNumber:Mock.mock('@ctitle(5)'),
      InvoiceType:Mock.mock('@ctitle(5)'),
      PurchaserName:Mock.mock('@ctitle(5)'),
      PurchaserTaxNumber:Mock.mock('@ctitle(5)'),
      InvoiceCode:Mock.mock('@ctitle(5)'),
      InvoiceNumber:Mock.mock('@ctitle(5)'),
      InvoiceDate:Mock.mock('@datetime()'),
      SellerName:Mock.mock('@ctitle(5)'),
      SellerTaxNumber:Mock.mock('@ctitle(5)'),
      TotalAmount:Mock.mock('@float(60, 100, 0, 2)'),
      FileName:Mock.mock('@ctitle(5)'),
      FilePath:Mock.mock('@ctitle(5)'),
      DownloadCount:Mock.mock('@string("number", 1, 3)'),
  },  
  {
      InvoiceSerialNumber:Mock.mock('@ctitle(5)'),
      InvoiceType:Mock.mock('@ctitle(5)'),
      PurchaserName:Mock.mock('@ctitle(5)'),
      PurchaserTaxNumber:Mock.mock('@ctitle(5)'),
      InvoiceCode:Mock.mock('@ctitle(5)'),
      InvoiceNumber:Mock.mock('@ctitle(5)'),
      InvoiceDate:Mock.mock('@datetime()'),
      SellerName:Mock.mock('@ctitle(5)'),
      SellerTaxNumber:Mock.mock('@ctitle(5)'),
      TotalAmount:Mock.mock('@float(60, 100, 0, 2)'),
      FileName:Mock.mock('@ctitle(5)'),
      FilePath:Mock.mock('@ctitle(5)'),
      DownloadCount:Mock.mock('@string("number", 1, 3)'),
  },  
  {
      InvoiceSerialNumber:Mock.mock('@ctitle(5)'),
      InvoiceType:Mock.mock('@ctitle(5)'),
      PurchaserName:Mock.mock('@ctitle(5)'),
      PurchaserTaxNumber:Mock.mock('@ctitle(5)'),
      InvoiceCode:Mock.mock('@ctitle(5)'),
      InvoiceNumber:Mock.mock('@ctitle(5)'),
      InvoiceDate:Mock.mock('@datetime()'),
      SellerName:Mock.mock('@ctitle(5)'),
      SellerTaxNumber:Mock.mock('@ctitle(5)'),
      TotalAmount:Mock.mock('@float(60, 100, 0, 2)'),
      FileName:Mock.mock('@ctitle(5)'),
      FilePath:Mock.mock('@ctitle(5)'),
      DownloadCount:Mock.mock('@string("number", 1, 3)'),
  },  
  {
      InvoiceSerialNumber:Mock.mock('@ctitle(5)'),
      InvoiceType:Mock.mock('@ctitle(5)'),
      PurchaserName:Mock.mock('@ctitle(5)'),
      PurchaserTaxNumber:Mock.mock('@ctitle(5)'),
      InvoiceCode:Mock.mock('@ctitle(5)'),
      InvoiceNumber:Mock.mock('@ctitle(5)'),
      InvoiceDate:Mock.mock('@datetime()'),
      SellerName:Mock.mock('@ctitle(5)'),
      SellerTaxNumber:Mock.mock('@ctitle(5)'),
      TotalAmount:Mock.mock('@float(60, 100, 0, 2)'),
      FileName:Mock.mock('@ctitle(5)'),
      FilePath:Mock.mock('@ctitle(5)'),
      DownloadCount:Mock.mock('@string("number", 1, 3)'),
  },  
  {
      InvoiceSerialNumber:Mock.mock('@ctitle(5)'),
      InvoiceType:Mock.mock('@ctitle(5)'),
      PurchaserName:Mock.mock('@ctitle(5)'),
      PurchaserTaxNumber:Mock.mock('@ctitle(5)'),
      InvoiceCode:Mock.mock('@ctitle(5)'),
      InvoiceNumber:Mock.mock('@ctitle(5)'),
      InvoiceDate:Mock.mock('@datetime()'),
      SellerName:Mock.mock('@ctitle(5)'),
      SellerTaxNumber:Mock.mock('@ctitle(5)'),
      TotalAmount:Mock.mock('@float(60, 100, 0, 2)'),
      FileName:Mock.mock('@ctitle(5)'),
      FilePath:Mock.mock('@ctitle(5)'),
      DownloadCount:Mock.mock('@string("number", 1, 3)'),
  },  
];
// 获取币制信息
export const getPhysicalInvoiceList = async () : Promise<PhysicalInvoiceItemProps[]> => {
  // const response = await request({
  //   method: "GET",
  //   url: "/physical_invoice"
  // });
  // const responseData = response?.data as ApiRes<PhysicalInvoiceItemProps[]>;
  // return responseData.data || [];
  return physicalInvoiceItems;
}

export const savePhysicalInvoice = (data:PhysicalInvoiceItemProps,onUploadProgress: (progress: number) => void) => {
  return requestWithProgress({
    method: 'POST',
    url: "/physical_invoice/save",
    data:data,
    onUploadProgress: (progress) => {
        onUploadProgress(progress);
    }
  })
}

