
import { TableColumnsType, Tag, Popconfirm } from 'antd';
import { BusinessPartnerItemProps } from "@/types/dynamic_configuration_platform/basic_manage/business_partner";
import i18n from '@/i18n';
import LocaleHelper from '@/utils/locale';
import { NavLink } from 'react-router-dom';



export const getColumns = (handleEdit: (record: BusinessPartnerItemProps) => void, handleDelete: (record: BusinessPartnerItemProps) => void): TableColumnsType<BusinessPartnerItemProps> => [

    {
        title: i18n.t(LocaleHelper.getBusinessPartnerId()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Id',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerAbbreviatedName()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'AbbreviatedName',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerCode()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Code',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerCountryRegion()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CountryRegion',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerChineseName()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'ChineseName',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerEnglishName()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'EnglishName',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerCustomerContractStatus()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CustomerContractStatus',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerAdditionalRemarks()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'AdditionalRemarks',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerBranchCompany()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BranchCompany',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerAuditStatus()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'AuditStatus',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerRejectionReason()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'RejectionReason',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerAuditor()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Auditor',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerAuditDate()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'AuditDate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerCreator()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Creator',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerCreationDate()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CreationDate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerModifier()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Modifier',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerModificationDate()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'ModificationDate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerIsActive()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'IsActive',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerECommerceCustomer()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'ECommerceCustomer',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerSales()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Sales',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerSettlementType()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'SettlementType',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerCreditControlDateType()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CreditControlDateType',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerSettlementMethod()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'SettlementMethod',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerBlacklist()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Blacklist',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerFreightType()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'FreightType',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerRevenueExpenditureType()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'RevenueExpenditureType',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerCreditPeriod()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CreditPeriod',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerCreditLimit()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CreditLimit',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerCreditControlLimit()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CreditControlLimit',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerCreditCurrency()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CreditCurrency',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerOver30Days()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Over30Days',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerOver60Days()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Over60Days',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerOver90Days()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Over90Days',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerOver90PlusDays()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Over90PlusDays',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerSource()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Source',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerCustomerSource()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CustomerSource',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerCustomerContactChannel()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CustomerContactChannel',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerSupplierResponsiblePerson()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'SupplierResponsiblePerson',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerBusinessType()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BusinessType',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerAddress()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Address',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerCustomerLevel()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CustomerLevel',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerAffiliationDepartment()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'AffiliationDepartment',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerOverseasCustomerService()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'OverseasCustomerService',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerCustomerCode()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CustomerCode',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerSupplierCode()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'SupplierCode',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerCreditAccountsReceivableRemarks()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CreditAccountsReceivableRemarks',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerSupplierContractStatus()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'SupplierContractStatus',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerOverseasAgentContractStatus()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'OverseasAgentContractStatus',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerOtherContractStatus()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'OtherContractStatus',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerContractNumberStatus()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'ContractNumberStatus',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerCarriageType()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CarriageType',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerDocumentNumber()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'DocumentNumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getBusinessPartnerIsContractAttachmentUploaded()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'IsContractAttachmentUploaded',
        sorter: true,
        align: 'right',
    },
    {
        title: '操作',
        key: 'operation',
        fixed: 'right',
        width: 100,
        render: (_, record) => (
        <>
            <NavLink to={`/cooperation_party/business_partner/detail?id=${record.Id}`}>详细</NavLink>
            <Popconfirm title="确定要删除吗?" cancelText="取消" okText="确定" onConfirm={() => handleDelete(record)}>
                <a>删除</a>
            </Popconfirm>
        </>
        ),
    },
]; 
