
import { TableColumnsType, Tag, Popconfirm } from 'antd';
import { ExpenseReviewItemProps } from "@/types/expense_review/expense_review";
import i18n from '@/i18n';
import LocaleHelper from '@/utils/locale';
import { NavLink } from 'react-router-dom';



export const getColumns = (handleEdit: (record: ExpenseReviewItemProps) => void, handleDelete: (record: ExpenseReviewItemProps) => void): TableColumnsType<ExpenseReviewItemProps> => [

    {
        title: i18n.t(LocaleHelper.getExpenseReviewBusinessNumber()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BusinessNumber',
        sorter: true,
        align: 'left',
        fixed: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewContainerType()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'ContainerType',
        sorter: true,
        align: 'left',
        fixed: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewBusinessType()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BusinessType',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewMasterNumber()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'MasterNumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewSplitNumber()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'SplitNumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewCustomerName()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CustomerName',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewCargoType()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CargoType',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewCustomerLevel()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CustomerLevel',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewContractStatus()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'ContractStatus',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewCarrierName()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CarrierName',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewVesselName()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'VesselName',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewVoyageFlight()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'VoyageFlight',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewLoadingPort()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'LoadingPort',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewDestinationPort()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'DestinationPort',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewDeliveryPlace()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'DeliveryPlace',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewDischargingPort()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'DischargingPort',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewEtd()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Etd',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewEta()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Eta',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewBusinessDate()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BusinessDate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewBookingAgent()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BookingAgent',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewCreationDate()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CreationDate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewVoucherWord()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'VoucherWord',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewVoucherNumber()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'VoucherNumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewBusinessRefNumber()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BusinessRefNumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewProjectNumber()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'ProjectNumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewOperationStaff()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'OperationStaff',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewSalesStaff()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'SalesStaff',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewCustomerServiceStaff()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CustomerServiceStaff',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewDocumentStaff()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'DocumentStaff',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewSolicitationType()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'SolicitationType',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewStatus()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Status',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewActualChargeableWeight()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'ActualChargeableWeight',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewProfit()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'Profit',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewTotalRevenue()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'TotalRevenue',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewTotalCost()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'TotalCost',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewPayableReconciliationStatus()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'PayableReconciliationStatus',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewReceivableReconciliationStatus()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'ReceivableReconciliationStatus',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewBusinessCreator()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BusinessCreator',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewContainerDescription()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'ContainerDescription',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewAppointedAgent()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'AppointedAgent',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewMasterFreightTerms()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'MasterFreightTerms',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewSplitFreightTerms()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'SplitFreightTerms',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewTradeTerms()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'TradeTerms',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewOperationMode()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'OperationMode',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewCustomField1()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CustomField1',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewCustomField2()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CustomField2',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewCustomField3()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CustomField3',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewProfitReviewStatus()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'ProfitReviewStatus',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewRouteName()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'RouteName',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewRouteManager()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'RouteManager',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewDestinationAgent()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'DestinationAgent',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewCustomPosition1()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CustomPosition1',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewCustomPosition2()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CustomPosition2',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewPickupDeliveryLocation()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'PickupDeliveryLocation',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewTruckPickupTime()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'TruckPickupTime',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewBookingNumber()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'BookingNumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewSopStatus()),
        width: '100px',
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'SopStatus',
        sorter: false,
        align: 'left',
        render: (text: string) => {
            return <div title={text} style={{ maxWidth:'200px',whiteSpace: 'nowrap',wordWrap: 'break-word', wordBreak: 'break-word',textOverflow:'ellipsis',overflow:'hidden'}}>{text}</div>;
        },
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewCancellationReviewReason()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'CancellationReviewReason',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewChargeLockTime()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'ChargeLockTime',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getExpenseReviewPayableLockTime()),
        width: 100,
        onHeaderCell: () => ({ style: { width: '100px' } }),
        dataIndex: 'PayableLockTime',
        sorter: true,
        align: 'center',
    },
    {
        title: '操作',
        key: 'operation',
        fixed: 'right',
        width: 20,
        render: (_, record) => (
        <>
            <NavLink to={`/orders/detail?businessId=${record.BusinessNumber}`}>详细</NavLink>
        </>
        ),
    },
]; 
