
import request, { ApiRes, requestWithProgress } from '../request'
import { ExpenseReviewItemProps } from "@/types/finance_manage/expense_review/expense_review";
import Mock from "mockjs";
//
const expenseReviewItems: ExpenseReviewItemProps[] = [
    {
        "BusinessNumber": "SHAE21050001",
        "ContainerType": "整箱",
        "BusinessType": "空运出口",
        "MasterNumber": "SHAE21050001",
        "SplitNumber": "SHAE50001",
        "CustomerName": "上海苍鹭实业有限公司",
        "CargoType": "普货",
        "CustomerLevel": "普通客户",
        "ContractStatus": "未签约",
        "CarrierName": "[HLHJHKGS]荷兰皇家航空公司",
        "VesselName": "荷兰皇家航空公司",
        "VoyageFlight": "飞机起飞",
        "LoadingPort": "SHENZHEN",
        "DestinationPort": "DELHI",
        "DeliveryPlace": "DELHI",
        "DischargingPort": "DELHI",
        "Etd": "2021-05-14",
        "Eta": "2021-05-15",
        "BusinessDate": "2021-05-14",
        "BookingAgent": "荷兰皇家航空公司",
        "CreationDate": "2021-05-07",
        "VoucherWord": "",
        "VoucherNumber": "0",
        "BusinessRefNumber": "HTSHA00001",
        "ProjectNumber": "5555",
        "OperationStaff": "李朋朋",
        "SalesStaff": "甘以星",
        "CustomerServiceStaff": "李朋朋",
        "DocumentStaff": "OP",
        "SolicitationType": "自揽货",
        "Status": "正操作",
        "ActualChargeableWeight": 1600.0,
        "Profit": 0.0,
        "TotalRevenue": 0.0,
        "TotalCost": 0.0,
        "PayableReconciliationStatus": "无应付",
        "ReceivableReconciliationStatus": "无应收",
        "BusinessCreator": "李朋朋",
        "ContainerDescription": "1*40HC",
        "AppointedAgent": "COMM FORWARDING COMPANY",
        "MasterFreightTerms": "FREIGHT PREPAID",
        "SplitFreightTerms": "FREIGHT PREPAID",
        "TradeTerms": "CIF",
        "OperationMode": "一主一分",
        "CustomField1": "",
        "CustomField2": "",
        "CustomField3": "",
        "ProfitReviewStatus": "未审核",
        "RouteName": "印巴",
        "RouteManager": "",
        "DestinationAgent": "COMM FORWARDING COMPANY",
        "CustomPosition1": "",
        "CustomPosition2": "",
        "PickupDeliveryLocation": "SHANGHAI",
        "TruckPickupTime": "2020-10-31",
        "BookingNumber": "ASHAYIN200595345",
        "SopStatus": "接单(已接单),订舱(未订舱),报关(Y),送货(未送货),飞机起飞(Y),到港(未到港)",
        "CancellationReviewReason": "",
        "ChargeLockTime": "2025-02-21 15:28:55",
        "PayableLockTime": "2025-02-21 15:28:55"
    },
    {
        "BusinessNumber": "SE21003",
        "ContainerType": "整箱",
        "BusinessType": "海运出口",
        "MasterNumber": "SE21003",
        "SplitNumber": "SE21003",
        "CustomerName": "上海好年国际贸易有限公司",
        "CargoType": "普货",
        "CustomerLevel": "VIP客户",
        "ContractStatus": "未签约",
        "CarrierName": "现代商船（中国）有限公司",
        "VesselName": "现代商船",
        "VoyageFlight": "V.2104E",
        "LoadingPort": "SHANGHAI",
        "DestinationPort": "DELHI",
        "DeliveryPlace": "LOS ANGELES,CA",
        "DischargingPort": "LOS ANGELES,CA",
        "Etd": "2021-05-18",
        "Eta": "2021-05-15",
        "BusinessDate": "2021-05-18",
        "BookingAgent": "荷兰皇家航空公司",
        "CreationDate": "2021-05-07",
        "VoucherWord": "",
        "VoucherNumber": "0",
        "BusinessRefNumber": "HTSHA00001",
        "ProjectNumber": "5555",
        "OperationStaff": "邵阳",
        "SalesStaff": "邵阳",
        "CustomerServiceStaff": "刘风彩",
        "DocumentStaff": "OP",
        "SolicitationType": "自揽货",
        "Status": "正操作",
        "ActualChargeableWeight": 11.0,
        "Profit": 0.0,
        "TotalRevenue": 0.0,
        "TotalCost": 0.0,
        "PayableReconciliationStatus": "无应付",
        "ReceivableReconciliationStatus": "无应收",
        "BusinessCreator": "李朋朋",
        "ContainerDescription": "1*20GP",
        "AppointedAgent": "COMM FORWARDING COMPANY",
        "MasterFreightTerms": "FREIGHT PREPAID",
        "SplitFreightTerms": "FREIGHT PREPAID",
        "TradeTerms": "FOB",
        "OperationMode": "一主一分",
        "CustomField1": "",
        "CustomField2": "",
        "CustomField3": "",
        "ProfitReviewStatus": "未审核",
        "RouteName": "美西",
        "RouteManager": "",
        "DestinationAgent": "COMM FORWARDING COMPANY",
        "CustomPosition1": "",
        "CustomPosition2": "",
        "PickupDeliveryLocation": "SHANGHAI",
        "TruckPickupTime": "2020-10-31",
        "BookingNumber": "ASHAYIN200595345",
        "SopStatus": "接单(未接单),订舱(pending),货物进仓(未入库),安排拖车(未派车),货物装箱(未装箱),报关单证(未收到),离港(未离港),提单(未制单),到港(未到港),已完结(),卸区(未确定)",
        "CancellationReviewReason": "",
        "ChargeLockTime": "2025-02-21 15:28:55",
        "PayableLockTime": "2025-02-21 15:28:55"
    },
    {
        "BusinessNumber": "SE21002",
        "ContainerType": "自拼箱",
        "BusinessType": "海运出口",
        "MasterNumber": "SE21002",
        "SplitNumber": "SE21002",
        "CustomerName": "上海沃行信息技术有限公司",
        "CargoType": "普货",
        "CustomerLevel": "VIP客户",
        "ContractStatus": "合约失效",
        "CarrierName": "高丽海运株式会社",
        "VesselName": "高丽海运",
        "VoyageFlight": "V.2008E",
        "LoadingPort": "SHENZHEN,CHINA",
        "DestinationPort": "DELHI",
        "DeliveryPlace": "OSAKA",
        "DischargingPort": "OSAKA",
        "Etd": "2021-03-25",
        "Eta": "2021-05-15",
        "BusinessDate": "2021-03-25",
        "BookingAgent": "美国联合轮船代理有限公司上海联合国际船舶代理有限公司",
        "CreationDate": "2021-03-15",
        "VoucherWord": "",
        "VoucherNumber": "0",
        "BusinessRefNumber": "HTSHA00001",
        "ProjectNumber": "5555",
        "OperationStaff": "邵阳",
        "SalesStaff": "崔晓光",
        "CustomerServiceStaff": "刘风彩",
        "DocumentStaff": "OP",
        "SolicitationType": "指定货",
        "Status": "正操作",
        "ActualChargeableWeight": 25.0,
        "Profit": -27.0,
        "TotalRevenue": 114.0,
        "TotalCost": 141.0,
        "PayableReconciliationStatus": "未核销",
        "ReceivableReconciliationStatus": "未核销",
        "BusinessCreator": "干建英",
        "ContainerDescription": "1*40HC",
        "AppointedAgent": "COMM FORWARDING COMPANY",
        "MasterFreightTerms": "FREIGHT PREPAID",
        "SplitFreightTerms": "FREIGHT PREPAID",
        "TradeTerms": "CIF",
        "OperationMode": "一主一分",
        "CustomField1": "",
        "CustomField2": "",
        "CustomField3": "",
        "ProfitReviewStatus": "未审核",
        "RouteName": "东南亚",
        "RouteManager": "",
        "DestinationAgent": "COMM FORWARDING COMPANY",
        "CustomPosition1": "",
        "CustomPosition2": "",
        "PickupDeliveryLocation": "SHANGHAI",
        "TruckPickupTime": "2020-10-31",
        "BookingNumber": "ASHAYIN200595345",
        "SopStatus": "接单(未接单),订舱(pending),货物进仓(未入库),安排拖车(未派车),货物装箱(未装箱),报关单证(未收到),离港(未离港),提单(未制单),到港(未到港),已完结(),卸区(未确定)",
        "CancellationReviewReason": "",
        "ChargeLockTime": "2025-02-21 15:28:55",
        "PayableLockTime": "2025-02-21 15:28:55"
    },
    {
        "BusinessNumber": "SI210007",
        "ContainerType": "整箱",
        "BusinessType": "海运进口",
        "MasterNumber": "SI210007",
        "SplitNumber": "SE21002",
        "CustomerName": "浙江森诺进出口有限公司",
        "CargoType": "普货",
        "CustomerLevel": "VIP客户",
        "ContractStatus": "未签约",
        "CarrierName": "高丽海运株式会社",
        "VesselName": "高丽海运",
        "VoyageFlight": "V.2008E",
        "LoadingPort": "LOS ANGELES,CA",
        "DestinationPort": "DELHI",
        "DeliveryPlace": "SHANGHAI",
        "DischargingPort": "SHANGHAI",
        "Etd": "2021-02-19",
        "Eta": "2021-03-13",
        "BusinessDate": "2021-03-13",
        "BookingAgent": "美国联合轮船代理有限公司上海联合国际船舶代理有限公司",
        "CreationDate": "2021-02-23",
        "VoucherWord": "",
        "VoucherNumber": "0",
        "BusinessRefNumber": "HTSHA00001",
        "ProjectNumber": "5555",
        "OperationStaff": "邵阳",
        "SalesStaff": "刘风彩",
        "CustomerServiceStaff": "戴翊雯",
        "DocumentStaff": "OP",
        "SolicitationType": "指定货",
        "Status": "正操作",
        "ActualChargeableWeight": 460.0,
        "Profit": 22900.0,
        "TotalRevenue": 50000.0,
        "TotalCost": 27100.0,
        "PayableReconciliationStatus": "未核销",
        "ReceivableReconciliationStatus": "未核销",
        "BusinessCreator": "戴翊雯",
        "ContainerDescription": "10*40GP",
        "AppointedAgent": "COMM FORWARDING COMPANY",
        "MasterFreightTerms": "FREIGHT PREPAID",
        "SplitFreightTerms": "FREIGHT PREPAID",
        "TradeTerms": "CIF",
        "OperationMode": "一主一分",
        "CustomField1": "",
        "CustomField2": "",
        "CustomField3": "",
        "ProfitReviewStatus": "未审核",
        "RouteName": "东南亚",
        "RouteManager": "",
        "DestinationAgent": "COMM FORWARDING COMPANY",
        "CustomPosition1": "",
        "CustomPosition2": "",
        "PickupDeliveryLocation": "SHANGHAI",
        "TruckPickupTime": "2020-10-31",
        "BookingNumber": "ASHAYIN200595345",
        "SopStatus": "订舱(已订舱 2020-11-17 11:12:05),配船(Y),离港(Y),到港(Y),换单(Y),提箱(Y),报关(Y),送货(Y)",
        "CancellationReviewReason": "",
        "ChargeLockTime": "2025-02-21 15:28:55",
        "PayableLockTime": "2025-02-21 15:28:55"
    },
    {
        "BusinessNumber": "SE2101001",
        "ContainerType": "整箱",
        "BusinessType": "海运出口",
        "MasterNumber": "SE2101001",
        "SplitNumber": "SE2101001",
        "CustomerName": "上海沃行信息技术有限公司",
        "CargoType": "普货",
        "CustomerLevel": "VIP客户",
        "ContractStatus": "合约失效",
        "CarrierName": "高丽海运株式会社",
        "VesselName": "MILD WALTZ",
        "VoyageFlight": "V.2104E",
        "LoadingPort": "SHANGHAI",
        "DestinationPort": "DELHI",
        "DeliveryPlace": "LOS ANGELES,CA",
        "DischargingPort": "LOS ANGELES,CA",
        "Etd": "2021-01-26",
        "Eta": "2021-02-10",
        "BusinessDate": "2021-01-26",
        "BookingAgent": "美国总统班轮公司",
        "CreationDate": "2021-01-20",
        "VoucherWord": "",
        "VoucherNumber": "0",
        "BusinessRefNumber": "HTSHA00001",
        "ProjectNumber": "5555",
        "OperationStaff": "刘风彩",
        "SalesStaff": "崔晓光",
        "CustomerServiceStaff": "戴翊雯",
        "DocumentStaff": "OP",
        "SolicitationType": "自揽货",
        "Status": "正操作",
        "ActualChargeableWeight": 20.0,
        "Profit": -92.0,
        "TotalRevenue": 116745.0,
        "TotalCost": 114820.0,
        "PayableReconciliationStatus": "未核销",
        "ReceivableReconciliationStatus": "未核销",
        "BusinessCreator": "徐伟力",
        "ContainerDescription": "1*20ST",
        "AppointedAgent": "COMM FORWARDING COMPANY",
        "MasterFreightTerms": "FREIGHT PREPAID",
        "SplitFreightTerms": "FREIGHT COLLECT",
        "TradeTerms": "CIF",
        "OperationMode": "一主一分",
        "CustomField1": "",
        "CustomField2": "",
        "CustomField3": "",
        "ProfitReviewStatus": "未审核",
        "RouteName": "美西",
        "RouteManager": "",
        "DestinationAgent": "COMM FORWARDING COMPANY",
        "CustomPosition1": "",
        "CustomPosition2": "",
        "PickupDeliveryLocation": "SHANGHAI",
        "TruckPickupTime": "2020-10-31",
        "BookingNumber": "ASHAYIN200595345",
        "SopStatus": "接单(未接单),订舱(pending),货物进仓(未入库),安排拖车(未派车),货物装箱(未装箱),报关单证(未收到),离港(未离港),提单(未制单),到港(未到港),已完结(),卸区(未确定)",
        "CancellationReviewReason": "",
        "ChargeLockTime": "2025-02-21 15:28:55",
        "PayableLockTime": "2025-02-21 15:28:55"
    },
    {
        "BusinessNumber":"SE2012001A",
        "ContainerType":"自拼箱",
        "BusinessType":"海运出口",
        "MasterNumber":"SE2012001A",
        "SplitNumber":"SE2012001A",
        "CustomerName":"上海大洋行有限公司",
        "CargoType":"普货",
        "CustomerLevel":"VIP客户",
        "ContractStatus":"合约失效",
        "CarrierName":"高丽海运株式会社",
        "VesselName":"MILD WALTZ",
        "VoyageFlight":"V.2104E",
        "LoadingPort":"SHANGHAI",
        "DestinationPort":"DELHI",
        "DeliveryPlace":"LOS ANGELES,CA",
        "DischargingPort":"LOS ANGELES,CA",
        "Etd":"2020-12-19",
        "Eta":"2021-02-10",
        "BusinessDate":"2020-12-19",
        "BookingAgent":"美国总统班轮公司",
        "CreationDate":"2020-12-10",
        "VoucherWord":"",
        "VoucherNumber":"0",
        "BusinessRefNumber":"HTSHA00001",
        "ProjectNumber":"5555",
        "OperationStaff":"刘风彩",
        "SalesStaff":"刘风彩",
        "CustomerServiceStaff":"戴翊雯",
        "DocumentStaff":"OP",
        "SolicitationType":"自揽货",
        "Status":"正操作",
        "ActualChargeableWeight":60.0,
        "Profit":-92.0,
        "TotalRevenue":116745.0,
        "TotalCost":114820.0,
        "PayableReconciliationStatus":"未核销",
        "ReceivableReconciliationStatus":"未核销",
        "BusinessCreator":"徐伟力",
        "ContainerDescription":"1*20ST",
        "AppointedAgent":"COMM FORWARDING COMPANY",
        "MasterFreightTerms":"FREIGHT PREPAID",
        "SplitFreightTerms":"FREIGHT COLLECT",
        "TradeTerms":"CIF",
        "OperationMode":"一主一分",
        "CustomField1":"",
        "CustomField2":"",
        "CustomField3":"",
        "ProfitReviewStatus":"未审核",
        "RouteName":"美西",
        "RouteManager":"",
        "DestinationAgent":"COMM FORWARDING COMPANY",
        "CustomPosition1":"",
        "CustomPosition2":"",
        "PickupDeliveryLocation":"SHANGHAI",
        "TruckPickupTime":"2020-10-31",
        "BookingNumber":"ASHAYIN200595345",
        "SopStatus":"接单(未接单),订舱(pending),货物进仓(未入库),安排拖车(未派车),货物装箱(未装箱),报关单证(未收到),离港(未离港),提单(未制单),到港(未到港),已完结(),卸区(未确定)",
        "CancellationReviewReason":"",
        "ChargeLockTime":"2025-02-21 15:28:55",
        "PayableLockTime":"2025-02-21 15:28:55"
      },
      {
        "BusinessNumber":"SE2011011",
        "ContainerType":"整箱",
        "BusinessType":"海运出口",
        "MasterNumber":"SE2011011",
        "SplitNumber":"SE2011011",
        "CustomerName":"上海合金",
        "CargoType":"普货",
        "CustomerLevel":"VIP客户",
        "ContractStatus":"未签约",
        "CarrierName":"高丽海运株式会社",
        "VesselName":"SM MUMBAI",
        "VoyageFlight":"2008E",
        "LoadingPort":"SHANGHAI",
        "DestinationPort":"DELHI",
        "DeliveryPlace":"TORONTO",
        "DischargingPort":"VANCOUVER,CANADA",
        "Etd":"2020-12-01",
        "Eta":"2021-02-10",
        "BusinessDate":"2020-12-01",
        "BookingAgent":"美国总统班轮公司",
        "CreationDate":"2020-11-25",
        "VoucherWord":"",
        "VoucherNumber":"0",
        "BusinessRefNumber":"1233",
        "ProjectNumber":"5555",
        "OperationStaff":"黄琪",
        "SalesStaff":"邵阳",
        "CustomerServiceStaff":"戴翊雯",
        "DocumentStaff":"OP",
        "SolicitationType":"自揽货",
        "Status":"正操作",
        "ActualChargeableWeight":0.0,
        "Profit":59.0,
        "TotalRevenue":260.0,
        "TotalCost":201.0,
        "PayableReconciliationStatus":"部分核销",
        "ReceivableReconciliationStatus":"未核销",
        "BusinessCreator":"胡总",
        "ContainerDescription":"1*40HC",
        "AppointedAgent":"COMM FORWARDING COMPANY",
        "MasterFreightTerms":"FREIGHT PREPAID",
        "SplitFreightTerms":"FREIGHT PREPAID",
        "TradeTerms":"CIF",
        "OperationMode":"一主一分",
        "CustomField1":"",
        "CustomField2":"",
        "CustomField3":"",
        "ProfitReviewStatus":"未审核",
        "RouteName":"加拿大",
        "RouteManager":"",
        "DestinationAgent":"COMM FORWARDING COMPANY",
        "CustomPosition1":"",
        "CustomPosition2":"",
        "PickupDeliveryLocation":"SHANGHAI",
        "TruckPickupTime":"2020-10-31",
        "BookingNumber":"ASHAYIN200595345",
        "SopStatus":"接单(未接单),订舱(pending),货物进仓(未入库),安排拖车(未派车),货物装箱(未装箱),报关单证(未收到),离港(未离港),提单(未制单),到港(未到港),已完结(),卸区(未确定)",
        "CancellationReviewReason":"",
        "ChargeLockTime":"2025-02-21 15:28:55",
        "PayableLockTime":"2025-02-21 15:28:55"
      },
      {
        "BusinessNumber":"SE2011010",
        "ContainerType":"整箱",
        "BusinessType":"海运出口",
        "MasterNumber":"SHCR0W797600",
        "SplitNumber":"SE2011010",
        "CustomerName":"上海合金",
        "CargoType":"普货",
        "CustomerLevel":"VIP客户",
        "ContractStatus":"未签约",
        "CarrierName":"高丽海运株式会社",
        "VesselName":"SM MUMBAI",
        "VoyageFlight":"2008E",
        "LoadingPort":"SHANGHAI",
        "DestinationPort":"DELHI",
        "DeliveryPlace":"TORONTO",
        "DischargingPort":"VANCOUVER,CANADA",
        "Etd":"2020-12-01",
        "Eta":"2021-02-10",
        "BusinessDate":"2020-12-01",
        "BookingAgent":"美国总统班轮公司",
        "CreationDate":"2020-11-25",
        "VoucherWord":"",
        "VoucherNumber":"0",
        "BusinessRefNumber":"1233",
        "ProjectNumber":"5555",
        "OperationStaff":"黄琪",
        "SalesStaff":"邵阳",
        "CustomerServiceStaff":"戴翊雯",
        "DocumentStaff":"OP",
        "SolicitationType":"自揽货",
        "Status":"正操作",
        "ActualChargeableWeight":0.0,
        "Profit":59.0,
        "TotalRevenue":260.0,
        "TotalCost":201.0,
        "PayableReconciliationStatus":"未核销",
        "ReceivableReconciliationStatus":"未核销",
        "BusinessCreator":"胡总",
        "ContainerDescription":"1*40HC",
        "AppointedAgent":"COMM FORWARDING COMPANY",
        "MasterFreightTerms":"FREIGHT PREPAID",
        "SplitFreightTerms":"FREIGHT PREPAID",
        "TradeTerms":"CIF",
        "OperationMode":"一主一分",
        "CustomField1":"",
        "CustomField2":"",
        "CustomField3":"",
        "ProfitReviewStatus":"未审核",
        "RouteName":"加拿大",
        "RouteManager":"",
        "DestinationAgent":"COMM FORWARDING COMPANY",
        "CustomPosition1":"",
        "CustomPosition2":"",
        "PickupDeliveryLocation":"SHANGHAI",
        "TruckPickupTime":"2020-10-31",
        "BookingNumber":"ASHAYIN200595345",
        "SopStatus":"接单(未接单),订舱(pending),货物进仓(未入库),安排拖车(未派车),货物装箱(未装箱),报关单证(未收到),离港(未离港),提单(未制单),到港(未到港),已完结(),卸区(未确定)",
        "CancellationReviewReason":"",
        "ChargeLockTime":"2025-02-21 15:28:55",
        "PayableLockTime":"2025-02-21 15:28:55"
      },
      {
        "BusinessNumber":"SE2011009",
        "ContainerType":"整箱",
        "BusinessType":"海运出口",
        "MasterNumber":"ASHAYIN200604654I",
        "SplitNumber":"SE2011009",
        "CustomerName":"上海合金",
        "CargoType":"普货",
        "CustomerLevel":"VIP客户",
        "ContractStatus":"未签约",
        "CarrierName":"高丽海运株式会社",
        "VesselName":"SM MUMBAI",
        "VoyageFlight":"2008E",
        "LoadingPort":"SHANGHAI",
        "DestinationPort":"DELHI",
        "DeliveryPlace":"TORONTO",
        "DischargingPort":"VANCOUVER,CANADA",
        "Etd":"2020-12-01",
        "Eta":"2021-02-10",
        "BusinessDate":"2020-12-01",
        "BookingAgent":"美国总统班轮公司",
        "CreationDate":"2020-11-25",
        "VoucherWord":"",
        "VoucherNumber":"0",
        "BusinessRefNumber":"1233",
        "ProjectNumber":"5555",
        "OperationStaff":"黄琪",
        "SalesStaff":"邵阳",
        "CustomerServiceStaff":"戴翊雯",
        "DocumentStaff":"OP",
        "SolicitationType":"自揽货",
        "Status":"正操作",
        "ActualChargeableWeight":0.0,
        "Profit":59.0,
        "TotalRevenue":260.0,
        "TotalCost":201.0,
        "PayableReconciliationStatus":"未核销",
        "ReceivableReconciliationStatus":"未核销",
        "BusinessCreator":"胡总",
        "ContainerDescription":"1*40HC",
        "AppointedAgent":"COMM FORWARDING COMPANY",
        "MasterFreightTerms":"FREIGHT PREPAID",
        "SplitFreightTerms":"FREIGHT PREPAID",
        "TradeTerms":"CIF",
        "OperationMode":"一主一分",
        "CustomField1":"",
        "CustomField2":"",
        "CustomField3":"",
        "ProfitReviewStatus":"未审核",
        "RouteName":"加拿大",
        "RouteManager":"",
        "DestinationAgent":"COMM FORWARDING COMPANY",
        "CustomPosition1":"",
        "CustomPosition2":"",
        "PickupDeliveryLocation":"SHANGHAI",
        "TruckPickupTime":"2020-10-31",
        "BookingNumber":"ASHAYIN200595345",
        "SopStatus":"接单(未接单),订舱(pending),货物进仓(未入库),安排拖车(未派车),货物装箱(未装箱),报关单证(未收到),离港(未离港),提单(未制单),到港(未到港),已完结(),卸区(未确定)",
        "CancellationReviewReason":"",
        "ChargeLockTime":"2025-02-21 15:28:55",
        "PayableLockTime":"2025-02-21 15:28:55"
      },
      {
        "BusinessNumber":"SE2011008",
        "ContainerType":"整箱",
        "BusinessType":"海运出口",
        "MasterNumber":"ASHAYIN200624814E",
        "SplitNumber":"SE2011008",
        "CustomerName":"上海合金",
        "CargoType":"普货",
        "CustomerLevel":"VIP客户",
        "ContractStatus":"未签约",
        "CarrierName":"高丽海运株式会社",
        "VesselName":"SM MUMBAI",
        "VoyageFlight":"2008E",
        "LoadingPort":"SHANGHAI",
        "DestinationPort":"DELHI",
        "DeliveryPlace":"TORONTO",
        "DischargingPort":"VANCOUVER,CANADA",
        "Etd":"2020-12-01",
        "Eta":"2021-02-10",
        "BusinessDate":"2020-12-01",
        "BookingAgent":"美国总统班轮公司",
        "CreationDate":"2020-11-25",
        "VoucherWord":"",
        "VoucherNumber":"0",
        "BusinessRefNumber":"1233",
        "ProjectNumber":"5555",
        "OperationStaff":"黄琪",
        "SalesStaff":"邵阳",
        "CustomerServiceStaff":"戴翊雯",
        "DocumentStaff":"OP",
        "SolicitationType":"自揽货",
        "Status":"正操作",
        "ActualChargeableWeight":0.0,
        "Profit":59.0,
        "TotalRevenue":260.0,
        "TotalCost":201.0,
        "PayableReconciliationStatus":"未核销",
        "ReceivableReconciliationStatus":"未核销",
        "BusinessCreator":"胡总",
        "ContainerDescription":"1*40HC",
        "AppointedAgent":"COMM FORWARDING COMPANY",
        "MasterFreightTerms":"FREIGHT PREPAID",
        "SplitFreightTerms":"FREIGHT PREPAID",
        "TradeTerms":"CIF",
        "OperationMode":"一主一分",
        "CustomField1":"",
        "CustomField2":"",
        "CustomField3":"",
        "ProfitReviewStatus":"未审核",
        "RouteName":"加拿大",
        "RouteManager":"",
        "DestinationAgent":"COMM FORWARDING COMPANY",
        "CustomPosition1":"",
        "CustomPosition2":"",
        "PickupDeliveryLocation":"SHANGHAI",
        "TruckPickupTime":"2020-10-31",
        "BookingNumber":"ASHAYIN200595345",
        "SopStatus":"接单(未接单),订舱(pending),货物进仓(未入库),安排拖车(未派车),货物装箱(未装箱),报关单证(未收到),离港(未离港),提单(未制单),到港(未到港),已完结(),卸区(未确定)",
        "CancellationReviewReason":"",
        "ChargeLockTime":"2025-02-21 15:28:55",
        "PayableLockTime":"2025-02-21 15:28:55"
      },
      {
        "BusinessNumber":"SE2011007",
        "ContainerType":"整箱",
        "BusinessType":"海运出口",
        "MasterNumber":"ASHAYIN200624814",
        "SplitNumber":"SE2011007",
        "CustomerName":"上海合金",
        "CargoType":"普货",
        "CustomerLevel":"VIP客户",
        "ContractStatus":"未签约",
        "CarrierName":"高丽海运株式会社",
        "VesselName":"SM MUMBAI",
        "VoyageFlight":"2008E",
        "LoadingPort":"SHANGHAI",
        "DestinationPort":"DELHI",
        "DeliveryPlace":"TORONTO",
        "DischargingPort":"VANCOUVER,CANADA",
        "Etd":"2020-12-01",
        "Eta":"2021-02-10",
        "BusinessDate":"2020-12-01",
        "BookingAgent":"美国总统班轮公司",
        "CreationDate":"2020-11-25",
        "VoucherWord":"",
        "VoucherNumber":"0",
        "BusinessRefNumber":"1233",
        "ProjectNumber":"5555",
        "OperationStaff":"黄琪",
        "SalesStaff":"邵阳",
        "CustomerServiceStaff":"戴翊雯",
        "DocumentStaff":"OP",
        "SolicitationType":"自揽货",
        "Status":"正操作",
        "ActualChargeableWeight":0.0,
        "Profit":-3.0,
        "TotalRevenue":198.0,
        "TotalCost":201.0,
        "PayableReconciliationStatus":"未核销",
        "ReceivableReconciliationStatus":"未核销",
        "BusinessCreator":"胡总",
        "ContainerDescription":"1*40HC",
        "AppointedAgent":"COMM FORWARDING COMPANY",
        "MasterFreightTerms":"FREIGHT PREPAID",
        "SplitFreightTerms":"FREIGHT PREPAID",
        "TradeTerms":"CIF",
        "OperationMode":"一主一分",
        "CustomField1":"",
        "CustomField2":"",
        "CustomField3":"",
        "ProfitReviewStatus":"未审核",
        "RouteName":"加拿大",
        "RouteManager":"",
        "DestinationAgent":"COMM FORWARDING COMPANY",
        "CustomPosition1":"",
        "CustomPosition2":"",
        "PickupDeliveryLocation":"SHANGHAI",
        "TruckPickupTime":"2020-10-31",
        "BookingNumber":"ASHAYIN200595345",
        "SopStatus":"接单(未接单),订舱(pending),货物进仓(未入库),安排拖车(未派车),货物装箱(未装箱),报关单证(未收到),离港(未离港),提单(未制单),到港(未到港),已完结(),卸区(未确定)",
        "CancellationReviewReason":"",
        "ChargeLockTime":"2025-02-21 15:28:55",
        "PayableLockTime":"2025-02-21 15:28:55"
      },
      {
        "BusinessNumber":"SE2011006",
        "ContainerType":"整箱",
        "BusinessType":"海运出口",
        "MasterNumber":"SHCR0W810600",
        "SplitNumber":"SE2011006",
        "CustomerName":"上海合金",
        "CargoType":"普货",
        "CustomerLevel":"VIP客户",
        "ContractStatus":"未签约",
        "CarrierName":"高丽海运株式会社",
        "VesselName":"SM MUMBAI",
        "VoyageFlight":"2008E",
        "LoadingPort":"SHANGHAI",
        "DestinationPort":"DELHI",
        "DeliveryPlace":"TORONTO",
        "DischargingPort":"VANCOUVER,CANADA",
        "Etd":"2020-12-01",
        "Eta":"2021-02-10",
        "BusinessDate":"2020-12-01",
        "BookingAgent":"美国总统班轮公司",
        "CreationDate":"2020-11-25",
        "VoucherWord":"",
        "VoucherNumber":"0",
        "BusinessRefNumber":"1233",
        "ProjectNumber":"5555",
        "OperationStaff":"黄琪",
        "SalesStaff":"邵阳",
        "CustomerServiceStaff":"戴翊雯",
        "DocumentStaff":"OP",
        "SolicitationType":"自揽货",
        "Status":"正操作",
        "ActualChargeableWeight":0.0,
        "Profit":-27.0,
        "TotalRevenue":114.0,
        "TotalCost":141.0,
        "PayableReconciliationStatus":"未核销",
        "ReceivableReconciliationStatus":"未核销",
        "BusinessCreator":"胡总",
        "ContainerDescription":"1*40HC",
        "AppointedAgent":"COMM FORWARDING COMPANY",
        "MasterFreightTerms":"FREIGHT PREPAID",
        "SplitFreightTerms":"FREIGHT PREPAID",
        "TradeTerms":"CIF",
        "OperationMode":"一主一分",
        "CustomField1":"",
        "CustomField2":"",
        "CustomField3":"",
        "ProfitReviewStatus":"未审核",
        "RouteName":"加拿大",
        "RouteManager":"",
        "DestinationAgent":"COMM FORWARDING COMPANY",
        "CustomPosition1":"",
        "CustomPosition2":"",
        "PickupDeliveryLocation":"SHANGHAI",
        "TruckPickupTime":"2020-10-31",
        "BookingNumber":"ASHAYIN200595345",
        "SopStatus":"接单(未接单),订舱(pending),货物进仓(未入库),安排拖车(未派车),货物装箱(未装箱),报关单证(未收到),离港(未离港),提单(未制单),到港(未到港),已完结(),卸区(未确定)",
        "CancellationReviewReason":"",
        "ChargeLockTime":"2025-02-21 15:28:55",
        "PayableLockTime":"2025-02-21 15:28:55"
      },
      {
        "BusinessNumber":"SE2011005",
        "ContainerType":"整箱",
        "BusinessType":"海运出口",
        "MasterNumber":"SHCR0W809700",
        "SplitNumber":"SE2011005",
        "CustomerName":"上海合金",
        "CargoType":"普货",
        "CustomerLevel":"VIP客户",
        "ContractStatus":"未签约",
        "CarrierName":"高丽海运株式会社",
        "VesselName":"SM MUMBAI",
        "VoyageFlight":"2008E",
        "LoadingPort":"SHANGHAI",
        "DestinationPort":"DELHI",
        "DeliveryPlace":"TORONTO",
        "DischargingPort":"VANCOUVER,CANADA",
        "Etd":"2020-12-01",
        "Eta":"2021-02-10",
        "BusinessDate":"2020-12-01",
        "BookingAgent":"美国总统班轮公司",
        "CreationDate":"2020-11-25",
        "VoucherWord":"",
        "VoucherNumber":"0",
        "BusinessRefNumber":"1233",
        "ProjectNumber":"5555",
        "OperationStaff":"黄琪",
        "SalesStaff":"邵阳",
        "CustomerServiceStaff":"戴翊雯",
        "DocumentStaff":"OP",
        "SolicitationType":"自揽货",
        "Status":"正操作",
        "ActualChargeableWeight":0.0,
        "Profit":-55.0,
        "TotalRevenue":66.0,
        "TotalCost":121.0,
        "PayableReconciliationStatus":"未核销",
        "ReceivableReconciliationStatus":"未核销",
        "BusinessCreator":"胡总",
        "ContainerDescription":"1*40HC",
        "AppointedAgent":"COMM FORWARDING COMPANY",
        "MasterFreightTerms":"FREIGHT PREPAID",
        "SplitFreightTerms":"FREIGHT PREPAID",
        "TradeTerms":"CIF",
        "OperationMode":"一主一分",
        "CustomField1":"",
        "CustomField2":"",
        "CustomField3":"",
        "ProfitReviewStatus":"未审核",
        "RouteName":"加拿大",
        "RouteManager":"",
        "DestinationAgent":"COMM FORWARDING COMPANY",
        "CustomPosition1":"",
        "CustomPosition2":"",
        "PickupDeliveryLocation":"SHANGHAI",
        "TruckPickupTime":"2020-10-31",
        "BookingNumber":"ASHAYIN200595345",
        "SopStatus":"接单(未接单),订舱(pending),货物进仓(未入库),安排拖车(未派车),货物装箱(未装箱),报关单证(未收到),离港(未离港),提单(未制单),到港(未到港),已完结(),卸区(未确定)",
        "CancellationReviewReason":"",
        "ChargeLockTime":"2025-02-21 15:28:55",
        "PayableLockTime":"2025-02-21 15:28:55"
      },
      {
        "BusinessNumber":"SE2011004",
        "ContainerType":"整箱",
        "BusinessType":"海运出口",
        "MasterNumber":"SHCR0W808600",
        "SplitNumber":"SE2011004",
        "CustomerName":"上海合金",
        "CargoType":"普货",
        "CustomerLevel":"VIP客户",
        "ContractStatus":"未签约",
        "CarrierName":"高丽海运株式会社",
        "VesselName":"SM MUMBAI",
        "VoyageFlight":"2008E",
        "LoadingPort":"SHANGHAI",
        "DestinationPort":"DELHI",
        "DeliveryPlace":"TORONTO",
        "DischargingPort":"VANCOUVER,CANADA",
        "Etd":"2020-12-01",
        "Eta":"2021-02-10",
        "BusinessDate":"2020-12-01",
        "BookingAgent":"美国总统班轮公司",
        "CreationDate":"2020-11-25",
        "VoucherWord":"",
        "VoucherNumber":"0",
        "BusinessRefNumber":"1233",
        "ProjectNumber":"5555",
        "OperationStaff":"黄琪",
        "SalesStaff":"邵阳",
        "CustomerServiceStaff":"戴翊雯",
        "DocumentStaff":"OP",
        "SolicitationType":"自揽货",
        "Status":"正操作",
        "ActualChargeableWeight":0.0,
        "Profit":-92.0,
        "TotalRevenue":18.0,
        "TotalCost":110.0,
        "PayableReconciliationStatus":"未核销",
        "ReceivableReconciliationStatus":"未核销",
        "BusinessCreator":"胡总",
        "ContainerDescription":"1*40HC",
        "AppointedAgent":"COMM FORWARDING COMPANY",
        "MasterFreightTerms":"FREIGHT PREPAID",
        "SplitFreightTerms":"FREIGHT PREPAID",
        "TradeTerms":"CIF",
        "OperationMode":"一主一分",
        "CustomField1":"",
        "CustomField2":"",
        "CustomField3":"",
        "ProfitReviewStatus":"未审核",
        "RouteName":"加拿大",
        "RouteManager":"",
        "DestinationAgent":"COMM FORWARDING COMPANY",
        "CustomPosition1":"",
        "CustomPosition2":"",
        "PickupDeliveryLocation":"SHANGHAI",
        "TruckPickupTime":"2020-10-31",
        "BookingNumber":"ASHAYIN200595345",
        "SopStatus":"接单(未接单),订舱(pending),货物进仓(未入库),安排拖车(未派车),货物装箱(未装箱),报关单证(未收到),离港(未离港),提单(未制单),到港(未到港),已完结(),卸区(未确定)",
        "CancellationReviewReason":"",
        "ChargeLockTime":"2025-02-21 15:28:55",
        "PayableLockTime":"2025-02-21 15:28:55"
      },
      {
        "BusinessNumber":"SE2011003",
        "ContainerType":"整箱",
        "BusinessType":"海运出口",
        "MasterNumber":"SHFO0D658100",
        "SplitNumber":"SE2011003",
        "CustomerName":"上海合金",
        "CargoType":"普货",
        "CustomerLevel":"VIP客户",
        "ContractStatus":"未签约",
        "CarrierName":"高丽海运株式会社",
        "VesselName":"SM MUMBAI",
        "VoyageFlight":"2008E",
        "LoadingPort":"SHANGHAI",
        "DestinationPort":"DELHI",
        "DeliveryPlace":"TORONTO",
        "DischargingPort":"VANCOUVER,CANADA",
        "Etd":"2020-12-01",
        "Eta":"2021-02-10",
        "BusinessDate":"2020-12-01",
        "BookingAgent":"美国总统班轮公司",
        "CreationDate":"2020-11-25",
        "VoucherWord":"",
        "VoucherNumber":"0",
        "BusinessRefNumber":"1233",
        "ProjectNumber":"5555",
        "OperationStaff":"黄琪",
        "SalesStaff":"邵阳",
        "CustomerServiceStaff":"戴翊雯",
        "DocumentStaff":"OP",
        "SolicitationType":"自揽货",
        "Status":"正操作",
        "ActualChargeableWeight":0.0,
        "Profit":-92.0,
        "TotalRevenue":18.0,
        "TotalCost":110.0,
        "PayableReconciliationStatus":"未核销",
        "ReceivableReconciliationStatus":"未核销",
        "BusinessCreator":"胡总",
        "ContainerDescription":"1*40HC",
        "AppointedAgent":"COMM FORWARDING COMPANY",
        "MasterFreightTerms":"FREIGHT PREPAID",
        "SplitFreightTerms":"FREIGHT PREPAID",
        "TradeTerms":"CIF",
        "OperationMode":"一主一分",
        "CustomField1":"",
        "CustomField2":"",
        "CustomField3":"",
        "ProfitReviewStatus":"未审核",
        "RouteName":"加拿大",
        "RouteManager":"",
        "DestinationAgent":"COMM FORWARDING COMPANY",
        "CustomPosition1":"",
        "CustomPosition2":"",
        "PickupDeliveryLocation":"SHANGHAI",
        "TruckPickupTime":"2020-10-31",
        "BookingNumber":"ASHAYIN200595345",
        "SopStatus":"接单(未接单),订舱(pending),货物进仓(未入库),安排拖车(未派车),货物装箱(未装箱),报关单证(未收到),离港(未离港),提单(未制单),到港(未到港),已完结(),卸区(未确定)",
        "CancellationReviewReason":"",
        "ChargeLockTime":"2025-02-21 15:28:55",
        "PayableLockTime":"2025-02-21 15:28:55"
      },
      {
        "BusinessNumber":"SE2011002",
        "ContainerType":"自拼箱",
        "BusinessType":"海运出口",
        "MasterNumber":"SHFO0D657700",
        "SplitNumber":"SE2011002",
        "CustomerName":"上海合金",
        "CargoType":"普货",
        "CustomerLevel":"VIP客户",
        "ContractStatus":"未签约",
        "CarrierName":"高丽海运株式会社",
        "VesselName":"SM MUMBAI",
        "VoyageFlight":"2008E",
        "LoadingPort":"SHANGHAI",
        "DestinationPort":"DELHI",
        "DeliveryPlace":"TORONTO",
        "DischargingPort":"VANCOUVER,CANADA",
        "Etd":"2020-12-01",
        "Eta":"2021-02-10",
        "BusinessDate":"2020-12-01",
        "BookingAgent":"美国总统班轮公司",
        "CreationDate":"2020-11-25",
        "VoucherWord":"",
        "VoucherNumber":"0",
        "BusinessRefNumber":"1233",
        "ProjectNumber":"5555",
        "OperationStaff":"黄琪",
        "SalesStaff":"邵阳",
        "CustomerServiceStaff":"戴翊雯",
        "DocumentStaff":"OP",
        "SolicitationType":"自揽货",
        "Status":"正操作",
        "ActualChargeableWeight":0.0,
        "Profit":-92.0,
        "TotalRevenue":18.0,
        "TotalCost":110.0,
        "PayableReconciliationStatus":"未核销",
        "ReceivableReconciliationStatus":"未核销",
        "BusinessCreator":"胡总",
        "ContainerDescription":"1*40HC",
        "AppointedAgent":"COMM FORWARDING COMPANY",
        "MasterFreightTerms":"FREIGHT PREPAID",
        "SplitFreightTerms":"FREIGHT PREPAID",
        "TradeTerms":"CIF",
        "OperationMode":"一主一分",
        "CustomField1":"",
        "CustomField2":"",
        "CustomField3":"",
        "ProfitReviewStatus":"未审核",
        "RouteName":"加拿大",
        "RouteManager":"",
        "DestinationAgent":"COMM FORWARDING COMPANY",
        "CustomPosition1":"",
        "CustomPosition2":"",
        "PickupDeliveryLocation":"SHANGHAI",
        "TruckPickupTime":"2020-10-31",
        "BookingNumber":"ASHAYIN200595345",
        "SopStatus":"接单(未接单),订舱(pending),货物进仓(未入库),安排拖车(未派车),货物装箱(未装箱),报关单证(未收到),离港(未离港),提单(未制单),到港(未到港),已完结(),卸区(未确定)",
        "CancellationReviewReason":"",
        "ChargeLockTime":"2025-02-21 15:28:55",
        "PayableLockTime":"2025-02-21 15:28:55"
      },
      {
        "BusinessNumber":"SHSI200010001",
        "ContainerType":"整箱",
        "BusinessType":"海运进口",
        "MasterNumber":"1155225",
        "SplitNumber":"SE2011002",
        "CustomerName":"浙江森诺进出口有限公司",
        "CargoType":"普货",
        "CustomerLevel":"VIP客户",
        "ContractStatus":"未签约",
        "CarrierName":"高丽海运株式会社",
        "VesselName":"SM MUMBAI",
        "VoyageFlight":"2008E",
        "LoadingPort":"LOS ANGELES,CA",
        "DestinationPort":"DELHI",
        "DeliveryPlace":"SHANGHAI",
        "DischargingPort":"SHANGHAI",
        "Etd":"2020-10-01",
        "Eta":"2020-10-15",
        "BusinessDate":"2020-10-15",
        "BookingAgent":"美国总统班轮公司",
        "CreationDate":"2020-11-17",
        "VoucherWord":"",
        "VoucherNumber":"0",
        "BusinessRefNumber":"1233",
        "ProjectNumber":"5555",
        "OperationStaff":"黄琪",
        "SalesStaff":"刘风彩",
        "CustomerServiceStaff":"戴翊雯",
        "DocumentStaff":"OP",
        "SolicitationType":"自揽货",
        "Status":"正操作",
        "ActualChargeableWeight":460.0,
        "Profit":0.0,
        "TotalRevenue":18.0,
        "TotalCost":110.0,
        "PayableReconciliationStatus":"无应付",
        "ReceivableReconciliationStatus":"无应收",
        "BusinessCreator":"范晓玲",
        "ContainerDescription":"10*40GP",
        "AppointedAgent":"COMM FORWARDING COMPANY",
        "MasterFreightTerms":"FREIGHT PREPAID",
        "SplitFreightTerms":"FREIGHT PREPAID",
        "TradeTerms":"CIF",
        "OperationMode":"一主一分",
        "CustomField1":"",
        "CustomField2":"",
        "CustomField3":"",
        "ProfitReviewStatus":"未审核",
        "RouteName":"东南亚",
        "RouteManager":"",
        "DestinationAgent":"COMM FORWARDING COMPANY",
        "CustomPosition1":"",
        "CustomPosition2":"",
        "PickupDeliveryLocation":"SHANGHAI",
        "TruckPickupTime":"2020-10-31",
        "BookingNumber":"ASHAYIN200595345",
        "SopStatus":"订舱(已订舱 2020-11-17 11:12:05),配船(Y),离港(Y),到港(Y),换单(Y),提箱(Y),报关(Y),送货(Y)",
        "CancellationReviewReason":"",
        "ChargeLockTime":"2025-02-21 15:28:55",
        "PayableLockTime":"2025-02-21 15:28:55"
      },
      {
        "BusinessNumber":"SHSI200009001",
        "ContainerType":"整箱",
        "BusinessType":"海运进口",
        "MasterNumber":"5485495",
        "SplitNumber":"SE2011002",
        "CustomerName":"浙江森诺进出口有限公司",
        "CargoType":"普货",
        "CustomerLevel":"VIP客户",
        "ContractStatus":"未签约",
        "CarrierName":"高丽海运株式会社",
        "VesselName":"SM MUMBAI",
        "VoyageFlight":"2008E",
        "LoadingPort":"CAGAYAN",
        "DestinationPort":"DELHI",
        "DeliveryPlace":"SHANGHAI",
        "DischargingPort":"SHANGHAI",
        "Etd":"2020-08-12",
        "Eta":"2020-10-29",
        "BusinessDate":"2020-10-29",
        "BookingAgent":"上海联合国际船舶代理有限公司",
        "CreationDate":"2020-11-12",
        "VoucherWord":"",
        "VoucherNumber":"0",
        "BusinessRefNumber":"1233",
        "ProjectNumber":"5555",
        "OperationStaff":"黄琪",
        "SalesStaff":"崔晓光",
        "CustomerServiceStaff":"戴翊雯",
        "DocumentStaff":"OP",
        "SolicitationType":"自揽货",
        "Status":"正操作",
        "ActualChargeableWeight":66.0,
        "Profit":11100.0,
        "TotalRevenue":25000.0,
        "TotalCost":13900.0,
        "PayableReconciliationStatus":"未核销",
        "ReceivableReconciliationStatus":"未核销",
        "BusinessCreator":"范晓玲",
        "ContainerDescription":"5*40HC",
        "AppointedAgent":"COMM FORWARDING COMPANY",
        "MasterFreightTerms":"FREIGHT PREPAID",
        "SplitFreightTerms":"FREIGHT PREPAID",
        "TradeTerms":"CIF",
        "OperationMode":"一主一分",
        "CustomField1":"",
        "CustomField2":"",
        "CustomField3":"",
        "ProfitReviewStatus":"未审核",
        "RouteName":"东南亚",
        "RouteManager":"",
        "DestinationAgent":"COMM FORWARDING COMPANY",
        "CustomPosition1":"",
        "CustomPosition2":"",
        "PickupDeliveryLocation":"SHANGHAI",
        "TruckPickupTime":"2020-10-31",
        "BookingNumber":"ASHAYIN200595345",
        "SopStatus":"订舱(未订舱),配船(Y),离港(Y),到港(Y),换单(Y),提箱(Y),报关(Y),送货(Y)",
        "CancellationReviewReason":"",
        "ChargeLockTime":"2025-02-21 15:28:55",
        "PayableLockTime":"2025-02-21 15:28:55"
      },
      {
        "BusinessNumber":"SHSI200008001",
        "ContainerType":"整箱",
        "BusinessType":"海运进口",
        "MasterNumber":"111234433",
        "SplitNumber":"SE2011002",
        "CustomerName":"浙江森诺进出口有限公司",
        "CargoType":"普货",
        "CustomerLevel":"VIP客户",
        "ContractStatus":"未签约",
        "CarrierName":"高丽海运株式会社",
        "VesselName":"MCC SHSDHSH",
        "VoyageFlight":"E016",
        "LoadingPort":"CAGAYAN",
        "DestinationPort":"DELHI",
        "DeliveryPlace":"SHANGHAI",
        "DischargingPort":"SHANGHAI",
        "Etd":"2020-08-05",
        "Eta":"2020-10-20",
        "BusinessDate":"2020-10-20",
        "BookingAgent":"上海联合国际船舶代理有限公司",
        "CreationDate":"2020-11-12",
        "VoucherWord":"",
        "VoucherNumber":"0",
        "BusinessRefNumber":"1233",
        "ProjectNumber":"5555",
        "OperationStaff":"黄琪",
        "SalesStaff":"崔晓光",
        "CustomerServiceStaff":"戴翊雯",
        "DocumentStaff":"OP",
        "SolicitationType":"自揽货",
        "Status":"正操作",
        "ActualChargeableWeight":122.222,
        "Profit":22900.0,
        "TotalRevenue":50000.0,
        "TotalCost":27100.0,
        "PayableReconciliationStatus":"未核销",
        "ReceivableReconciliationStatus":"未核销",
        "BusinessCreator":"范晓玲",
        "ContainerDescription":"10*40HC",
        "AppointedAgent":"COMM FORWARDING COMPANY",
        "MasterFreightTerms":"FREIGHT PREPAID",
        "SplitFreightTerms":"FREIGHT PREPAID",
        "TradeTerms":"CIF",
        "OperationMode":"一主一分",
        "CustomField1":"",
        "CustomField2":"",
        "CustomField3":"",
        "ProfitReviewStatus":"未审核",
        "RouteName":"东南亚",
        "RouteManager":"",
        "DestinationAgent":"COMM FORWARDING COMPANY",
        "CustomPosition1":"",
        "CustomPosition2":"",
        "PickupDeliveryLocation":"SHANGHAI",
        "TruckPickupTime":"2020-10-31",
        "BookingNumber":"ASHAYIN200595345",
        "SopStatus":"订舱(未订舱),配船(Y),离港(Y),到港(Y),换单(Y),提箱(Y),报关(Y),送货(Y)",
        "CancellationReviewReason":"",
        "ChargeLockTime":"2025-02-21 15:28:55",
        "PayableLockTime":"2025-02-21 15:28:55"
      },
      {
        "BusinessNumber":"SE2011001",
        "ContainerType":"委托拼箱",
        "BusinessType":"海运出口",
        "MasterNumber":"111234433",
        "SplitNumber":"SE2011001",
        "CustomerName":"苏州永翔五金塑胶有限公司",
        "CargoType":"普货",
        "CustomerLevel":"VIP客户",
        "ContractStatus":"未签约",
        "CarrierName":"高丽海运株式会社",
        "VesselName":"MCC SHSDHSH",
        "VoyageFlight":"E016",
        "LoadingPort":"SHANGHAI",
        "DestinationPort":"DELHI",
        "DeliveryPlace":"OSAKA",
        "DischargingPort":"OSAKA",
        "Etd":"2020-11-24",
        "Eta":"2020-10-20",
        "BusinessDate":"2020-11-24",
        "BookingAgent":"上海联合国际船舶代理有限公司",
        "CreationDate":"2020-11-11",
        "VoucherWord":"",
        "VoucherNumber":"0",
        "BusinessRefNumber":"1233",
        "ProjectNumber":"5555",
        "OperationStaff":"黄琪",
        "SalesStaff":"崔晓光",
        "CustomerServiceStaff":"戴翊雯",
        "DocumentStaff":"OP",
        "SolicitationType":"自揽货",
        "Status":"正操作",
        "ActualChargeableWeight":6.0,
        "Profit":0.0,
        "TotalRevenue":50000.0,
        "TotalCost":27100.0,
        "PayableReconciliationStatus":"无应付",
        "ReceivableReconciliationStatus":"无应收",
        "BusinessCreator":"刘小芳",
        "ContainerDescription":"10*40HC",
        "AppointedAgent":"COMM FORWARDING COMPANY",
        "MasterFreightTerms":"FREIGHT PREPAID",
        "SplitFreightTerms":"FREIGHT PREPAID",
        "TradeTerms":"CIF",
        "OperationMode":"一主一分",
        "CustomField1":"",
        "CustomField2":"",
        "CustomField3":"",
        "ProfitReviewStatus":"未审核",
        "RouteName":"东南亚",
        "RouteManager":"",
        "DestinationAgent":"COMM FORWARDING COMPANY",
        "CustomPosition1":"",
        "CustomPosition2":"",
        "PickupDeliveryLocation":"SHANGHAI",
        "TruckPickupTime":"2020-10-31",
        "BookingNumber":"ASHAYIN200595345",
        "SopStatus":"接单(未接单),订舱(pending),货物进仓(未入库),安排拖车(未派车),货物装箱(未装箱),报关单证(未收到),离港(未离港),提单(未制单),到港(未到港),已完结(),卸区(未确定)",
        "CancellationReviewReason":"",
        "ChargeLockTime":"2025-02-21 15:28:55",
        "PayableLockTime":"2025-02-21 15:28:55"
      },
      {
        "BusinessNumber":"SHSI200007",
        "ContainerType":"整箱",
        "BusinessType":"海运进口",
        "MasterNumber":"111234433",
        "SplitNumber":"2432543543",
        "CustomerName":"abc",
        "CargoType":"普货",
        "CustomerLevel":"VIP客户",
        "ContractStatus":"未签约",
        "CarrierName":"以星综合航运(中国)有限公司",
        "VesselName":"MCC SHSDHSH",
        "VoyageFlight":"E016",
        "LoadingPort":"YANTIAN",
        "DestinationPort":"DELHI",
        "DeliveryPlace":"AL KOMS",
        "DischargingPort":"AL KOMS",
        "Etd":"2020-11-03",
        "Eta":"2020-11-24",
        "BusinessDate":"2020-11-24",
        "BookingAgent":"上海联合国际船舶代理有限公司",
        "CreationDate":"2020-11-03",
        "VoucherWord":"",
        "VoucherNumber":"0",
        "BusinessRefNumber":"1233",
        "ProjectNumber":"5555",
        "OperationStaff":"黄琪",
        "SalesStaff":"刘风彩",
        "CustomerServiceStaff":"jason",
        "DocumentStaff":"OP",
        "SolicitationType":"自揽货",
        "Status":"正操作",
        "ActualChargeableWeight":72.0,
        "Profit":0.0,
        "TotalRevenue":50000.0,
        "TotalCost":27100.0,
        "PayableReconciliationStatus":"无应付",
        "ReceivableReconciliationStatus":"无应收",
        "BusinessCreator":"jason",
        "ContainerDescription":"10*40HC",
        "AppointedAgent":"COMM FORWARDING COMPANY",
        "MasterFreightTerms":"FREIGHT PREPAID",
        "SplitFreightTerms":"FREIGHT PREPAID",
        "TradeTerms":"DDP",
        "OperationMode":"一主一分",
        "CustomField1":"",
        "CustomField2":"",
        "CustomField3":"",
        "ProfitReviewStatus":"未审核",
        "RouteName":"东南亚",
        "RouteManager":"",
        "DestinationAgent":"COMM FORWARDING COMPANY",
        "CustomPosition1":"",
        "CustomPosition2":"",
        "PickupDeliveryLocation":"SZ",
        "TruckPickupTime":"2020-10-31",
        "BookingNumber":"ASHAYIN200595345",
        "SopStatus":"订舱(未订舱),配船(Y),离港(Y),到港(Y),换单(Y),提箱(Y),报关(Y),送货(Y)",
        "CancellationReviewReason":"",
        "ChargeLockTime":"2025-02-21 15:28:55",
        "PayableLockTime":"2025-02-21 15:28:55"
      },
      {
        "BusinessNumber":"SE2010003",
        "ContainerType":"整箱",
        "BusinessType":"海运出口",
        "MasterNumber":"111234433",
        "SplitNumber":"SE2010003",
        "CustomerName":"浙江永晟物流有限公司",
        "CargoType":"普货",
        "CustomerLevel":"VIP客户",
        "ContractStatus":"未签约",
        "CarrierName":"以星综合航运(中国)有限公司",
        "VesselName":"OOCL WASHINGTON",
        "VoyageFlight":"V.060W",
        "LoadingPort":"SHANGHAI",
        "DestinationPort":"DELHI",
        "DeliveryPlace":"NHAVA SHEVA",
        "DischargingPort":"NHAVA SHEVA",
        "Etd":"2020-10-31",
        "Eta":"2020-11-24",
        "BusinessDate":"2020-10-31",
        "BookingAgent":"上海联合国际船舶代理有限公司",
        "CreationDate":"2020-10-28",
        "VoucherWord":"",
        "VoucherNumber":"0",
        "BusinessRefNumber":"1233",
        "ProjectNumber":"5555",
        "OperationStaff":"邵阳",
        "SalesStaff":"许洋",
        "CustomerServiceStaff":"刘风彩",
        "DocumentStaff":"邵阳",
        "SolicitationType":"自揽货",
        "Status":"正操作",
        "ActualChargeableWeight":3.81,
        "Profit":0.0,
        "TotalRevenue":50000.0,
        "TotalCost":27100.0,
        "PayableReconciliationStatus":"无应付",
        "ReceivableReconciliationStatus":"无应收",
        "BusinessCreator":"吴建美",
        "ContainerDescription":"1*20GP",
        "AppointedAgent":"COMM FORWARDING COMPANY",
        "MasterFreightTerms":"FREIGHT PREPAID",
        "SplitFreightTerms":"FREIGHT COLLECT",
        "TradeTerms":"CIF",
        "OperationMode":"一主一分",
        "CustomField1":"",
        "CustomField2":"",
        "CustomField3":"",
        "ProfitReviewStatus":"未审核",
        "RouteName":"印巴",
        "RouteManager":"",
        "DestinationAgent":"COMM FORWARDING COMPANY",
        "CustomPosition1":"",
        "CustomPosition2":"",
        "PickupDeliveryLocation":"SZ",
        "TruckPickupTime":"2020-10-31",
        "BookingNumber":"ASHAYIN200595345",
        "SopStatus":"接单(未接单),订舱(pending),货物进仓(未入库),安排拖车(未派车),货物装箱(未装箱),报关单证(未收到),离港(未离港),提单(未制单),到港(未到港),已完结(),卸区(未确定)",
        "CancellationReviewReason":"",
        "ChargeLockTime":"2025-02-21 15:28:55",
        "PayableLockTime":"2025-02-21 15:28:55"
      },
      {
        "BusinessNumber":"SE2010002",
        "ContainerType":"整箱",
        "BusinessType":"海运出口",
        "MasterNumber":"111234433",
        "SplitNumber":"SE2010002",
        "CustomerName":"浙江永晟物流有限公司",
        "CargoType":"普货",
        "CustomerLevel":"VIP客户",
        "ContractStatus":"未签约",
        "CarrierName":"以星综合航运(中国)有限公司",
        "VesselName":"OOCL WASHINGTON",
        "VoyageFlight":"V.060W",
        "LoadingPort":"SHANGHAI",
        "DestinationPort":"DELHI",
        "DeliveryPlace":"NHAVA SHEVA",
        "DischargingPort":"NHAVA SHEVA",
        "Etd":"2020-10-28",
        "Eta":"2020-11-24",
        "BusinessDate":"2020-10-28",
        "BookingAgent":"上海联合国际船舶代理有限公司",
        "CreationDate":"2020-10-28",
        "VoucherWord":"",
        "VoucherNumber":"0",
        "BusinessRefNumber":"1233",
        "ProjectNumber":"5555",
        "OperationStaff":"刘风彩",
        "SalesStaff":"许洋",
        "CustomerServiceStaff":"刘风彩",
        "DocumentStaff":"邵阳",
        "SolicitationType":"自揽货",
        "Status":"正操作",
        "ActualChargeableWeight":3.81,
        "Profit":0.0,
        "TotalRevenue":50000.0,
        "TotalCost":27100.0,
        "PayableReconciliationStatus":"无应付",
        "ReceivableReconciliationStatus":"无应收",
        "BusinessCreator":"吴建美",
        "ContainerDescription":"1*20GP",
        "AppointedAgent":"COMM FORWARDING COMPANY",
        "MasterFreightTerms":"FREIGHT PREPAID",
        "SplitFreightTerms":"FREIGHT PREPAID",
        "TradeTerms":"CIF",
        "OperationMode":"一主一分",
        "CustomField1":"",
        "CustomField2":"",
        "CustomField3":"",
        "ProfitReviewStatus":"未审核",
        "RouteName":"印巴",
        "RouteManager":"",
        "DestinationAgent":"COMM FORWARDING COMPANY",
        "CustomPosition1":"",
        "CustomPosition2":"",
        "PickupDeliveryLocation":"SZ",
        "TruckPickupTime":"2020-10-31",
        "BookingNumber":"ASHAYIN200595345",
        "SopStatus":"接单(未接单),订舱(pending),货物进仓(未入库),安排拖车(未派车),货物装箱(未装箱),报关单证(未收到),离港(未离港),提单(未制单),到港(未到港),已完结(),卸区(未确定)",
        "CancellationReviewReason":"",
        "ChargeLockTime":"2025-02-21 15:28:55",
        "PayableLockTime":"2025-02-21 15:28:55"
      },
      {
        "BusinessNumber":"SE2010001",
        "ContainerType":"整箱",
        "BusinessType":"海运出口",
        "MasterNumber":"SZPAH0927907",
        "SplitNumber":"SE2010001",
        "CustomerName":"上海沃行信息技术有限公司",
        "CargoType":"普货",
        "CustomerLevel":"VIP客户",
        "ContractStatus":"合约失效",
        "CarrierName":"以星综合航运(中国)有限公司",
        "VesselName":"YM WONDROUS",
        "VoyageFlight":"V.029W",
        "LoadingPort":"SHEKOU",
        "DestinationPort":"DELHI",
        "DeliveryPlace":"ASHDOD",
        "DischargingPort":"ASHDOD",
        "Etd":"2020-10-20",
        "Eta":"2020-11-24",
        "BusinessDate":"2020-10-20",
        "BookingAgent":"上海联合国际船舶代理有限公司",
        "CreationDate":"2020-10-12",
        "VoucherWord":"",
        "VoucherNumber":"0",
        "BusinessRefNumber":"1233",
        "ProjectNumber":"5555",
        "OperationStaff":"黄琪",
        "SalesStaff":"刘风彩",
        "CustomerServiceStaff":"刘风彩",
        "DocumentStaff":"邵阳",
        "SolicitationType":"自揽货",
        "Status":"正操作",
        "ActualChargeableWeight":68.0,
        "Profit":0.0,
        "TotalRevenue":50000.0,
        "TotalCost":27100.0,
        "PayableReconciliationStatus":"无应付",
        "ReceivableReconciliationStatus":"无应收",
        "BusinessCreator":"王先生",
        "ContainerDescription":"1*40HC",
        "AppointedAgent":"COMM FORWARDING COMPANY",
        "MasterFreightTerms":"FREIGHT PREPAID",
        "SplitFreightTerms":"FREIGHT PREPAID",
        "TradeTerms":"FOB",
        "OperationMode":"一主一分",
        "CustomField1":"",
        "CustomField2":"",
        "CustomField3":"",
        "ProfitReviewStatus":"未审核",
        "RouteName":"地中海",
        "RouteManager":"",
        "DestinationAgent":"COMM FORWARDING COMPANY",
        "CustomPosition1":"",
        "CustomPosition2":"",
        "PickupDeliveryLocation":"SZ",
        "TruckPickupTime":"2020-10-31",
        "BookingNumber":"ASHAYIN200595345",
        "SopStatus":"接单(未接单),订舱(pending),货物进仓(未入库),安排拖车(未派车),货物装箱(未装箱),报关单证(未收到),离港(未离港),提单(未制单),到港(未到港),已完结(),卸区(未确定)",
        "CancellationReviewReason":"",
        "ChargeLockTime":"2025-02-21 15:28:55",
        "PayableLockTime":"2025-02-21 15:28:55"
      },
      {
        "BusinessNumber":"SHSI200008001AKI",
        "ContainerType":"整箱",
        "BusinessType":"海运进口",
        "MasterNumber":"SZPAH0927907",
        "SplitNumber":"SE2010001",
        "CustomerName":"客户1",
        "CargoType":"普货",
        "CustomerLevel":"普通客户",
        "ContractStatus":"未签约",
        "CarrierName":"以星综合航运(中国)有限公司",
        "VesselName":"YM WONDROUS",
        "VoyageFlight":"V.029W",
        "LoadingPort":"AKITA",
        "DestinationPort":"DELHI",
        "DeliveryPlace":"SHENZHEN",
        "DischargingPort":"SHENZHEN",
        "Etd":"2020-09-24",
        "Eta":"2020-10-08",
        "BusinessDate":"2020-10-08",
        "BookingAgent":"上海联合国际船舶代理有限公司",
        "CreationDate":"2020-09-23",
        "VoucherWord":"",
        "VoucherNumber":"0",
        "BusinessRefNumber":"1233",
        "ProjectNumber":"5555",
        "OperationStaff":"黄琪",
        "SalesStaff":"刘风彩",
        "CustomerServiceStaff":"黄琪",
        "DocumentStaff":"邵阳",
        "SolicitationType":"自揽货",
        "Status":"正操作",
        "ActualChargeableWeight":675.0,
        "Profit":2900.0,
        "TotalRevenue":13800.0,
        "TotalCost":10900.0,
        "PayableReconciliationStatus":"未核销",
        "ReceivableReconciliationStatus":"未核销",
        "BusinessCreator":"王先生",
        "ContainerDescription":"1*20GP",
        "AppointedAgent":"COMM FORWARDING COMPANY",
        "MasterFreightTerms":"FREIGHT PREPAID",
        "SplitFreightTerms":"FREIGHT PREPAID",
        "TradeTerms":"FOB",
        "OperationMode":"一主一分",
        "CustomField1":"",
        "CustomField2":"",
        "CustomField3":"",
        "ProfitReviewStatus":"未审核",
        "RouteName":"东南亚",
        "RouteManager":"",
        "DestinationAgent":"COMM FORWARDING COMPANY",
        "CustomPosition1":"",
        "CustomPosition2":"",
        "PickupDeliveryLocation":"SZ",
        "TruckPickupTime":"2020-10-31",
        "BookingNumber":"ASHAYIN200595345",
        "SopStatus":"订舱(未订舱),配船(Y),离港(Y),到港(Y),换单(Y),提箱(Y),报关(Y),送货(Y)",
        "CancellationReviewReason":"",
        "ChargeLockTime":"2025-02-21 15:28:55",
        "PayableLockTime":"2025-02-21 15:28:55"
      },
      {
        "BusinessNumber":"SE2009004",
        "ContainerType":"整箱",
        "BusinessType":"海运出口",
        "MasterNumber":"SZPAH0927907",
        "SplitNumber":"SE2009004",
        "CustomerName":"上海苍鹭实业有限公司",
        "CargoType":"普货",
        "CustomerLevel":"普通客户",
        "ContractStatus":"未签约",
        "CarrierName":"上海联合国际船舶代理有限公司",
        "VesselName":"XINDE KEELUNG",
        "VoyageFlight":"V.1926S",
        "LoadingPort":"XINGANG",
        "DestinationPort":"DELHI",
        "DeliveryPlace":"KAOHSIUNG",
        "DischargingPort":"KAOHSIUNG",
        "Etd":"2020-10-12",
        "Eta":"2020-10-08",
        "BusinessDate":"2020-10-12",
        "BookingAgent":"上海联合国际船舶代理有限公司",
        "CreationDate":"2020-09-21",
        "VoucherWord":"",
        "VoucherNumber":"0",
        "BusinessRefNumber":"1233",
        "ProjectNumber":"5555",
        "OperationStaff":"刘风彩",
        "SalesStaff":"甘以星",
        "CustomerServiceStaff":"黄琪",
        "DocumentStaff":"邵阳",
        "SolicitationType":"自揽货",
        "Status":"正操作",
        "ActualChargeableWeight":67.5,
        "Profit":34200.0,
        "TotalRevenue":41000.0,
        "TotalCost":6800.0,
        "PayableReconciliationStatus":"未核销",
        "ReceivableReconciliationStatus":"未核销",
        "BusinessCreator":"王先生",
        "ContainerDescription":"1*40TK",
        "AppointedAgent":"COMM FORWARDING COMPANY",
        "MasterFreightTerms":"FREIGHT PREPAID",
        "SplitFreightTerms":"FREIGHT PREPAID",
        "TradeTerms":"CIF",
        "OperationMode":"一主一分",
        "CustomField1":"",
        "CustomField2":"",
        "CustomField3":"",
        "ProfitReviewStatus":"未审核",
        "RouteName":"东南亚",
        "RouteManager":"",
        "DestinationAgent":"天津京滨报关行",
        "CustomPosition1":"",
        "CustomPosition2":"",
        "PickupDeliveryLocation":"SZ",
        "TruckPickupTime":"2020-10-31",
        "BookingNumber":"ASHAYIN200595345",
        "SopStatus":"接单(未接单),订舱(pending),货物进仓(未入库),安排拖车(未派车),货物装箱(未装箱),报关单证(未收到),离港(已离港 2020-07-26 09:00:00),提单(未制单),到港(未到港),已完结(),卸区(未确定)",
        "CancellationReviewReason":"",
        "ChargeLockTime":"2025-02-21 15:28:55",
        "PayableLockTime":"2025-02-21 15:28:55"
      },
      {
        "BusinessNumber":"AFS2009003",
        "ContainerType":"整箱",
        "BusinessType":"海运出口",
        "MasterNumber":"SZPAH0927907",
        "SplitNumber":"AFS2009003",
        "CustomerName":"上海世邦",
        "CargoType":"普货",
        "CustomerLevel":"普通客户",
        "ContractStatus":"合约失效",
        "CarrierName":"阳明海运集团",
        "VesselName":"XINDE KEELUNG",
        "VoyageFlight":"V.1926S",
        "LoadingPort":"SHANGHAI",
        "DestinationPort":"DELHI",
        "DeliveryPlace":"COLOMBO",
        "DischargingPort":"COLOMBO",
        "Etd":"2020-09-28",
        "Eta":"2020-10-08",
        "BusinessDate":"2020-09-28",
        "BookingAgent":"上海联合国际船舶代理有限公司",
        "CreationDate":"2020-09-19",
        "VoucherWord":"",
        "VoucherNumber":"0",
        "BusinessRefNumber":"HTSHA20091001",
        "ProjectNumber":"5555",
        "OperationStaff":"刘风彩",
        "SalesStaff":"刘风彩",
        "CustomerServiceStaff":"黄琪",
        "DocumentStaff":"邵阳",
        "SolicitationType":"自揽货",
        "Status":"正操作",
        "ActualChargeableWeight":0.0,
        "Profit":0.0,
        "TotalRevenue":41000.0,
        "TotalCost":6800.0,
        "PayableReconciliationStatus":"无应付",
        "ReceivableReconciliationStatus":"无应收",
        "BusinessCreator":"李先生",
        "ContainerDescription":"1*40HC",
        "AppointedAgent":"COMM FORWARDING COMPANY",
        "MasterFreightTerms":"FREIGHT PREPAID",
        "SplitFreightTerms":"FREIGHT PREPAID",
        "TradeTerms":"CIF",
        "OperationMode":"一主一分",
        "CustomField1":"",
        "CustomField2":"",
        "CustomField3":"",
        "ProfitReviewStatus":"未审核",
        "RouteName":"印巴",
        "RouteManager":"",
        "DestinationAgent":"天津京滨报关行",
        "CustomPosition1":"",
        "CustomPosition2":"",
        "PickupDeliveryLocation":"SZ",
        "TruckPickupTime":"2020-10-31",
        "BookingNumber":"ASHAYIN200595345",
        "SopStatus":"接单(未接单),订舱(pending),货物进仓(未入库),安排拖车(未派车),货物装箱(未装箱),报关单证(未收到),离港(未离港),提单(未制单),到港(未到港),已完结(),卸区(未确定)",
        "CancellationReviewReason":"",
        "ChargeLockTime":"2025-02-21 15:28:55",
        "PayableLockTime":"2025-02-21 15:28:55"
      },
      {
        "BusinessNumber":"SHSI200007AKI",
        "ContainerType":"整箱",
        "BusinessType":"海运进口",
        "MasterNumber":"SZPAH0927907",
        "SplitNumber":"AFS2009003",
        "CustomerName":"客户1",
        "CargoType":"普货",
        "CustomerLevel":"普通客户",
        "ContractStatus":"未签约",
        "CarrierName":"阳明海运集团",
        "VesselName":"XINDE KEELUNG",
        "VoyageFlight":"V.1926S",
        "LoadingPort":"AKITA",
        "DestinationPort":"DELHI",
        "DeliveryPlace":"SHENZHEN",
        "DischargingPort":"SHENZHEN",
        "Etd":"2020-09-01",
        "Eta":"2020-09-11",
        "BusinessDate":"2020-09-11",
        "BookingAgent":"上海联合国际船舶代理有限公司",
        "CreationDate":"2020-09-12",
        "VoucherWord":"",
        "VoucherNumber":"0",
        "BusinessRefNumber":"12312",
        "ProjectNumber":"1111111",
        "OperationStaff":"刘风彩",
        "SalesStaff":"刘风彩",
        "CustomerServiceStaff":"姚杰",
        "DocumentStaff":"邵阳",
        "SolicitationType":"自揽货",
        "Status":"正操作",
        "ActualChargeableWeight":675.0,
        "Profit":400.0,
        "TotalRevenue":2500.0,
        "TotalCost":2100.0,
        "PayableReconciliationStatus":"未核销",
        "ReceivableReconciliationStatus":"未核销",
        "BusinessCreator":"姚杰",
        "ContainerDescription":"1*20GP",
        "AppointedAgent":"COMM FORWARDING COMPANY",
        "MasterFreightTerms":"FREIGHT PREPAID",
        "SplitFreightTerms":"FREIGHT PREPAID",
        "TradeTerms":"FBM",
        "OperationMode":"一主一分",
        "CustomField1":"",
        "CustomField2":"",
        "CustomField3":"",
        "ProfitReviewStatus":"未审核",
        "RouteName":"东南亚",
        "RouteManager":"",
        "DestinationAgent":"天津京滨报关行",
        "CustomPosition1":"",
        "CustomPosition2":"",
        "PickupDeliveryLocation":"SZ",
        "TruckPickupTime":"2020-10-31",
        "BookingNumber":"ASHAYIN200595345",
        "SopStatus":"订舱(未订舱),配船(Y),离港(Y),到港(Y),换单(Y),提箱(Y),报关(Y),送货(Y)",
        "CancellationReviewReason":"",
        "ChargeLockTime":"2025-02-21 15:28:55",
        "PayableLockTime":"2025-02-21 15:28:55"
      },
      {
        "BusinessNumber":"AFS2009002",
        "ContainerType":"整箱",
        "BusinessType":"海运出口",
        "MasterNumber":"C245051198",
        "SplitNumber":"AFS2009002",
        "CustomerName":"上海沃行信息技术有限公司",
        "CargoType":"普货",
        "CustomerLevel":"普通客户",
        "ContractStatus":"合约失效",
        "CarrierName":"阳明海运集团",
        "VesselName":"RACHA BHUM",
        "VoyageFlight":"148S",
        "LoadingPort":"DALIAN",
        "DestinationPort":"DELHI",
        "DeliveryPlace":"MONTERREY",
        "DischargingPort":"MANZANILLO,MEXICO",
        "Etd":"2020-09-04",
        "Eta":"2020-10-08",
        "BusinessDate":"2020-09-04",
        "BookingAgent":"上海联合国际船舶代理有限公司",
        "CreationDate":"2020-09-11",
        "VoucherWord":"",
        "VoucherNumber":"0",
        "BusinessRefNumber":"XMEF20080274",
        "ProjectNumber":"1111111",
        "OperationStaff":"邵阳",
        "SalesStaff":"刘风彩",
        "CustomerServiceStaff":"姚杰",
        "DocumentStaff":"邵阳",
        "SolicitationType":"指定货",
        "Status":"正操作",
        "ActualChargeableWeight":131.77,
        "Profit":1925.0,
        "TotalRevenue":116745.0,
        "TotalCost":114820.0,
        "PayableReconciliationStatus":"未核销",
        "ReceivableReconciliationStatus":"未核销",
        "BusinessCreator":"邵阳",
        "ContainerDescription":"4*40HC",
        "AppointedAgent":"4 POINTS LOGISTICS MEXICO S.A. DE C.V.",
        "MasterFreightTerms":"FREIGHT PREPAID",
        "SplitFreightTerms":"FREIGHT COLLECT",
        "TradeTerms":"CIF",
        "OperationMode":"一主一分",
        "CustomField1":"",
        "CustomField2":"",
        "CustomField3":"",
        "ProfitReviewStatus":"未审核",
        "RouteName":"墨西哥",
        "RouteManager":"",
        "DestinationAgent":"天津京滨报关行",
        "CustomPosition1":"",
        "CustomPosition2":"",
        "PickupDeliveryLocation":"SZ",
        "TruckPickupTime":"2020-10-31",
        "BookingNumber":"ASHAYIN200595345",
        "SopStatus":"接单(未接单),订舱(pending),货物进仓(未入库),安排拖车(未派车),货物装箱(未装箱),报关单证(未收到),离港(未离港),提单(未制单),到港(未到港),已完结(),卸区(未确定)",
        "CancellationReviewReason":"",
        "ChargeLockTime":"2025-02-21 15:28:55",
        "PayableLockTime":"2025-02-21 15:28:55"
      },
      {
        "BusinessNumber":"AFS2009001",
        "ContainerType":"整箱",
        "BusinessType":"海运出口",
        "MasterNumber":"CNCT450911",
        "SplitNumber":"AFS2009001",
        "CustomerName":"江苏球迅国际货运代理有限公司",
        "CargoType":"普货",
        "CustomerLevel":"普通客户",
        "ContractStatus":"未签约",
        "CarrierName":"法国达飞轮船有限公司",
        "VesselName":"APL BARCELONA",
        "VoyageFlight":"V.0PP7FE",
        "LoadingPort":"NINGBO",
        "DestinationPort":"DELHI",
        "DeliveryPlace":"CAUCEDO",
        "DischargingPort":"CAUCEDO",
        "Etd":"2020-08-27",
        "Eta":"2020-09-28",
        "BusinessDate":"2020-08-27",
        "BookingAgent":"上海联合国际船舶代理有限公司",
        "CreationDate":"2020-09-11",
        "VoucherWord":"",
        "VoucherNumber":"0",
        "BusinessRefNumber":"XMEF20080274",
        "ProjectNumber":"AFS2009001",
        "OperationStaff":"邵阳",
        "SalesStaff":"邵阳",
        "CustomerServiceStaff":"姚杰",
        "DocumentStaff":"邵阳",
        "SolicitationType":"自揽货",
        "Status":"已审核",
        "ActualChargeableWeight":20.0,
        "Profit":2533.0,
        "TotalRevenue":20715.1,
        "TotalCost":18182.1,
        "PayableReconciliationStatus":"未核销",
        "ReceivableReconciliationStatus":"未核销",
        "BusinessCreator":"邵阳",
        "ContainerDescription":"1*20GP",
        "AppointedAgent":"4 POINTS LOGISTICS MEXICO S.A. DE C.V.",
        "MasterFreightTerms":"FREIGHT PREPAID",
        "SplitFreightTerms":"FREIGHT PREPAID",
        "TradeTerms":"CIF",
        "OperationMode":"一主一分",
        "CustomField1":"",
        "CustomField2":"",
        "CustomField3":"",
        "ProfitReviewStatus":"未审核",
        "RouteName":"加勒比",
        "RouteManager":"",
        "DestinationAgent":"天津京滨报关行",
        "CustomPosition1":"",
        "CustomPosition2":"",
        "PickupDeliveryLocation":"SZ",
        "TruckPickupTime":"2020-10-31",
        "BookingNumber":"ASHAYIN200595345",
        "SopStatus":"接单(未接单),订舱(pending),货物进仓(未入库),安排拖车(未派车),货物装箱(未装箱),报关单证(未收到),离港(未离港),提单(未制单),到港(未到港),已完结(),卸区(未确定)",
        "CancellationReviewReason":"",
        "ChargeLockTime":"2025-02-21 15:28:55",
        "PayableLockTime":"2025-02-21 15:28:55"
      }
];


// 获取账单管理台账列表
export const getExpenseReviewList = async (): Promise<ExpenseReviewItemProps[]> => {
    return expenseReviewItems;
}

// 保存账单管理
export const saveExpenseReview = async (data: ExpenseReviewItemProps, onUploadProgress?: (progress: number) => void): Promise<ExpenseReviewItemProps> => {
    // 模拟上传进度
    if (onUploadProgress) {
        let progress = 0;
        const interval = setInterval(() => {
            progress += 10;
            onUploadProgress(progress);
            if (progress >= 100) {
                clearInterval(interval);
            }
        }, 1000);
    }
    return data;
}


/*
// 获取币制信息
export const getExpenseReviewList = async (): Promise<ExpenseReviewItemProps[]> => {
  const response = await request({
    method: "GET",
    url: "/expense_review"
  })
  const responseData = response?.data as ApiRes<ExpenseReviewItemProps[]>;
  return responseData.data || [];
}

export const saveExpenseReview = (data:ExpenseReviewItemProps,onUploadProgress: (progress: number) => void) => {
  return requestWithProgress({
    method: 'POST',
    url: "/expense_review/save",
    data:data,
    onUploadProgress: (progress) => {
        onUploadProgress(progress);
    }
  })
}
*/
