
import { NotOffFeesItemProps } from '@/types/settlement_center/finance_manage/not_off_fees';
import request, {ApiRes,requestWithProgress } from '../../request'
import { NotOffSettingItemProps } from "@/types/settlement_center/finance_manage/not_off_setting";

const notOffSettingItems:NotOffSettingItemProps[] = [
  {
      "BusinessNumber": "AFS2007004",
      "SettlementUnit": "上海大洋行有限公司",
      "DomesticOrForeign": "国内",
      "MasterOrderNumber": "KMTCSHAF703978",
      "SubOrderNumber": "AFS2007004",
      "InvoiceTitle": "上海大洋行有限公司",
      "InvoiceNumber": "6666.0",
      "BillNumber": "",
      "ReconciliationNumber": "",
      "Customer": "上海大洋行有限公司",
      "BusinessType": "海运出口",
      "BusinessDate": "2020-08-07",
      "VesselAndVoyage": "KMTC QINGDAO/V.2008S",
      "PortOfLoading": "SHANGHAI",
      "UnitPrice": 33,
      "PortOfDestination": "LOS ANGELES,CA",
      "BillDueDate": "",
      "Sales": "刘风彩",
      "ProvisionallyAccrued": "否",
      "OverseasCustomerService": "",
      "OnSiteOperation": "",
      "Operation": "刘风彩",
      "FinanceDate": "",
      "PaymentType": "应收",
      "FeeStatus": "未提交",
      "ConfirmationStatus": "未确认",
      "FeeName": "拖车费",
      "Currency": "RMB",
      "CustomBusinessType": "",
      "Quantity": 1,
      "TaxInclusivePrice": 33,
      "TaxExclusivePrice": 33,
      "TaxRate": 0,
      "TaxAmount": 0,
      "ContactPerson": "",
      "WriteOffAmount": 0,
      "UnwriteOffAmount": 33,
      "FeeRemark": "",
      "CustomPosition1": "",
      "CustomPosition2": "",
      "Etd": "2020-08-07",
      "Eta": "",
      "Carrier": "高丽海运株式会社",
      "PickupDeliveryLocation": "SHANGHAI",
      "ActualPickupTime": "",
      "Sono": "KMTCSHAF703978,KMTCSHAF703978A",
      "BusinessStatus": "正操作"
  },
  {
      "BusinessNumber": "AFS2007004",
      "SettlementUnit": "上海大洋行有限公司",
      "DomesticOrForeign": "国内",
      "MasterOrderNumber": "KMTCSHAF703978",
      "SubOrderNumber": "AFS2007004",
      "InvoiceTitle": "上海大洋行有限公司",
      "InvoiceNumber": "6666.0",
      "BillNumber": "",
      "ReconciliationNumber": "",
      "Customer": "上海大洋行有限公司",
      "BusinessType": "海运出口",
      "BusinessDate": "2020-08-07",
      "VesselAndVoyage": "KMTC QINGDAO/V.2008S",
      "PortOfLoading": "SHANGHAI",
      "UnitPrice": 22,
      "PortOfDestination": "LOS ANGELES,CA",
      "BillDueDate": "",
      "Sales": "刘风彩",
      "ProvisionallyAccrued": "否",
      "OverseasCustomerService": "",
      "OnSiteOperation": "",
      "Operation": "刘风彩",
      "FinanceDate": "",
      "PaymentType": "应收",
      "FeeStatus": "未提交",
      "ConfirmationStatus": "未确认",
      "FeeName": "拖车费",
      "Currency": "RMB",
      "CustomBusinessType": "",
      "Quantity": 1,
      "TaxInclusivePrice": 22,
      "TaxExclusivePrice": 22,
      "TaxRate": 0,
      "TaxAmount": 0,
      "ContactPerson": "",
      "WriteOffAmount": 0,
      "UnwriteOffAmount": 22,
      "FeeRemark": "",
      "CustomPosition1": "",
      "CustomPosition2": "",
      "Etd": "2020-08-07",
      "Eta": "",
      "Carrier": "高丽海运株式会社",
      "PickupDeliveryLocation": "SHANGHAI",
      "ActualPickupTime": "",
      "Sono": "KMTCSHAF703978,KMTCSHAF703978A",
      "BusinessStatus": "正操作"
  },
  {
      "BusinessNumber": "AFS2007004",
      "SettlementUnit": "上海大洋行有限公司",
      "DomesticOrForeign": "国内",
      "MasterOrderNumber": "KMTCSHAF703978",
      "SubOrderNumber": "AFS2007004",
      "InvoiceTitle": "上海大洋行有限公司",
      "InvoiceNumber": "6666.0",
      "BillNumber": "SH25020002D",
      "ReconciliationNumber": "",
      "Customer": "上海大洋行有限公司",
      "BusinessType": "海运出口",
      "BusinessDate": "2020-08-07",
      "VesselAndVoyage": "KMTC QINGDAO/V.2008S",
      "PortOfLoading": "SHANGHAI",
      "UnitPrice": 222,
      "PortOfDestination": "LOS ANGELES,CA",
      "BillDueDate": "",
      "Sales": "刘风彩",
      "ProvisionallyAccrued": "否",
      "OverseasCustomerService": "",
      "OnSiteOperation": "",
      "Operation": "刘风彩",
      "FinanceDate": "",
      "PaymentType": "应收",
      "FeeStatus": "未提交",
      "ConfirmationStatus": "未确认",
      "FeeName": "堆存费",
      "Currency": "RMB",
      "CustomBusinessType": "",
      "Quantity": 1,
      "TaxInclusivePrice": 222,
      "TaxExclusivePrice": 222,
      "TaxRate": 0,
      "TaxAmount": 0,
      "ContactPerson": "",
      "WriteOffAmount": 0,
      "UnwriteOffAmount": 222,
      "FeeRemark": "",
      "CustomPosition1": "",
      "CustomPosition2": "",
      "Etd": "2020-08-07",
      "Eta": "",
      "Carrier": "高丽海运株式会社",
      "PickupDeliveryLocation": "SHANGHAI",
      "ActualPickupTime": "",
      "Sono": "KMTCSHAF703978,KMTCSHAF703978A",
      "BusinessStatus": "正操作"
  },
  {
      "BusinessNumber": "AFS2007004",
      "SettlementUnit": "COMM FORWARDING COMPANY",
      "DomesticOrForeign": "国外",
      "MasterOrderNumber": "KMTCSHAF703978",
      "SubOrderNumber": "AFS2007004",
      "InvoiceTitle": "上海大洋行有限公司",
      "InvoiceNumber": "6666.0",
      "BillNumber": "SH25020002D",
      "ReconciliationNumber": "",
      "Customer": "上海大洋行有限公司",
      "BusinessType": "海运出口",
      "BusinessDate": "2020-08-07",
      "VesselAndVoyage": "KMTC QINGDAO/V.2008S",
      "PortOfLoading": "SHANGHAI",
      "UnitPrice": 2500,
      "PortOfDestination": "LOS ANGELES,CA",
      "BillDueDate": "",
      "Sales": "刘风彩",
      "ProvisionallyAccrued": "否",
      "OverseasCustomerService": "",
      "OnSiteOperation": "",
      "Operation": "刘风彩",
      "FinanceDate": "",
      "PaymentType": "应收",
      "FeeStatus": "未提交",
      "ConfirmationStatus": "未确认",
      "FeeName": "打板费",
      "Currency": "USD",
      "CustomBusinessType": "",
      "Quantity": 1,
      "TaxInclusivePrice": 2500,
      "TaxExclusivePrice": 2500,
      "TaxRate": 0,
      "TaxAmount": 0,
      "ContactPerson": "",
      "WriteOffAmount": 0,
      "UnwriteOffAmount": 2500,
      "FeeRemark": "",
      "CustomPosition1": "",
      "CustomPosition2": "",
      "Etd": "2020-08-07",
      "Eta": "",
      "Carrier": "高丽海运株式会社",
      "PickupDeliveryLocation": "SHANGHAI",
      "ActualPickupTime": "",
      "Sono": "KMTCSHAF703978,KMTCSHAF703978A",
      "BusinessStatus": "正操作"
  },
  {
      "BusinessNumber": "AFS2007004",
      "SettlementUnit": "COMM FORWARDING COMPANY",
      "DomesticOrForeign": "国外",
      "MasterOrderNumber": "KMTCSHAF703978",
      "SubOrderNumber": "AFS2007004",
      "InvoiceTitle": "COMM FORWARDING COMPANY",
      "InvoiceNumber": "6666.0",
      "BillNumber": "SH20080001D",
      "ReconciliationNumber": "",
      "Customer": "上海大洋行有限公司",
      "BusinessType": "海运出口",
      "BusinessDate": "2020-08-07",
      "VesselAndVoyage": "KMTC QINGDAO/V.2008S",
      "PortOfLoading": "SHANGHAI",
      "UnitPrice": 25,
      "PortOfDestination": "LOS ANGELES,CA",
      "BillDueDate": "",
      "Sales": "刘风彩",
      "ProvisionallyAccrued": "否",
      "OverseasCustomerService": "",
      "OnSiteOperation": "",
      "Operation": "刘风彩",
      "FinanceDate": "",
      "PaymentType": "应收",
      "FeeStatus": "未提交",
      "ConfirmationStatus": "未确认",
      "FeeName": "利润分成",
      "Currency": "USD",
      "CustomBusinessType": "",
      "Quantity": 1,
      "TaxInclusivePrice": 25,
      "TaxExclusivePrice": 25,
      "TaxRate": 0,
      "TaxAmount": 0,
      "ContactPerson": "",
      "WriteOffAmount": 0,
      "UnwriteOffAmount": 25,
      "FeeRemark": "",
      "CustomPosition1": "",
      "CustomPosition2": "",
      "Etd": "2020-08-07",
      "Eta": "",
      "Carrier": "高丽海运株式会社",
      "PickupDeliveryLocation": "SHANGHAI",
      "ActualPickupTime": "",
      "Sono": "KMTCSHAF703978,KMTCSHAF703978A",
      "BusinessStatus": "正操作"
  },
  {
      "BusinessNumber": "AFS2007004",
      "SettlementUnit": "COMM FORWARDING COMPANY",
      "DomesticOrForeign": "国外",
      "MasterOrderNumber": "KMTCSHAF703978",
      "SubOrderNumber": "AFS2007004",
      "InvoiceTitle": "COMM FORWARDING COMPANY",
      "InvoiceNumber": "6666.0",
      "BillNumber": "SH20080001D",
      "ReconciliationNumber": "",
      "Customer": "上海大洋行有限公司",
      "BusinessType": "海运出口",
      "BusinessDate": "2020-08-07",
      "VesselAndVoyage": "KMTC QINGDAO/V.2008S",
      "PortOfLoading": "SHANGHAI",
      "UnitPrice": 50,
      "PortOfDestination": "LOS ANGELES,CA",
      "BillDueDate": "",
      "Sales": "刘风彩",
      "ProvisionallyAccrued": "否",
      "OverseasCustomerService": "",
      "OnSiteOperation": "",
      "Operation": "刘风彩",
      "FinanceDate": "",
      "PaymentType": "应收",
      "FeeStatus": "未提交",
      "ConfirmationStatus": "未确认",
      "FeeName": "操作费",
      "Currency": "USD",
      "CustomBusinessType": "",
      "Quantity": 1,
      "TaxInclusivePrice": 50,
      "TaxExclusivePrice": 50,
      "TaxRate": 0,
      "TaxAmount": 0,
      "ContactPerson": "",
      "WriteOffAmount": 0,
      "UnwriteOffAmount": 50,
      "FeeRemark": "",
      "CustomPosition1": "",
      "CustomPosition2": "",
      "Etd": "2020-08-07",
      "Eta": "",
      "Carrier": "高丽海运株式会社",
      "PickupDeliveryLocation": "SHANGHAI",
      "ActualPickupTime": "",
      "Sono": "KMTCSHAF703978,KMTCSHAF703978A",
      "BusinessStatus": "正操作"
  }
];

const notOffFeesItems:NotOffFeesItemProps[] = [
  {
      "BusinessNumber": "SHSE20020008",
      "MBL": "WSTBND126407447",
      "BusinessDate": "2020-01-15",
      "FeeName": "操作费",
      "ReconciliationStatus": "未确认",
      "ExchangeRate": 1.0000,
      "BusinessStatus": "正操作",
      "CreditDebit": "应付",
      "Currency": "RMB",
      "WriteOffExchangeRate": 1.0000,
      "Amount": 200,
      "LastBalance": 200,
      "CurrentWriteOff": 200,
      "CurrentBalance": 0
  },
  {
      "BusinessNumber": "SHSE20020008",
      "MBL": "WSTBND126407447",
      "BusinessDate": "2020-01-15",
      "FeeName": "文件费",
      "ReconciliationStatus": "未确认",
      "ExchangeRate": 1,
      "BusinessStatus": "正操作",
      "CreditDebit": "应付",
      "Currency": "RMB",
      "WriteOffExchangeRate": 1,
      "Amount": 500,
      "LastBalance": 500,
      "CurrentWriteOff": 500,
      "CurrentBalance": 0
  },
  {
      "BusinessNumber": "SHSE20020008",
      "MBL": "WSTBND126407447",
      "BusinessDate": "2020-01-15",
      "FeeName": "港杂费",
      "ReconciliationStatus": "未确认",
      "ExchangeRate": 1,
      "BusinessStatus": "正操作",
      "CreditDebit": "应付",
      "Currency": "RMB",
      "WriteOffExchangeRate": 1,
      "Amount": 1480,
      "LastBalance": 1480,
      "CurrentWriteOff": 1480,
      "CurrentBalance": 0
  },
  {
      "BusinessNumber": "SHSE20020008",
      "MBL": "WSTBND126407447",
      "BusinessDate": "2020-01-15",
      "FeeName": "称重声明费",
      "ReconciliationStatus": "未确认",
      "ExchangeRate": 1,
      "BusinessStatus": "正操作",
      "CreditDebit": "应付",
      "Currency": "RMB",
      "WriteOffExchangeRate": 1,
      "Amount": 160,
      "LastBalance": 160,
      "CurrentWriteOff": 160,
      "CurrentBalance": 0
  },
  {
      "BusinessNumber": "SHSE20020008",
      "MBL": "WSTBND126407447",
      "BusinessDate": "2020-01-15",
      "FeeName": "舱单费",
      "ReconciliationStatus": "未确认",
      "ExchangeRate": 1,
      "BusinessStatus": "正操作",
      "CreditDebit": "应付",
      "Currency": "RMB",
      "WriteOffExchangeRate": 1,
      "Amount": 100,
      "LastBalance": 100,
      "CurrentWriteOff": 100,
      "CurrentBalance": 0
  },
  {
      "BusinessNumber": "SHSE20020008",
      "MBL": "WSTBND126407447",
      "BusinessDate": "2020-01-15",
      "FeeName": "THC",
      "ReconciliationStatus": "未确认",
      "ExchangeRate": 1,
      "BusinessStatus": "正操作",
      "CreditDebit": "应付",
      "Currency": "RMB",
      "WriteOffExchangeRate": 1,
      "Amount": 6000,
      "LastBalance": 6000,
      "CurrentWriteOff": 6000,
      "CurrentBalance": 0
  },
  {
      "BusinessNumber": "SHSE20020008",
      "MBL": "WSTBND126407447",
      "BusinessDate": "2020-01-15",
      "FeeName": "货物处理费用",
      "ReconciliationStatus": "未确认",
      "ExchangeRate": 1,
      "BusinessStatus": "正操作",
      "CreditDebit": "应付",
      "Currency": "RMB",
      "WriteOffExchangeRate": 1,
      "Amount": 200,
      "LastBalance": 200,
      "CurrentWriteOff": 200,
      "CurrentBalance": 0
  },
  {
      "BusinessNumber": "SHSE20020008",
      "MBL": "WSTBND126407447",
      "BusinessDate": "2020-01-15",
      "FeeName": "安保费",
      "ReconciliationStatus": "未确认",
      "ExchangeRate": 1,
      "BusinessStatus": "正操作",
      "CreditDebit": "应付",
      "Currency": "RMB",
      "WriteOffExchangeRate": 1,
      "Amount": 80,
      "LastBalance": 80,
      "CurrentWriteOff": 80,
      "CurrentBalance": 0
  },
  {
      "BusinessNumber": "SHSE20020008",
      "MBL": "WSTBND126407447",
      "BusinessDate": "2020-01-15",
      "FeeName": "铅封费",
      "ReconciliationStatus": "未确认",
      "ExchangeRate": 1,
      "BusinessStatus": "正操作",
      "CreditDebit": "应付",
      "Currency": "RMB",
      "WriteOffExchangeRate": 1,
      "Amount": 360,
      "LastBalance": 360,
      "CurrentWriteOff": 360,
      "CurrentBalance": 0
  },
  {
      "BusinessNumber": "SHSE20020008",
      "MBL": "WSTBND126407447",
      "BusinessDate": "2020-01-15",
      "FeeName": "海运费",
      "ReconciliationStatus": "未确认",
      "ExchangeRate": 7.2,
      "BusinessStatus": "正操作",
      "CreditDebit": "应付",
      "Currency": "USD",
      "WriteOffExchangeRate": 7,
      "Amount": 13200,
      "LastBalance": 13200,
      "CurrentWriteOff": 13200,
      "CurrentBalance": 0
  }
];
// 获取币制信息
export const getNotOffSettingList = async () : Promise<NotOffSettingItemProps[]> => {
  // const response = await request({
  //   method: "GET",
  //   url: "/not_off_setting"
  // });
  // const responseData = response?.data as ApiRes<NotOffSettingItemProps[]>;
  // return responseData.data || [];
  return notOffSettingItems;
}

export const getNotOffFeesList = async () : Promise<NotOffFeesItemProps[]> => {
  const response = await request({
    method: "GET",
    url: "/not_off_fees"
  });
  const responseData = response?.data as ApiRes<NotOffFeesItemProps[]>;
  return responseData.data || [];
}

export const saveNotOffSetting = (data:NotOffSettingItemProps,onUploadProgress: (progress: number) => void) => {
  return requestWithProgress({
    method: 'POST',
    url: "/not_off_setting/save",
    data:data,
    onUploadProgress: (progress) => {
        onUploadProgress(progress);
    }
  })
}

