import { TableColumnsType, Tag, Popconfirm } from 'antd';
import { OrdersItemProps } from "@/types/orders/orders";
import i18n from '@/i18n';
import LocaleHelper from '@/utils/localeHelper';
import { NavLink,Link } from 'react-router-dom';


export const getColumns = (handleEdit: (record: OrdersItemProps) => void, handleDelete: (record: OrdersItemProps) => void): TableColumnsType<OrdersItemProps> => [

    {
        title: i18n.t(LocaleHelper.getOrdersBusinessId()),
        width: '200px',
        dataIndex: 'BusinessId',
        sorter: true,
        align: 'left',
        fixed: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersMainOrderNumber()),
        width: '200px',
        dataIndex: 'MainOrderNumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersCarrier()),
        width: '200px',
        dataIndex: 'Carrier',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersShipName()),
        width: 200,
        dataIndex: 'ShipName',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersVoyage()),
        width: 200,
        dataIndex: 'Voyage',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersCustomer()),
        width: 200,
        dataIndex: 'Customer',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersBusinessDate()),
        width: 200,
        dataIndex: 'BusinessDate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersContractStatus()),
        width: 200,
        dataIndex: 'ContractStatus',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersDeparturePort()),
        width: 200,
        dataIndex: 'DeparturePort',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersDestinationPort()),
        width: 200,
        dataIndex: 'DestinationPort',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersDepartureDate()),
        width: 200,
        dataIndex: 'DepartureDate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersCustomerService()),
        width: 200,
        dataIndex: 'CustomerService',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersAirWaybillChargedWeight()),
        width: 200,
        dataIndex: 'AirWaybillChargedWeight',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersAirBookingChargedWeight()),
        width: 200,
        dataIndex: 'AirBookingChargedWeight',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersBookingAgent()),
        width: 200,
        dataIndex: 'BookingAgent',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersProjectId()),
        width: 200,
        dataIndex: 'ProjectId',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersOperation()),
        width: 200,
        dataIndex: 'Operation',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersSales()),
        width: 200,
        dataIndex: 'Sales',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersSalesDepartment()),
        width: 200,
        dataIndex: 'SalesDepartment',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersOverseasService()),
        width: 200,
        dataIndex: 'OverseasService',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersStatus()),
        width: 200,
        dataIndex: 'Status',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersBusinessType()),
        width: 200,
        dataIndex: 'BusinessType',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersActualChargedWeight()),
        width: 200,
        dataIndex: 'ActualChargedWeight',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersEntrustedPieces()),
        width: 200,
        dataIndex: 'EntrustedPieces',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersContainerNumber()),
        width: 200,
        dataIndex: 'ContainerNumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersEntrustedGrossWeight()),
        width: 200,
        dataIndex: 'EntrustedGrossWeight',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersEntrustedVolume()),
        width: 200,
        dataIndex: 'EntrustedVolume',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersActualPieces()),
        width: 200,
        dataIndex: 'ActualPieces',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersActualGrossWeight()),
        width: 200,
        dataIndex: 'ActualGrossWeight',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersActualVolume()),
        width: 200,
        dataIndex: 'ActualVolume',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersPayableVerificationStatus()),
        width: 200,
        dataIndex: 'PayableVerificationStatus',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersReceivableVerificationStatus()),
        width: 200,
        dataIndex: 'ReceivableVerificationStatus',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersPurchasePrice()),
        width: 200,
        dataIndex: 'PurchasePrice',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersSellingPrice()),
        width: 200,
        dataIndex: 'SellingPrice',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersArrivalDate()),
        width: 200,
        dataIndex: 'ArrivalDate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersDesignatedFreightAgent()),
        width: 200,
        dataIndex: 'DesignatedFreightAgent',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersFinalDestination()),
        width: 200,
        dataIndex: 'FinalDestination',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersLocalService()),
        width: 200,
        dataIndex: 'LocalService',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersCreationDate()),
        width: 200,
        dataIndex: 'CreationDate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersCustomBusinessType()),
        width: 200,
        dataIndex: 'CustomBusinessType',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersBusinessReferenceNumber()),
        width: 200,
        dataIndex: 'BusinessReferenceNumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersDeliveryDate()),
        width: 200,
        dataIndex: 'DeliveryDate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersShippingCompanyContractNumber()),
        width: 200,
        dataIndex: 'ShippingCompanyContractNumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersInternalContractNumber()),
        width: 200,
        dataIndex: 'InternalContractNumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersQuotationNumber()),
        width: 200,
        dataIndex: 'QuotationNumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersShippingRoute()),
        width: 200,
        dataIndex: 'ShippingRoute',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersTeu()),
        width: 200,
        dataIndex: 'Teu',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersContainerTypeQuantity()),
        width: 200,
        dataIndex: 'ContainerTypeQuantity',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersCollectionSales()),
        width: 200,
        dataIndex: 'CollectionSales',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersOperationDate()),
        width: 200,
        dataIndex: 'OperationDate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersActualDepartureDateAtd()),
        width: 200,
        dataIndex: 'ActualDepartureDateAtd',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersActualArrivalDateAta()),
        width: 200,
        dataIndex: 'ActualArrivalDateAta',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersConsignee()),
        width: 200,
        dataIndex: 'Consignee',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersShipper()),
        width: 200,
        dataIndex: 'Shipper',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersReceivableInvoiceStatus()),
        width: 200,
        dataIndex: 'ReceivableInvoiceStatus',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersPayableInvoiceStatus()),
        width: 200,
        dataIndex: 'PayableInvoiceStatus',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersCustomerContact()),
        width: 200,
        dataIndex: 'CustomerContact',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersSopStatus()),
        width: 200,
        dataIndex: 'SopStatus',
        // sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersSopTemplateName()),
        width: 200,
        dataIndex: 'SopTemplateName',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersCargoType()),
        width: 200,
        dataIndex: 'CargoType',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersActualPickupTime()),
        width: 200,
        dataIndex: 'ActualPickupTime',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersActualReturnEmptyTime()),
        width: 200,
        dataIndex: 'ActualReturnEmptyTime',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersSubOrderNumber()),
        width: 200,
        dataIndex: 'SubOrderNumber',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersCustomerLevel()),
        width: 200,
        dataIndex: 'CustomerLevel',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersActualDeliveryTime()),
        width: 200,
        dataIndex: 'ActualDeliveryTime',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersCustomerServiceDepartment()),
        width: 200,
        dataIndex: 'CustomerServiceDepartment',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersDocumentationDepartment()),
        width: 200,
        dataIndex: 'DocumentationDepartment',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersReceivableFeesEntered()),
        width: 200,
        dataIndex: 'ReceivableFeesEntered',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersPayableFeesEntered()),
        width: 200,
        dataIndex: 'PayableFeesEntered',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersBranchDepartureDate()),
        width: 200,
        dataIndex: 'BranchDepartureDate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersBranchArrivalDate()),
        width: 200,
        dataIndex: 'BranchArrivalDate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersBargeDepartureDate()),
        width: 200,
        dataIndex: 'BargeDepartureDate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersBargeArrivalDate()),
        width: 200,
        dataIndex: 'BargeArrivalDate',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersMark()),
        width: 200,
        dataIndex: 'Mark',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersEntryTime()),
        width: 200,
        dataIndex: 'EntryTime',
        sorter: true,
        align: 'center',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersCollectionType()),
        width: 200,
        dataIndex: 'CollectionType',
        sorter: true,
        align: 'left',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersProfit()),
        width: 200,
        dataIndex: 'Profit',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersIncome()),
        width: 200,
        dataIndex: 'Income',
        sorter: true,
        align: 'right',
    },
    {
        title: i18n.t(LocaleHelper.getOrdersExpenditure()),
        width: 200,
        dataIndex: 'Expenditure',
        sorter: true,
        align: 'right',
    },
    {
        title: '操作',
        key: 'operation',
        fixed: 'right',
        width: 200,
        render: (_, record) => (
        <>
            <a>启用</a>
            <NavLink to={`/orders/detail?businessId=${record.BusinessId}`}>编辑</NavLink>
            <Popconfirm title="确定要删除吗?" cancelText="取消" okText="确定" onConfirm={() => handleDelete(record)}>
                <a>删除</a>
            </Popconfirm>
        </>
        ),
    },
];
